"""One-off writer for the "General Shorts Outliers" tab: a curated swipe file of
ultra-viral, cross-niche YouTube Shorts packaging, each translated into a
cold-approach-ready title and thumbnail concept.

Entries here must be real, statistically verified outliers found by
general_shorts_finder.py (run via GitHub Actions) — genuinely exceptional Shorts
(5M+ views, or 50x+ channel average, or 20x+ subscriber breakout in the last 90 days),
not merely good ones. That script only surfaces candidates; picking which ones cleanly
translate into a cold-approach idea and writing the analysis below is a manual step.
Cold-approach thumbnail concepts should put a woman front and center as the visual
star, per the channel's packaging convention. This file is not a live API pull itself —
run it manually whenever new entries are added.
"""
import os

import gspread

from youtube_outliers import GOOGLE_SPREADSHEET_ID, build_google_sheets_client

SHEET_NAME = os.getenv("GENERAL_SHORTS_SHEET_NAME", "General Shorts Outliers")

HEADERS = [
    "Original Video Title",
    "Original Channel",
    "Video URL",
    "Original Niche",
    "Views",
    "Subscribers",
    "Outlier Score",
    "Core Packaging Pattern",
    "Psychological Trigger",
    "Thumbnail Breakdown",
    "Title Formula",
    "Why It Worked",
    "Cold Approach Translation (Concept)",
    "Cold Approach Title",
    "Cold Approach Thumbnail Concept",
    "Notes",
    "Status",
]

SWIPE_FILE = [
    {
        "title": "When a Delivery Driver Outsmarts a Porch Pirate…",
        "channel": "Patrol POV",
        "url": "https://www.youtube.com/watch?v=Sm80NMnoqTY",
        "niche": "Raw Security-Cam Justice/POV",
        "views": "39,315,165",
        "views_num": 39315165,
        "subscribers": 117000,
        "score": "336.0x subs",
        "pattern": "Raw, unproduced security-camera footage framed as \"gotcha\" justice content, with a plain caption labeling exactly what's happening rather than describing the twist — letting the reveal do the work.",
        "trigger": "Curiosity about how the \"outsmarting\" happens (an open loop, no visual spoiler) + the voyeuristic pull of real surveillance footage feeling more authentic than staged content + a satisfying justice payoff implied by the title.",
        "thumbnail": "A security-camera/doorbell-cam style POV shot of a delivery person opening a gate, an on-screen caption \"Delivery Driver 'OPENS GATE'\" in a plain chat-label style, muted outdoor daylight colors, raw unproduced surveillance-footage aesthetic.",
        "formula": "\"When A [Underdog Role] Outsmarts A [Wrongdoer]…\"",
        "why": "The trailing \"…\" withholds the actual twist, the plain surveillance-camera aesthetic (no visible editing or music cues) reads as unquestionably real, and \"outsmarts\" promises a satisfying reversal without revealing how.",
        "translation": "Reframe \"delivery driver outsmarts a porch pirate\" as \"guy outsmarts a dismissive reaction and turns the interaction around\" — same raw, unproduced POV aesthetic and withheld-twist title structure.",
        "ca_title": "When A Guy Outsmarts A Girl's \"I Have A Boyfriend\"…",
        "ca_thumbnail": "Raw, handheld POV shot of the creator mid-conversation with a woman on a sidewalk, an on-screen caption labeling the moment plainly (e.g. \"'I Have A Boyfriend'\") in a chat-bubble style, muted natural daylight, unproduced candid framing matching the surveillance-footage aesthetic.",
        "notes": "The \"plain caption labeling the moment, not describing the twist\" device works because it trusts the raw footage to carry authenticity — over-producing this would undercut it.",
        "status": "Not Adapted",
    },
    {
        "title": "Parents Surprise Bride During Father-Daughter Dance",
        "channel": "David Micklos",
        "url": "https://www.youtube.com/watch?v=MhHVR_0WYgY",
        "niche": "Real Emotional Milestone Moment",
        "views": "10,389,410",
        "views_num": 10389410,
        "subscribers": 38200,
        "score": "272.0x subs",
        "pattern": "A real, unscripted emotional milestone moment captured with the actual spoken words overlaid as on-screen text, letting the sentimentality come from genuine dialogue rather than a title's summary.",
        "trigger": "Universal emotional resonance (parent/child milestone moments) + the caption functioning as an emotional preview that makes viewers want to hear the rest + the bride as the clear, warm visual focal point.",
        "thumbnail": "A real wedding reception scene, father and bride mid-dance, wedding guests visible in soft-focus background, on-screen caption text quoting the actual spoken line over the moment, warm string-light ballroom lighting.",
        "formula": "\"[Family Members] Surprise [Person] During [Milestone Moment]\"",
        "why": "Captioning the actual spoken words (not a generic description) gives viewers an emotional preview strong enough to click for the full context, and the milestone framing taps into a nearly universal emotional trigger.",
        "translation": "Reframe \"parents surprise the bride during a milestone dance\" as \"a genuine, unscripted emotional moment during a real interaction with a woman\" — same real-spoken-words-as-caption device, same warm, sincere tone instead of a flashy hook.",
        "ca_title": "I Told Her Something That Made Her Tear Up On The First Date",
        "ca_thumbnail": "Creator and a woman together at a warmly lit table, her visibly moved and emotional expression as the clear focal point, on-screen caption text quoting the actual line said (e.g. \"'You remind me that people like you still exist...'\"), soft warm lighting.",
        "notes": "Quoting the actual words spoken (not summarizing them) is the transferable device — it works because it's a genuine preview of the emotional payoff, not a vague tease.",
        "status": "Not Adapted",
    },
    {
        "title": "A Hidden Camera Revealed True Kindness",
        "channel": "Grandma Blessing",
        "url": "https://www.youtube.com/watch?v=lZ8oRd0j-c8",
        "niche": "Candid Chivalry/Kindness",
        "views": "854,996",
        "views_num": 854996,
        "subscribers": 15400,
        "score": "55.5x subs",
        "pattern": "A small, genuine act of chivalry caught candidly on a \"hidden camera,\" with the visual itself doing all the emotional work without needing a caption to explain it.",
        "trigger": "Warm, wholesome social proof of good character (a faith-in-humanity payoff) + the \"hidden camera\" framing implying total authenticity, since nobody knew they were being filmed + a simple, instantly-readable visual story.",
        "thumbnail": "A candid street scene, a man kneeling down helping a woman with her belongings, both genuinely engaged in the moment without posing for camera, natural park/outdoor setting, soft daylight.",
        "formula": "\"A Hidden Camera Revealed [Virtue] [Person/Place]\"",
        "why": "The thumbnail needs zero caption to explain what's happening — a person helping a stranger is immediately legible — and \"hidden camera\" as a framing device pre-empts any \"was this staged\" skepticism.",
        "translation": "This is already extremely close to dating/cold-approach content as-is — a genuine, unprompted act of chivalry toward a woman is directly relevant, not a metaphor requiring translation.",
        "ca_title": "A Hidden Camera Caught Him Helping A Stranger Before Ever Talking To Her",
        "ca_thumbnail": "Candid street scene, creator genuinely helping a woman with something small (picking up a dropped item, holding a door), both naturally engaged without posing for camera, soft natural daylight, unstaged framing.",
        "notes": "One of the cleanest possible translations found — the mechanic (genuine chivalry, caught candidly) IS the cold-approach content, not an analogy for it.",
        "status": "Not Adapted",
    },
    {
        "title": "Delivery Guy Was NOT Expecting a Porch Pirate Like This",
        "channel": "Camera Drama",
        "url": "https://www.youtube.com/watch?v=I5bGHUrwo0Y",
        "niche": "Raw Security-Cam Justice/POV",
        "views": "29,892,483",
        "views_num": 29892483,
        "subscribers": 13100,
        "score": "2281.9x subs",
        "pattern": "The same raw security-cam \"gotcha\" genre as Patrol POV's porch-pirate video — an independent channel hitting a massive breakout with the near-identical format confirms this is a proven, repeatable structure, not a one-off fluke.",
        "trigger": "Same as the format's other example: an open-loop twist withheld from the thumbnail, plus the authenticity of raw, unproduced camera footage — reinforced here by a genuinely enormous subscriber multiplier (2281.9x, one of the largest found in this entire project).",
        "thumbnail": "A doorbell/security-cam style POV shot of a delivery person on a porch, an on-screen caption \"Delivery Guy 'Deliver Package'\" labeling the moment plainly, muted daylight residential setting, raw unproduced framing.",
        "formula": "\"[Role] Was NOT Expecting a [Wrongdoer/Twist] Like This\"",
        "why": "Two different channels independently hit huge numbers with the identical raw-security-cam-plus-plain-caption format, which is strong evidence the mechanic itself (not the specific creator or story) is what's driving performance.",
        "translation": "Same translation as the format's other example — reframe the raw POV/plain-caption justice reveal around a social interaction instead of a package theft.",
        "ca_title": "She Was NOT Expecting Me To Say This Back",
        "ca_thumbnail": "Raw, handheld POV shot of the creator mid-conversation with a woman, an on-screen caption labeling the moment plainly (e.g. her exact dismissive line), muted natural daylight, unproduced candid framing.",
        "notes": "Included alongside Patrol POV's entry deliberately — two independent channels succeeding with the same mechanic is stronger proof of a repeatable format than either alone.",
        "status": "Not Adapted",
    },
    {
        "title": "A Blind Man Asked for Help... Most People Walked Away",
        "channel": "Mascal Universe",
        "url": "https://www.youtube.com/watch?v=k4d5_y4AN6I",
        "niche": "Candid Social Experiment/Kindness Test",
        "views": "763,151",
        "views_num": 763151,
        "subscribers": 19700,
        "score": "38.7x subs",
        "pattern": "A vulnerable stranger's real, unscripted request for help captured candidly, with the title stating the discouraging outcome upfront (most walked away) to set up the moment someone doesn't.",
        "trigger": "Moral tension (the viewer wants to know who, if anyone, helps) + protective/empathetic instinct toward a vulnerable person + the \"most people walked away\" framing creating suspense around the exceptions.",
        "thumbnail": "A real street scene, a blind man with a cane standing near a small group of people including a woman, candid unposed body language, a caption reading \"HE ASKED STRANGERS FOR HELP,\" natural daylight.",
        "formula": "\"A [Vulnerable Person] Asked for Help... [Discouraging Outcome/Twist]\"",
        "why": "Stating the discouraging outcome in the title (most walked away) before the viewer even sees the footage creates a moral stake — you watch specifically to see who breaks the pattern.",
        "translation": "Reframe \"a vulnerable stranger asks for help and most ignore him\" as \"a woman gives a guy a real chance when everyone before her didn't\" — same \"most people did X, then...\" suspense structure, applied to social/dating rejection patterns instead of a kindness test.",
        "ca_title": "I Approached 10 Women, Most Walked Away... Then She Didn't",
        "ca_thumbnail": "A real street scene, creator mid-approach near a small group, one woman clearly pausing to engage as the visual focal point (contrasted with others walking past in the background), candid unposed framing, natural daylight.",
        "notes": "The \"most people did X, then this one didn't\" structure is a strong, reusable suspense device independent of the specific scenario.",
        "status": "Not Adapted",
    },
    {
        "title": "Simple Girl To Princess Look 👸 Amazing Glow Up #shorts",
        "channel": "Happy Wife",
        "url": "https://www.youtube.com/watch?v=GXmlXosvg3k",
        "niche": "Transformation Reveal/Glow Up",
        "views": "14,982,516",
        "views_num": 14982516,
        "subscribers": 45900,
        "score": "326.4x subs",
        "pattern": "A dramatic before/after transformation reveal where the thumbnail shows only the polished \"after\" — an elegant, glamorous result — with the title's contrast (\"Simple Girl\" vs \"Princess\") supplying the transformation arc the image doesn't show.",
        "trigger": "Aspirational curiosity (\"how did she get from A to B?\") + the visual reward of an already-impressive \"after\" shot pulling viewers in on looks alone + a relatable starting point (\"simple girl\") making the outcome feel attainable, not just for celebrities.",
        "thumbnail": "A woman in an elegant pink dress in an ornate, upscale interior (grand ceiling, warm gold lighting), a man partially visible beside her, polished and glamorous styling, warm high-end color grade.",
        "formula": "\"[Ordinary Starting Point] To [Aspirational Outcome] Look\"",
        "why": "Showing only the impressive \"after\" in the thumbnail (not a split before/after) makes the image itself aspirational enough to click on, while the title's stated contrast promises a satisfying transformation story underneath.",
        "translation": "Reframe \"ordinary girl to princess look\" as \"overlooked to unforgettable\" — same relatable-starting-point-to-aspirational-outcome contrast, applied to how a woman is perceived/responded to rather than a styling makeover.",
        "ca_title": "Invisible To Unforgettable: How She Changed The Way Every Room Reacted To Her",
        "ca_thumbnail": "A woman looking confident and radiant in an elevated real-world setting (a nice restaurant or event), warm flattering lighting, polished styling, positioned as the clear visual star of the frame.",
        "notes": "A 326x subscriber breakout confirms the \"aspirational after-shot only\" thumbnail approach travels far beyond a beauty-niche audience.",
        "status": "Not Adapted",
    },
    {
        "title": "The Wedding Stopped When She Revealed His Biggest Secret...",
        "channel": "Good Vibes Stories",
        "url": "https://www.youtube.com/watch?v=ddDkIrcZZ4Q",
        "niche": "Dramatized Wedding-Reveal Story",
        "views": "1,322,822",
        "views_num": 1322822,
        "subscribers": 12800,
        "score": "103.3x subs",
        "pattern": "A dramatized wedding-ceremony scene interrupted at its most emotionally charged possible moment, with the bride's raw reaction as the clear visual and emotional center of the frame.",
        "trigger": "Maximum-stakes curiosity (a secret big enough to stop a wedding) + the universal emotional weight of a wedding setting + the bride's genuine-looking distress making the stakes feel real regardless of production style.",
        "thumbnail": "A real wedding ceremony scene, the bride in her dress visibly emotional/crying, a groom or family member gesturing, an on-screen caption capturing a spoken line (\"Get this crazy woman off\"), warm ceremony lighting.",
        "formula": "\"The [Major Event] Stopped When [Person] Revealed [His/Her] Biggest Secret...\"",
        "why": "Interrupting the single highest-stakes moment in a wedding (not a random point in the story) maximizes the emotional charge, and capturing the bride's raw reaction as the focal point makes the stakes legible without needing to understand the full story yet.",
        "translation": "Reframe \"a wedding secret reveal\" as \"a moment during a date/approach where everything suddenly changes\" — same maximum-stakes-interruption structure, same real-reaction-as-focal-point thumbnail.",
        "ca_title": "The Date Stopped When She Found Out The Truth About Why I Approached Her",
        "ca_thumbnail": "A real date/café setting, a woman with a genuine, emotionally charged expression as the clear focal point, an on-screen caption capturing a spoken line, warm natural lighting.",
        "notes": "Likely a dramatized/scripted format rather than a spontaneous real event — still a legitimate packaging lesson (the interruption-at-peak-stakes structure), just worth knowing it's probably staged before modeling the production style.",
        "status": "Not Adapted",
    },
    {
        "title": "She Called for Water… But Reached the Police!",
        "channel": "Speader News",
        "url": "https://www.youtube.com/watch?v=Ho-rgBL2HAA",
        "niche": "Real Investigative/Kindness Story",
        "views": "445,637",
        "views_num": 445637,
        "subscribers": 8270,
        "score": "53.9x subs",
        "pattern": "A real, documentary-style moment framed around an unexpected mismatch between what someone asked for and what actually happened, with a woman as the clear subject of the story.",
        "trigger": "Curiosity about the mismatch in the title (why would asking for water reach the police?) + the documentary/news-style visual credibility + a real person's genuine situation making the stakes feel consequential.",
        "thumbnail": "A real, candid documentary-style shot, a woman in a tracksuit among a small group of people, on-screen caption text, natural indoor daylight, unproduced news-style framing.",
        "formula": "\"[Someone] [Asked/Called] For [Small Ordinary Thing]… But [Unexpected Escalation]!\"",
        "why": "Naming a specific, small, ordinary request (water) and pairing it with a specific, surprising escalation (police) creates a concrete curiosity gap that a vague \"you won't believe what happened\" title can't match.",
        "translation": "Reframe \"asked for something small, got an unexpected escalation\" as \"asked for something small during an approach, got an unexpectedly bigger response\" — same small-ask-vs-big-escalation contrast, applied to a real social interaction.",
        "ca_title": "I Asked Her For The Time… She Ended Up Giving Me Her Number",
        "ca_thumbnail": "A real, candid documentary-style shot of the creator and a woman mid-conversation on the street, on-screen caption text, natural daylight, unproduced framing.",
        "notes": "The \"specific small ask vs. specific surprising escalation\" title contrast is a clean, concrete alternative to vague curiosity-bait phrasing.",
        "status": "Not Adapted",
    },
    {
        "title": "₹500 vs ₹50 #skincare #glowup",
        "channel": "Uneven Glow",
        "url": "https://www.youtube.com/watch?v=ohnvRiMi-rY",
        "niche": "Budget vs. Premium Comparison",
        "views": "393,288",
        "views_num": 393288,
        "subscribers": 914,
        "score": "430.3x subs",
        "pattern": "A real, unpolished selfie-style comparison between a cheap and expensive version of the same product, with the price contrast alone doing the entire hook — no dramatic claim needed.",
        "trigger": "Practical, money-relevant curiosity (\"is the expensive one actually worth it?\") + the concrete, specific price contrast being instantly legible + zero-production authenticity (a real person testing on themselves).",
        "thumbnail": "A real, plain selfie-style shot of a woman applying a skincare product to her own face, casual home setting, on-screen price labels visible, unproduced handheld framing.",
        "formula": "\"₹/$[Low Price] vs ₹/$[High Price] #[category]\"",
        "why": "A concrete price-vs-price contrast is a self-explanatory hook that needs no additional claim or drama, and testing on a real, unpolished self (not a produced beauty shot) makes the comparison feel trustworthy rather than sponsored.",
        "translation": "Reframe \"cheap vs. expensive skincare\" as \"free advice vs. paid coaching\" or \"a scripted opener vs. genuine curiosity\" — same concrete side-by-side contrast format, applied to comparing two approaches instead of two products.",
        "ca_title": "Free Advice vs $500 Coaching: Which One Actually Gets You A Number?",
        "ca_thumbnail": "A real, plain selfie-style or handheld shot of the creator testing two approaches side by side, on-screen labels for each side, casual unproduced setting matching the authenticity of the original.",
        "notes": "A massive 430x subscriber breakout on a tiny channel (under 1,000 subscribers) shows a concrete price-contrast hook alone can travel very far with zero production value.",
        "status": "Not Adapted",
    },
    {
        "title": "Inside Michael Jackson's abandoned school",
        "channel": "LordExplores",
        "url": "https://www.youtube.com/watch?v=atNiWdHNPNU",
        "niche": "Forbidden Access/Urban Exploration",
        "views": "3,829,903",
        "views_num": 3829903,
        "subscribers": 258000,
        "score": "46.3x channel avg",
        "pattern": "The same forbidden-access exploration format seen elsewhere in this project, here anchored to a globally famous named celebrity for maximum grounded specificity — the first example of this proven format in the Shorts-specific tab.",
        "trigger": "Forbidden curiosity (seeing inside a real, famous person's abandoned property) + the specificity of a world-famous name making the premise instantly recognizable + decay/mystery visuals reinforcing the \"frozen in time\" feeling.",
        "thumbnail": "A real exterior shot of a plain suburban house with a white picket fence, on-screen caption \"Part 1\" and \"Michael Jackson's childhood home,\" overcast daylight, unproduced documentary-style framing.",
        "formula": "\"Inside [World-Famous Name]'s Abandoned [Place]\"",
        "why": "Naming a globally recognizable person (rather than a regional celebrity) maximizes how many viewers instantly understand the premise's significance without any further explanation needed.",
        "translation": "Reframe \"inside a world-famous person's abandoned property\" as \"approaching at a real, world-famous, extremely difficult venue\" — same maximum-name-recognition-for-instant-stakes device.",
        "ca_title": "Approaching Women At The World's Most Exclusive Nightclub",
        "ca_thumbnail": "A real venue exterior shot, a globally recognizable location name visible on-screen, creator approaching a specific real group, unproduced documentary-style framing.",
        "notes": "Same proven mechanic as the long-form exploration entries, included here specifically because the Shorts tab didn't have an example of it yet.",
        "status": "Not Adapted",
    },
    {
        "title": "Girl Haircut Before vs After | Amazing Transformation",
        "channel": "New Hair Style King And Queen",
        "url": "https://www.youtube.com/watch?v=tB0RA5JK6dg",
        "niche": "Transformation Reveal (Hair/Beauty)",
        "views": "23,396,480",
        "views_num": 23396480,
        "subscribers": 14800,
        "score": "1580.8x subs",
        "pattern": "A real, mid-process transformation moment (scissors actively cutting) rather than a static before/after split, letting the viewer catch the reveal in progress instead of already resolved.",
        "trigger": "Anticipation of an unresolved reveal (the cut is happening NOW, not already done) + a massive subscriber breakout (1580x, one of the largest in this entire project) proving this exact mid-process framing travels far beyond a beauty-niche audience.",
        "thumbnail": "A woman in a salon chair with a stylist's scissors actively mid-cut in her hair, genuine unposed expression, real salon setting with visible equipment, natural indoor lighting.",
        "formula": "\"[Subject] [Transformation Type] Before vs After | Amazing Transformation\"",
        "why": "Catching the transformation mid-action (not the finished result) creates a stronger open loop than a static before/after split would, since the viewer hasn't seen the outcome yet.",
        "translation": "Reframe \"catching a hair transformation mid-cut\" as \"catching a woman's reaction mid-change\" — same mid-process, not-yet-resolved framing, applied to an in-progress social moment instead of a physical makeover.",
        "ca_title": "Her Reaction Before vs After I Said This | Amazing Turnaround",
        "ca_thumbnail": "A woman mid-reaction in a real setting (café, street), her expression actively shifting in real time, genuine unposed body language, natural lighting matching the candid, unresolved-moment feel.",
        "notes": "A 1580x subscriber breakout on a small channel is one of the strongest single data points in this entire project for how far a mid-process (not finished-result) reveal can travel.",
        "status": "Not Adapted",
    },
    {
        "title": "Beautiful Red Wedding Dress Transformation | Stunning Bridal Dress Reel",
        "channel": "Rupsi Ram Goyal",
        "url": "https://www.youtube.com/watch?v=AQ7CbrwOUIo",
        "niche": "Transformation Reveal (Bridal/Fashion)",
        "views": "17,940,147",
        "views_num": 17940147,
        "subscribers": 46800,
        "score": "383.3x subs",
        "pattern": "A single, cinematic, professionally-produced reveal frame (not a raw before/after) — the transformation genre's high-production end, where the visual alone is aspirational enough to justify the click.",
        "trigger": "Aspirational visual reward (an already-stunning image, no need to imagine the outcome) + the wedding/bridal setting's inherent emotional and romantic weight + confetti/motion adding a celebratory, climactic feel.",
        "thumbnail": "A woman in a dramatic oversized red ballgown mid-twirl with a partner, confetti falling around them, professional studio lighting and backdrop, a cinematic, celebratory composition.",
        "formula": "\"[Aspirational Descriptor] [Event Type] Transformation | Stunning [Category] Reel\"",
        "why": "This is the high-production-value end of the transformation genre — the thumbnail doesn't need a before/after contrast at all when the \"after\" alone is cinematic enough to be aspirational on its own.",
        "translation": "Reframe \"a stunning bridal transformation reveal\" as \"a stunning moment of genuine connection\" — same high-production, single-cinematic-frame approach, applied to a real social/romantic moment instead of a styling reveal.",
        "ca_title": "The Moment She Said Yes | Stunning First Date Reel",
        "ca_thumbnail": "Creator and a woman together in a beautifully lit, elevated real-world setting, both radiating genuine warmth, professional-feeling lighting and composition, a cinematic, celebratory feel.",
        "notes": "Proof that at the high-production end of this format, the thumbnail doesn't need an explicit before/after — a sufficiently aspirational single frame carries the whole hook.",
        "status": "Not Adapted",
    },
    {
        "title": "The Evolution of Women's Fashion in New York",
        "channel": "VGraphs",
        "url": "https://www.youtube.com/watch?v=iatLQuhwLq0",
        "niche": "Historical Documentary/Fashion Evolution",
        "views": "9,801,733",
        "views_num": 9801733,
        "subscribers": 257000,
        "score": "59.3x channel avg",
        "pattern": "A stylized period recreation with an on-screen year stamp, using historical curiosity rather than a personal story to drive the transformation-genre hook.",
        "trigger": "Curiosity about how things looked/were done in the past + the specificity of an exact year stamp making each scene feel like a real historical document rather than a vague montage + high production value (period-accurate styling, sets, lighting).",
        "thumbnail": "A woman in period-accurate 1940s attire walking a stylized vintage city street, a bold year stamp (\"1945\") in the corner, cinematic warm lighting, classic cars and storefronts in the background.",
        "formula": "\"The Evolution of [Category] in [Place]\"",
        "why": "The exact year stamp turns an abstract \"evolution\" concept into a series of concrete, collectible moments, and period-accurate production value makes each one feel like a real historical artifact rather than a generic reenactment.",
        "translation": "Reframe \"the evolution of fashion through the decades\" as \"the evolution of how to approach women through the decades\" — same year-stamped, period-styled documentary device, applied to social approach norms instead of clothing.",
        "ca_title": "The Evolution of Talking To Women (1950 to Today)",
        "ca_thumbnail": "A period-styled recreation of a man approaching a woman on a stylized vintage street, a bold year stamp in the corner, cinematic period-accurate lighting and styling.",
        "notes": "The exact-year-stamp device is a strong, specific alternative to vague \"back in the day\" framing — it works because specificity makes each scene feel real and documented.",
        "status": "Not Adapted",
    },
    {
        "title": "146 kg to 84 kg transformation",
        "channel": "vijayeshwari002",
        "url": "https://www.youtube.com/watch?v=GFjHhRZGrxc",
        "niche": "Weight Loss Transformation",
        "views": "5,909,364",
        "views_num": 5909364,
        "subscribers": 14600,
        "score": "404.8x subs",
        "pattern": "A minimalist, unproduced gym-progress shot with the entire hook carried by two exact numbers in the title — no dramatic language needed when the numbers alone are impressive.",
        "trigger": "Concrete, verifiable numbers doing all the persuasive work (146 to 84 is instantly, viscerally understandable as a huge change) + the authenticity of plain, unproduced gym footage.",
        "thumbnail": "A real gym setting, a man mid-exercise on equipment, other gym-goers visible in the background, on-screen text stating the exact before/after numbers, plain fluorescent gym lighting.",
        "formula": "\"[Exact Starting Number] to [Exact Ending Number] transformation\"",
        "why": "Two concrete, specific numbers require zero interpretation and instantly communicate the scale of change — no adjectives, no drama, just verifiable facts doing the entire persuasive job.",
        "translation": "Reframe \"146 kg to 84 kg\" as an exact-number transformation applied to a social metric instead of a physical one — e.g., a rejection count or a specific measurable change in outcomes.",
        "ca_title": "0 Numbers To 12 Numbers In 30 Days",
        "ca_thumbnail": "A real street setting, creator mid-approach, on-screen text stating the exact before/after numbers, plain unproduced daylight framing matching the authenticity of the original.",
        "notes": "Exact, verifiable before/after numbers are one of the cheapest and most transferable hook devices in this entire swipe file — no visual production needed at all.",
        "status": "Not Adapted",
    },
    {
        "title": "The Power Of Wigs 💀✨",
        "channel": "Cliphade FX",
        "url": "https://www.youtube.com/watch?v=AUOc_KiUDbw",
        "niche": "Style/Wig Transformation Reveal",
        "views": "12,182,038",
        "views_num": 12182038,
        "subscribers": 451000,
        "score": "27.0x subs",
        "pattern": "A minimalist, moody portrait thumbnail that shows almost nothing literal about the transformation itself, relying entirely on mysterious visual tone to earn the click.",
        "trigger": "Intrigue from visual ambiguity (the image promises nothing specific, so curiosity has to be resolved by watching) + a punchy, almost provocative title that reframes an ordinary prop as something with outsized influence.",
        "thumbnail": "A dark, moody side-profile silhouette portrait of a young man, minimal lighting, almost entirely in shadow, no literal preview of any transformation.",
        "formula": "\"The Power Of [Ordinary Object/Prop]\"",
        "why": "Naming an ordinary object as having \"power\" reframes it as consequential, and a deliberately moody, low-information thumbnail works because the mystery itself is the hook.",
        "translation": "Reframe \"the power of wigs\" as \"the power of confidence\" or a specific small change during an approach — same reframe-the-ordinary-as-powerful device, same moody minimal-information thumbnail.",
        "ca_title": "The Power Of Just Saying Hi",
        "ca_thumbnail": "A moody, minimal-light side-profile portrait of the creator, mostly in shadow, no literal preview of what happens next, matching the original's low-information mystery aesthetic.",
        "notes": "One of the lowest-information thumbnails in this file — worth testing since it relies entirely on title-driven curiosity rather than a literal visual promise.",
        "status": "Not Adapted",
    },
    {
        "title": "✨ Long Hair Transformation 😍 | Beautiful Hair Style Look #Shorts:",
        "channel": "Aria Collins",
        "url": "https://www.youtube.com/watch?v=BvwVQ5ObP6o",
        "niche": "Hair Transformation Reveal",
        "views": "8,645,764",
        "views_num": 8645764,
        "subscribers": 68500,
        "score": "126.2x subs",
        "pattern": "A real, candid mid-motion hair reveal (hands still in her hair, caught mid-gesture) rather than a static finished shot, giving the still image a sense of movement and immediacy.",
        "trigger": "Aspirational beauty payoff + the \"caught mid-motion\" framing making the reveal feel like a real, spontaneous moment rather than a posed after-photo.",
        "thumbnail": "A real woman outdoors mid hair-flip/reveal gesture, hands in her hair, casual candid daylight setting.",
        "formula": "\"✨ [Transformation Type] 😍 | [Aspirational Descriptor] Look #Shorts\"",
        "why": "Freezing the shot mid-gesture, not the fully resolved after-look, makes the still image feel alive and current, and the emoji-bracketed title format signals lighthearted, aspirational content at a glance.",
        "translation": "Reframe \"catching a hair reveal mid-motion\" as \"catching a woman's confidence shift mid-moment\" — same caught-in-motion, not-fully-resolved framing.",
        "ca_title": "✨ Watch Her Whole Energy Change 😍 | Real Reaction Look #Shorts",
        "ca_thumbnail": "A woman outdoors mid-gesture/mid-reaction, candid unposed body language, casual daylight setting, caught in the middle of a genuine shift in expression.",
        "notes": "The \"caught mid-motion, not fully resolved\" framing recurs across several transformation entries in this file — a reliably transferable device.",
        "status": "Not Adapted",
    },
    {
        "title": "Mua- @makeover_by_romamehta | Simple soft glam bridal makeup transformation #shorts #makeup #bridal",
        "channel": "BEAUTY MUST",
        "url": "https://www.youtube.com/watch?v=iJ67ZpGDYLs",
        "niche": "Bridal Makeup Transformation",
        "views": "3,491,871",
        "views_num": 3491871,
        "subscribers": 228000,
        "score": "15.3x subs",
        "pattern": "Uses a common, relatable inside-joke premise (a client's contradictory request) with the subject's own exaggerated, comedic real reaction as the entire visual hook, rather than a straight before/after.",
        "trigger": "Relatable humor (a well-known contradictory request many recognize) + the bride's genuine, funny facial reaction doing more work than a polished result shot would.",
        "thumbnail": "A bride in an ornate traditional outfit, exaggerated wide-eyed comedic reaction, on-screen caption \"When Bride Wants 'No Makeup' Makeup Look.\"",
        "formula": "\"When [Client/Subject] Wants [Contradictory/Relatable Request]\"",
        "why": "Naming a specific, widely-recognized contradictory request turns a niche professional in-joke into broadly relatable humor, and using the subject's real comedic reaction makes it feel authentic rather than purely promotional.",
        "translation": "Reframe \"when the bride wants a contradictory makeup request\" as \"when she asks for something that seems to contradict itself\" during an approach — same relatable-contradiction-plus-real-reaction device.",
        "ca_title": "When She Says 'I'm Not Interested' But Keeps Talking To You",
        "ca_thumbnail": "A woman with an exaggerated, comedic, genuine facial reaction as the focal point, casual real-world setting, on-screen caption naming the contradictory moment.",
        "notes": "Comedic, relatable contradiction premises travel well because the humor doesn't require any context beyond the caption itself.",
        "status": "Not Adapted",
    },
    {
        "title": "Amazing Fashion Transformation | Cute Skirt Outfit Makeover #Shorts",
        "channel": "Mila Trend",
        "url": "https://www.youtube.com/watch?v=mJuTKBIednk",
        "niche": "Fashion/Outfit Transformation",
        "views": "1,925,816",
        "views_num": 1925816,
        "subscribers": 3930,
        "score": "490.0x subs, 49.3x avg",
        "pattern": "A real, candid outdoor moment where the subject is caught mid-adjustment of her own outfit alongside a partner, giving the \"reveal\" a natural, in-the-moment feel rather than a staged studio shot.",
        "trigger": "Aspirational styling payoff + the candid outdoor, two-person framing suggesting a real lifestyle moment rather than a posed fashion ad.",
        "thumbnail": "A real outdoor path, a woman touching her skirt mid-adjustment beside a partner, casual daylight setting, unstaged framing.",
        "formula": "\"Amazing [Category] Transformation | [Specific Garment] Outfit Makeover #Shorts\"",
        "why": "Setting the transformation in a real outdoor, two-person scene makes an otherwise generic makeover format feel like a genuine lifestyle moment, and a 490x subscriber breakout on a tiny channel confirms the format travels without production value.",
        "translation": "Reframe \"an outdoor outfit makeover with a partner present\" as \"a real moment of a woman's confidence shifting while out with someone\" — same candid, real-world, two-person framing instead of a studio reveal.",
        "ca_title": "Watch Her Confidence Change During Our Walk Together",
        "ca_thumbnail": "A real outdoor setting, the creator and a woman together mid-moment, her caught in a candid, natural gesture, casual daylight framing matching the original's lifestyle feel.",
        "notes": "A 490x subscriber breakout on a channel with under 4,000 subscribers is strong proof the candid-outdoor-setting device works regardless of channel size or production value.",
        "status": "Not Adapted",
    },
    {
        "title": "The ultimate black dress transformation 👗 #outfitinspo #styling #shorts",
        "channel": "Tejsi sharma",
        "url": "https://www.youtube.com/watch?v=_p_JFRIzZS4",
        "niche": "Fashion/Outfit Transformation",
        "views": "923,840",
        "views_num": 923840,
        "subscribers": 1550,
        "score": "596.0x subs, 42.8x avg",
        "pattern": "A comedic \"trying on everything and rejecting most of it\" scene played for exaggerated chaos, with the \"ultimate\" result implied but not shown until the video plays.",
        "trigger": "Relatable humor (everyone recognizes the \"nothing to wear\" struggle) + the visual chaos of discarded options building anticipation for what she ultimately picks.",
        "thumbnail": "A woman in a room surrounded by discarded clothes flung about, comedic exaggerated toss/reject gesture, playful chaotic scene.",
        "formula": "\"The Ultimate [Garment] Transformation #outfitinspo #styling #shorts\"",
        "why": "Showing the messy, comedic rejection process, not the tidy final result, makes the video feel like an authentic real struggle rather than a polished styling ad, and \"ultimate\" promises a satisfying final payoff.",
        "translation": "Reframe \"trying on and rejecting outfit after outfit before the ultimate choice\" as \"trying different approaches before finding the one that actually works\" — same comedic-chaos-before-the-payoff structure.",
        "ca_title": "The Ultimate Opener Transformation (After Rejecting 10 Others)",
        "ca_thumbnail": "The creator in a real setting surrounded by \"discarded\" attempts (a visual metaphor for failed openers), comedic exaggerated gesture, playful chaotic scene matching the original's tone.",
        "notes": "A massive 596x subscriber breakout on a channel with under 2,000 subscribers shows the comedic-chaos-before-payoff structure travels well regardless of channel size.",
        "status": "Not Adapted",
    },
    {
        "title": "NEW DRESS DESIGN MOMENT BEFORE FASHION #fashion​ #trollface​ #transformation​ #edit​#shorts​ ..",
        "channel": "s4editzz",
        "url": "https://www.youtube.com/watch?v=yDeGgYQzDVM",
        "niche": "Fashion Design Transformation",
        "views": "9,912,935",
        "views_num": 9912935,
        "subscribers": 29400,
        "score": "337.2x subs",
        "pattern": "Shows the real, hands-on design/construction process, not just a finished garment, letting the craftsmanship itself be part of the appeal alongside the eventual reveal.",
        "trigger": "Behind-the-scenes curiosity (how does raw fabric become a finished design?) + the credibility of visible real skilled labor.",
        "thumbnail": "A real fashion design workshop scene, two people working with fabric on a mannequin, professional tailoring studio setting.",
        "formula": "\"NEW [Garment Type] DESIGN MOMENT BEFORE FASHION\"",
        "why": "Showing the \"moment before\" (the construction process) rather than only the finished piece adds a craftsmanship-appreciation layer on top of the standard transformation hook.",
        "translation": "Reframe \"the design process before the finished garment\" as \"the real effort before a genuine connection happens\" — same show-the-process-not-just-the-result device.",
        "ca_title": "The Moment Before Everything Changed Between Us",
        "ca_thumbnail": "A real, candid behind-the-scenes-style moment of the creator and a woman in the middle of a genuine interaction not yet resolved, natural lighting, unstaged framing.",
        "notes": "Showing real process/effort rather than only the polished result is a device that could differentiate this channel's content from purely reveal-only competitors.",
        "status": "Not Adapted",
    },
    {
        "title": "Cloth Transformation👗#viral #shorts #shortsfeed #ytshorts #asmr #art #clothing #trendingshorts #fyp",
        "channel": "Sujata's Art Verse",
        "url": "https://www.youtube.com/watch?v=IHZc9TU71zk",
        "niche": "Textile Art/Design Illustration",
        "views": "4,281,022",
        "views_num": 4281022,
        "subscribers": 5750,
        "score": "744.5x subs, 32.8x avg",
        "pattern": "A real hand-drawn fashion illustration process, an artist sketching a garment design, appealing to craftsmanship and artistic skill rather than a literal photographed transformation.",
        "trigger": "Satisfying process-completion curiosity (watching a design come together stroke by stroke) + admiration for visible hand-skill/craft.",
        "thumbnail": "A hand-drawn colored illustration of a fashion design in progress, artist's hand visible sketching, paper and colored markers.",
        "formula": "\"[Garment/Material] Transformation #art #shorts #asmr\"",
        "why": "The ASMR/process-satisfaction appeal of watching a skilled hand complete an illustration works independently of whether viewers have any interest in fashion specifically — it's satisfying to watch competence in action.",
        "translation": "Reframe \"watching a design come together stroke by stroke\" as \"watching a genuine connection develop moment by moment\" — same satisfying, real-time process-completion appeal.",
        "ca_title": "Watch This Come Together In Real Time #shorts #asmr",
        "ca_thumbnail": "A real, candid moment of the creator and a woman's interaction developing naturally, styled with a similar process-in-progress, satisfying-to-watch visual quality.",
        "notes": "A different sub-mechanic than the polished-reveal transformation entries elsewhere in this file — the appeal here is watching a real-time skilled process, not a before/after contrast.",
        "status": "Not Adapted",
    },
    {
        "title": "The Most IMPOSSIBLE Basketball Shot Ever! 😱🏀#shorts",
        "channel": "CineClue7",
        "url": "https://www.youtube.com/watch?v=8zQntH4oGcw",
        "niche": "Impossible Trick Shot",
        "views": "3,206,814",
        "views_num": 3206814,
        "subscribers": 38700,
        "score": "82.9x subs",
        "pattern": "A trick-shot video with unusually high cinematic production value (dramatic lighting, styled setting) rather than the raw, phone-camera aesthetic typical of the genre, elevating an \"impossible shot\" premise into something visually striking on its own.",
        "trigger": "Curiosity about how the specific \"impossible\" shot is pulled off + the elevated visual production making the moment feel more significant than a typical amateur trick-shot clip.",
        "thumbnail": "A stylized, cinematic shot of a young man in a vintage-style basketball uniform in an ornate indoor court setting, dramatic lighting.",
        "formula": "\"The Most IMPOSSIBLE [Sport] Shot Ever! #shorts\"",
        "why": "Superlative framing sets a high bar the video has to pay off, and unusually cinematic styling differentiates this from the sea of similar phone-camera trick-shot content.",
        "translation": "Reframe \"the most impossible basketball shot ever\" as \"the most impossible recovery from a rejection ever\" — same superlative-framing-plus-elevated-visual-style device.",
        "ca_title": "The Most Impossible Recovery From A Rejection Ever",
        "ca_thumbnail": "A cinematically lit, styled real-world shot of the creator mid-interaction with a woman, dramatic lighting elevating an otherwise ordinary moment, similar visual polish to the original.",
        "notes": "Cinematic styling on an otherwise-common content format (trick shots) is a differentiator worth testing on in-field footage too.",
        "status": "Not Adapted",
    },
    {
        "title": "Impossible soccer trick shots? ⚽🫣",
        "channel": "Garrett Yaps",
        "url": "https://www.youtube.com/watch?v=fWF0Z7UF718",
        "niche": "Impossible Trick Shot",
        "views": "507,561",
        "views_num": 507561,
        "subscribers": 20500,
        "score": "24.8x subs",
        "pattern": "A numbered, sequential build-up format (1, 2, 3, 4...) where each number raises the stakes of the trick before the final payoff, letting the thumbnail itself preview an escalating structure.",
        "trigger": "Anticipation of an escalating sequence (each step visibly harder or more impressive than the last) + the concrete numbered structure making the video's pacing legible before clicking.",
        "thumbnail": "A real outdoor bubble-soccer scene, a numbered overlay (1, 2, 3, 4) with checkmarks, captions \"goooaal\" and \"PEAK\" building through the sequence.",
        "formula": "\"Impossible [Sport] Trick Shots? [Numbered escalation captions]\"",
        "why": "A visible numbered sequence with checkmarks/outcomes previews the escalating structure of the video itself, which sets clear expectations and makes the payoff something viewers watch specifically for.",
        "translation": "Reframe \"an escalating sequence of impossible trick shots\" as \"an escalating sequence of increasingly bold approaches\" — same numbered-escalation-with-visible-outcomes structure.",
        "ca_title": "Rating My Boldest Approaches 1 to 4 (The Last One Is Wild)",
        "ca_thumbnail": "A real street scene with a numbered overlay (1, 2, 3, 4) and checkmark/reaction captions building anticipation toward a final standout moment, matching the original's escalating-sequence structure.",
        "notes": "The numbered-escalation thumbnail structure is a clean, reusable way to preview pacing and build anticipation toward a specific payoff moment.",
        "status": "Not Adapted",
    },
    {
        "title": "Extreme Survival Challenge! 🌲🔥",
        "channel": "Jani Ahmed",
        "url": "https://www.youtube.com/watch?v=5nzGbanRrNg",
        "niche": "Extreme Survival Documentary",
        "views": "5,808,388",
        "views_num": 5808388,
        "subscribers": 214000,
        "score": "27.1x subs, 29.2x avg",
        "pattern": "Real, hands-on rural/survival footage where competence with practical, unglamorous equipment itself is the appeal, rather than a dramatic wilderness backdrop.",
        "trigger": "Admiration for practical skill/self-sufficiency + the grounded, unpolished authenticity of real rural labor rather than a produced survival-show aesthetic.",
        "thumbnail": "A real rural/outdoor scene, a man working with heavy equipment/machinery, practical hands-on setting.",
        "formula": "\"Extreme [Challenge Type] Challenge! 🌲🔥\"",
        "why": "Grounding \"extreme\" in real, visibly unglamorous practical competence, not just scenic wilderness shots, gives the superlative claim credibility through visible hands-on skill.",
        "translation": "Reframe \"extreme survival/practical skill\" as \"extreme social/emotional resilience\" — same grounded-competence-under-real-pressure framing, applied to handling rejection.",
        "ca_title": "Extreme Rejection Challenge! (How Many Can I Handle In One Day)",
        "ca_thumbnail": "A real, grounded outdoor/street scene, the creator visibly working through a repeated real challenge, natural daylight, unpolished practical framing.",
        "notes": "Grounding an \"extreme\" claim in visible, unglamorous real competence, not just a dramatic backdrop, is what gives the superlative credibility.",
        "status": "Not Adapted",
    },
    {
        "title": "Baby Hears Mom's Voice For The First Time  Reaction..!😭❤️ | Emotional Reaction! #shorts #viral",
        "channel": "BlackRed Media",
        "url": "https://www.youtube.com/watch?v=MLQOn8lRMDc",
        "niche": "Real Milestone Reaction",
        "views": "24,926,695",
        "views_num": 24926695,
        "subscribers": 308000,
        "score": "80.9x subs",
        "pattern": "A real, medically significant \"first time\" milestone moment captured candidly, with the baby's genuine reaction as the emotional center and the parent's presence providing context without needing explanation.",
        "trigger": "Universal emotional resonance of a milestone \"first\" moment + the medical/clinical setting adding real-world credibility and stakes to the emotional payoff.",
        "thumbnail": "A real medical/audiology setting, a baby with a hearing device, mother emotional beside a doctor, close family moment.",
        "formula": "\"[Subject] [Experiences Milestone] For The First Time Reaction..! | Emotional Reaction! #shorts\"",
        "why": "A specific, medically real \"first\" makes the emotional stakes concrete and verifiable, and the clinical setting signals this is a genuine documented event, not a staged reaction video.",
        "translation": "Reframe \"a baby's first real reaction to a milestone\" as \"a woman's genuine first reaction to something unexpected during an approach\" — same specific-real-first-moment + genuine-reaction-as-focal-point device.",
        "ca_title": "Her Reaction The First Time She Actually Felt Heard | Emotional Reaction! #shorts",
        "ca_thumbnail": "A real, candid setting, a woman's genuine emotional reaction as the clear visual focal point, other people present but not the focus, natural indoor lighting matching the clinical authenticity of the original.",
        "notes": "An 80.9x subscriber breakout confirms real \"milestone first\" content travels far beyond whatever niche originally hosts it.",
        "status": "Not Adapted",
    },
    {
        "title": "Soldier's Surprise 🥰#surprise #soldier #love #family #fyp",
        "channel": "Yamsmz Wnzmz",
        "url": "https://www.youtube.com/watch?v=__V3Udn_N9s",
        "niche": "Military Homecoming Surprise",
        "views": "18,686,713",
        "views_num": 18686713,
        "subscribers": 114000,
        "score": "163.9x subs",
        "pattern": "A real military-reunion surprise staged in an ordinary, mundane setting (a classroom) rather than an airport or ceremony, making the contrast between routine and surprise sharper.",
        "trigger": "Anticipation of an emotional reunion + the mundane setting heightening the surprise, since nothing about the environment signals anything special is about to happen.",
        "thumbnail": "A real classroom setting, a soldier in uniform crouching to reunite with a child seated at a desk, other children visible.",
        "formula": "\"[Family Member]'s Surprise 🥰#surprise #[relation] #love #family #fyp\"",
        "why": "Staging the reveal in a completely ordinary, low-stakes-seeming environment makes the emotional payoff land harder by contrast, since the setting itself gives no warning.",
        "translation": "Reframe \"a reunion surprise in a mundane setting\" as \"an unexpected approach in a mundane, everyday setting\" — same ordinary-environment-heightens-the-surprise device.",
        "ca_title": "Her Surprise 🥰 #surprise #approach #love #fyp",
        "ca_thumbnail": "A real, ordinary everyday setting (classroom, office, store), the creator approaching a woman who has no visible warning anything is about to happen, natural indoor lighting matching the mundane-setting contrast.",
        "notes": "A 163.9x subscriber breakout confirms the \"reveal in a mundane setting\" contrast device travels well regardless of channel size.",
        "status": "Not Adapted",
    },
    {
        "title": "She thought she was fired, but unexpectedly received praise. #movie  #shorts",
        "channel": "cherish food",
        "url": "https://www.youtube.com/watch?v=CK-kqaOBeZs",
        "niche": "Workplace Reversal Reaction",
        "views": "1,824,053",
        "views_num": 1824053,
        "subscribers": 13400,
        "score": "136.1x subs",
        "pattern": "A workplace-anxiety premise (fear of being fired) subverted into an unexpected positive outcome, with the subject's raw, close-up facial reaction as the entire visual hook.",
        "trigger": "Relatable dread (the universal fear of being called in and fired) + the relief/surprise payoff of the anxiety being unfounded, made concrete by the subject's genuine facial reaction.",
        "thumbnail": "A real-looking office setting, a woman in professional attire, close-up genuine surprised expression.",
        "formula": "\"[Subject] Thought She Was [Feared Outcome], But Unexpectedly Received [Positive Outcome]. #shorts\"",
        "why": "Opening with a universally dreaded assumption sets up maximum anxiety before revealing the reverse outcome, and centering the thumbnail on her real facial reaction keeps the twist withheld until the video plays.",
        "translation": "Reframe \"she thought she was fired, but was praised instead\" as \"she thought this was a rejection, but it wasn't\" — same dreaded-assumption-subverted-to-positive-outcome structure.",
        "ca_title": "She Thought I Was About To Get Rejected, But Unexpectedly She Said Yes",
        "ca_thumbnail": "A real, close-up shot of a woman's genuine, anxious-turning-surprised facial expression as the clear focal point, natural indoor lighting, candid unposed framing.",
        "notes": "Leading with a universally dreaded assumption before subverting it is a strong, transferable anxiety-then-relief structure independent of the specific scenario.",
        "status": "Not Adapted",
    },
    {
        "title": "They Gave Him The Best Surprise Ever 🥹",
        "channel": "Daily Smiles",
        "url": "https://www.youtube.com/watch?v=LN84YyRlT8g",
        "niche": "Real Surprise Reaction",
        "views": "1,579,740",
        "views_num": 1579740,
        "subscribers": 72200,
        "score": "21.9x subs",
        "pattern": "A real, candid genuine reaction shot (open-mouthed shock) paired with a caption revealing a twist detail that recontextualizes something the subject didn't realize.",
        "trigger": "Curiosity about what exactly was true \"all along\" (an open loop resolved by the video) + the authenticity of the subject's real, unguarded shocked expression.",
        "thumbnail": "A real man in a cap, outdoor setting, genuine shocked open-mouthed reaction, caption \"ALL ALONG.\"",
        "formula": "\"They Gave [Subject] The Best Surprise Ever 🥹\"",
        "why": "The genuine, unguarded shock on the subject's face does the emotional selling, while \"all along\" keeps just enough withheld to require watching.",
        "translation": "Reframe \"a surprise revealing something true all along\" as \"a woman revealing something that recontextualizes the whole interaction\" — same genuine-shock-plus-withheld-detail structure.",
        "ca_title": "She Revealed Something That Changed Everything (She Knew All Along)",
        "ca_thumbnail": "A real, candid shot of the creator's genuine, unguarded shocked expression as the focal point, natural outdoor daylight, a caption hinting at a withheld detail.",
        "notes": "Genuine, unguarded facial reactions, not posed \"surprised faces,\" are what make this format's authenticity read as real rather than staged.",
        "status": "Not Adapted",
    },
    {
        "title": "Viral Video | Russian Couple Arrested After Surprise Proposal Atop Empire State Building Tower",
        "channel": "India Today",
        "url": "https://www.youtube.com/watch?v=96kCnXdQeQQ",
        "niche": "Real News Story/Proposal Twist",
        "views": "428,372",
        "views_num": 428372,
        "subscribers": 11200000,
        "score": "25.1x avg",
        "pattern": "A real news story where the proposal itself succeeded but led to an unexpected, headline-worthy consequence (arrest), subverting the usual \"proposal goes right\" narrative with a genuinely surprising real-world twist.",
        "trigger": "Novelty of an unexpected real-world consequence to an otherwise-familiar event type + the news-credibility of a real, reported incident rather than a produced content piece.",
        "thumbnail": "A real news photo, two people on an elevated platform/crane against a city skyline, dramatic red arrow/highlight.",
        "formula": "\"Viral Video | [Subject] [Unexpected Consequence] After [Familiar Event Type]\"",
        "why": "Familiar event types are usually safe, low-curiosity premises — attaching a genuinely unexpected consequence to one makes it newsworthy and shareable in a way a normal version wouldn't be.",
        "translation": "Reframe \"a proposal that led to an unexpected real consequence\" as \"an approach that led to an unexpected real consequence\" — same familiar-premise-plus-genuinely-surprising-twist device.",
        "ca_title": "Viral Video | Guy Gets Banned From The Mall After This Approach",
        "ca_thumbnail": "A real documentary-style photo, the creator and a woman in a public setting, a dramatic highlight/arrow drawing attention to the unexpected element, matching the news-photo authenticity of the original.",
        "notes": "This entry qualified purely via channel-average multiplier (25.1x) on a massive 11.2M-subscriber news channel — proof a single unusually newsworthy clip can outperform a channel's own normal baseline regardless of its size.",
        "status": "Not Adapted",
    },
    {
        "title": "Boy Singing in Female Voice 😳 Girl Reaction 🤯",
        "channel": "Kunal Bbx",
        "url": "https://www.youtube.com/watch?v=nqfkYpvZaJw",
        "niche": "Street Talent Reveal/Reaction",
        "views": "10,729,087",
        "views_num": 10729087,
        "subscribers": 134000,
        "score": "80.1x subs, 176.8x avg",
        "pattern": "A real street performance moment that subverts an assumed expectation (that she would be the one performing), with the caption naming the assumption explicitly before the video overturns it.",
        "trigger": "Curiosity from a stated, specific assumption (\"everyone expected her to sing\") that primes the viewer to want to see how it's subverted + the authenticity of a real, candid group setting.",
        "thumbnail": "A real street/rooftop scene, two men and a woman, one man singing/performing, caption \"Everyone was expecting her to sing,\" informal outdoor gathering.",
        "formula": "\"[Subject] [Unexpected Skill] 😳 [Observer] Reaction 🤯\"",
        "why": "Naming the expected outcome explicitly in the caption, then subverting it, gives the viewer a specific mental prediction to have proven wrong, which is a stronger hook than a vague tease.",
        "translation": "Reframe \"everyone expected her to sing, but he did instead\" as \"everyone expected her to reject him, but she didn't\" — same stated-expectation-then-subverted structure.",
        "ca_title": "Everyone Expected Her To Say No 😳 Her Reaction 🤯",
        "ca_thumbnail": "A real street/outdoor scene, the creator and a woman with others present, her genuine reaction as the clear focal point, candid unposed group framing matching the original.",
        "notes": "Naming the specific expected outcome in the caption before subverting it is a stronger, more concrete curiosity device than a vague tease.",
        "status": "Not Adapted",
    },
    {
        "title": "MS Dhoni Supported A Rejected Kid 🥺🔥 Pure Goosebumps #shorts #msdhoni",
        "channel": "Kings edisz",
        "url": "https://www.youtube.com/watch?v=5BbTzfRodwg",
        "niche": "Real Photo/Status-Elevates-Rejected-Person",
        "views": "13,345,228",
        "views_num": 13345228,
        "subscribers": 177000,
        "score": "75.4x subs",
        "pattern": "A real, single photo capturing a respected public figure offering support to someone who'd been rejected/overlooked, with the title naming both the celebrity's status and the kid's rejected status to maximize the contrast.",
        "trigger": "Vicarious warmth from watching someone respected and high-status choose to support someone low-status/rejected + the authority-borrowing effect of a real, recognizable public figure's endorsement.",
        "thumbnail": "A real, color-graded photo of an athlete in sportswear alongside a child on a sports field, warm nostalgic tone.",
        "formula": "\"[Respected Public Figure] Supported A Rejected [Person] 🥹🔥 Pure Goosebumps #shorts\"",
        "why": "Pairing a high-status real figure with an explicitly \"rejected\" subject maximizes the emotional contrast, and \"Pure Goosebumps\" sets an emotional expectation the real photo has to deliver on.",
        "translation": "Reframe \"a respected figure supporting someone rejected\" as \"someone respected choosing to give a rejected person a real chance\" — same high-status-figure-elevates-the-rejected-person structure.",
        "ca_title": "She Was The Only One Who Didn't Walk Away After I Got Rejected 🥹🔥 Pure Goosebumps",
        "ca_thumbnail": "A real, warm-toned candid photo of the creator alongside a woman in a supportive moment, natural setting, nostalgic warm color grade matching the original's emotional tone.",
        "notes": "Naming both the high-status supporter AND the rejected status of the recipient explicitly in the title is what maximizes the contrast — omitting either half would weaken the hook.",
        "status": "Not Adapted",
    },
    {
        "title": "Military sister surprises brother at graduation 😭🎓",
        "channel": "Wholesmanship",
        "url": "https://www.youtube.com/watch?v=1rxO9WV3Z3s",
        "niche": "Military Homecoming Surprise",
        "views": "937,345",
        "views_num": 937345,
        "subscribers": 3810,
        "score": "246.0x subs",
        "pattern": "Real graduation-ceremony footage combined with a military-service context, and a specific familial relationship (sister, not generic \"family\") grounding the reunion in a distinct real dynamic.",
        "trigger": "Compounded emotional payoff (milestone event + military service context) + the specificity of the sibling relationship making the reunion feel like a distinct, real story.",
        "thumbnail": "A real outdoor graduation ceremony, uniformed figures marching, family visible reacting.",
        "formula": "\"[Specific Family Member] Surprises [Sibling] at [Milestone Event] 😭🎓\"",
        "why": "Naming the specific familial relationship gives the reunion a distinct emotional flavor beyond the generic \"soldier comes home\" template.",
        "translation": "Reframe \"a sister surprising her brother at graduation\" as \"someone specific and unexpected showing up at a guy's own milestone moment\" — same specific-relationship + milestone-event compounding.",
        "ca_title": "She Showed Up At My Graduation And I Had No Idea 😭🎓",
        "ca_thumbnail": "A real graduation/milestone-event setting, a woman approaching the creator mid-ceremony, other attendees visible, natural daylight event lighting.",
        "notes": "Naming the specific relationship, not a generic \"family member,\" is a small but real differentiator across the many reunion-format entries in this file.",
        "status": "Not Adapted",
    },
    {
        "title": "Soldier's homecoming surprise goes completely wrong 💔#shorts #emotional #reality",
        "channel": "Nati-c",
        "url": "https://www.youtube.com/watch?v=YQ-f1f28Qak",
        "niche": "Military Homecoming Subversion",
        "views": "927,887",
        "views_num": 927887,
        "subscribers": 1570,
        "score": "591.0x subs",
        "pattern": "Subverts the entire genre's usual happy-ending expectation, explicitly promising the reunion \"goes completely wrong,\" with a single quiet word doing more emotional work than a dramatic caption would.",
        "trigger": "Genre-subversion curiosity (every other reunion video in this format promises joy; this one promises the opposite) + the emotional restraint of a single quiet word creating more unease than an explanatory caption would.",
        "thumbnail": "A real, dim indoor scene, a soldier on crutches, a woman in a red dress reacting, small caption \"sorry.\"",
        "formula": "\"[Event Type] Surprise Goes Completely Wrong 💔#shorts #emotional #reality\"",
        "why": "After dozens of nearly identical \"happy reunion\" videos flood this format, explicitly promising the opposite outcome stands out purely through contrast, and understatement reads as more emotionally real than an explained catastrophe.",
        "translation": "Reframe \"a reunion surprise that goes wrong\" as \"an approach that goes somewhere completely unexpected, for better or worse\" — same genre-subversion + quiet-understated-caption device.",
        "ca_title": "I Tried To Surprise Her... It Went Completely Wrong",
        "ca_thumbnail": "A real, dim intimate setting, the creator and a woman with a subdued, ambiguous emotional tone, a single quiet caption word, muted lighting matching the original's restraint.",
        "notes": "In a swipe file with many \"happy reunion\" entries, this is the one deliberate genre-subversion — worth testing precisely because it stands out from the pattern rather than repeating it.",
        "status": "Not Adapted",
    },
    {
        "title": "\"Their reaction when their soldier comes home\"#soldier#reunion#homecoming#surprise#emotional",
        "channel": "mr UNKNOWN",
        "url": "https://www.youtube.com/watch?v=OIqyPMKDTF8",
        "niche": "Military Homecoming Surprise (Public)",
        "views": "2,205,539",
        "views_num": 2205539,
        "subscribers": 6830,
        "score": "322.9x subs, 40.5x avg",
        "pattern": "A real, candid public reunion captured in a busy, populated real-world location, not a private home, with the crowd itself adding scale and authenticity to the moment.",
        "trigger": "Amplified emotional payoff from a public setting (strangers witnessing and reacting too) + the authenticity of unstaged, busy real-world footage.",
        "thumbnail": "A real airport/public arrival scene, a soldier in uniform among a crowd, family reacting.",
        "formula": "\"Their reaction when their [Family Member] comes home\"#[relation]#reunion#homecoming#surprise#emotional",
        "why": "Setting the reunion in a public, populated space adds a layer of communal witnessing to the emotional payoff, and framing the title as a direct quote makes it read as an authentic, in-the-moment observation.",
        "translation": "Reframe \"a public reunion witnessed by a crowd\" as \"an approach that plays out in a busy public setting with onlookers reacting too\" — same public-witnessed-moment amplification device.",
        "ca_title": "Their Reaction When They Saw What Happened Next #approach #reaction #emotional",
        "ca_thumbnail": "A real, busy public setting, the creator and a woman in the foreground, other people visible genuinely reacting in the background, natural daylight matching the original's candid public-scene authenticity.",
        "notes": "A rare triple-signal outlier (2.2M views + 322.9x subs + 40.5x avg) — one of the strongest confirmations in this batch that the public-witnessed-moment device travels regardless of channel size.",
        "status": "Not Adapted",
    },
    {
        "title": "Soldier's Surprise 🥰#surprise #soldier #love #family #fyp",
        "channel": "Deborah Mitchell",
        "url": "https://www.youtube.com/watch?v=3JozAhdGdlc",
        "niche": "Military Homecoming Surprise (Errand)",
        "views": "1,956,528",
        "views_num": 1956528,
        "subscribers": 164000,
        "score": "11.9x subs",
        "pattern": "A real reunion staged in an unremarkable everyday errand setting (a mall), reinforcing the \"surprise in a mundane moment\" device seen elsewhere in this file.",
        "trigger": "Same mundane-setting-heightens-the-surprise effect + the relatable, everyday nature of the location making the moment feel like it could happen to anyone, anywhere.",
        "thumbnail": "A real indoor mall/store setting, a soldier and family embracing near shopping bags.",
        "formula": "\"[Family Member]'s Surprise 🥰#surprise #[relation] #love #family #fyp\"",
        "why": "A completely unremarkable errand-running setting gives zero visual warning that anything special is about to happen, which sharpens the emotional contrast when the reveal lands.",
        "translation": "Reframe \"a reunion surprise during an ordinary errand\" as \"an unexpected approach during someone's completely ordinary day\" — same everyday-setting contrast device.",
        "ca_title": "I Approached Her While She Was Just Running Errands 🥰 #fyp",
        "ca_thumbnail": "A real, unremarkable everyday setting (store, mall), the creator and a woman mid-interaction, natural indoor lighting, candid unposed framing matching the mundane-setting contrast.",
        "notes": "A second independent example of the \"everyday errand setting\" reunion device, alongside Yamsmz Wnzmz's classroom entry — repetition across independent channels reinforces it's a real, repeatable mechanic.",
        "status": "Not Adapted",
    },
    {
        "title": "She THOUGHT she could hide it from him 💔",
        "channel": "UnmaskedCheaters",
        "url": "https://www.youtube.com/watch?v=8b2_b6tuM88",
        "niche": "Real Confrontation/Reveal",
        "views": "406,472",
        "views_num": 406472,
        "subscribers": 9560,
        "score": "42.5x subs",
        "pattern": "A real, candid confrontation moment captured in an ordinary domestic setting, with the title stating the subject's failed assumption to frame the entire video as a reveal of hidden truth.",
        "trigger": "Moral curiosity about deception being uncovered + the voyeuristic pull of a real, raw, unscripted-looking confrontation moment.",
        "thumbnail": "A real candid kitchen scene, two people embracing/confronting, a third figure's hand visible reaching in from the frame edge.",
        "formula": "\"[Subject] THOUGHT [She/He] Could Hide It From [Him/Her] 💔\"",
        "why": "Stating the subject's false assumption directly in the title frames the entire video as a specific reveal-of-truth payoff, which is a stronger and more specific hook than a vague tease.",
        "translation": "Reframe \"she thought she could hide the truth from him\" as \"she thought her disinterest was hiding something else,\" kept light rather than accusatory — same stated-false-assumption-then-revealed structure.",
        "ca_title": "She Thought Her 'I'm Not Interested' Was Hiding Something Else 💔",
        "ca_thumbnail": "A real, candid moment of the creator and a woman mid-interaction in an ordinary real-world setting, a genuine, unguarded expression as the focal point, natural lighting matching the original's raw authenticity.",
        "notes": "Stating the subject's specific false assumption directly in the title, rather than a vague tease, is a stronger and more repeatable hook structure.",
        "status": "Not Adapted",
    },
    {
        "title": "Military Dad Surprises Family at 30,000 Feet #shorts #heartwarming",
        "channel": "Crafts Valley Stories",
        "url": "https://www.youtube.com/watch?v=dxxXFJxrpcA",
        "niche": "Military Homecoming Surprise (Unusual Location)",
        "views": "1,205,838",
        "views_num": 1205838,
        "subscribers": 98900,
        "score": "12.2x subs",
        "pattern": "A real reunion staged in an unusually specific, hard-to-replicate real setting (mid-flight, at a stated altitude), with the specificity of the location itself becoming part of the hook.",
        "trigger": "Novelty of an unusual, specific real setting + the compounded stakes of a confined public space where everyone present becomes part of the moment.",
        "thumbnail": "A real airplane cabin interior, a flight attendant, uniformed soldier, mother holding a baby, other passengers visible.",
        "formula": "\"[Family Member] Surprises Family at [Specific Real Location/Number] #shorts #heartwarming\"",
        "why": "Naming an unusually specific real setting makes the premise feel more remarkable and concrete than a generic reunion location would.",
        "translation": "Reframe \"a reunion at 30,000 feet\" as \"an approach in an unusually specific, hard-to-replicate real setting\" — same specific-unusual-location-as-hook device.",
        "ca_title": "I Approached Her At 30,000 Feet #shorts #heartwarming",
        "ca_thumbnail": "A real, unusual specific setting (an airplane cabin, elevator, or similarly confined public space), the creator and a woman as the clear focal point, other real people visible in the background, natural setting lighting.",
        "notes": "An unusually specific real location, not a generic setting, is a cheap way to make an otherwise-common reunion format feel distinct.",
        "status": "Not Adapted",
    },
    {
        "title": "N'Golo Kanté | Football Greatest Underdog 🥺🏆  #soccer #shorts",
        "channel": "PitchFile",
        "url": "https://www.youtube.com/watch?v=pvRV1cYHdMk",
        "niche": "Real Photo/Underdog Story",
        "views": "306,774",
        "views_num": 306774,
        "subscribers": 580,
        "score": "528.9x subs",
        "pattern": "A real athlete's well-documented underdog story reduced to a single real photo with a bold highlight arrow, letting a widely-recognized name and face carry the entire premise without narration.",
        "trigger": "Vicarious inspiration from a real, verifiable underdog success story + the authority-borrowing effect of using a real, recognizable name rather than an anonymous subject.",
        "thumbnail": "A real athlete photo, a dramatic red arrow/highlight pointing at him mid-celebration.",
        "formula": "\"[Real Recognizable Name] | [Category] Greatest Underdog 🥺🏆 #shorts\"",
        "why": "Naming a real, widely-recognized person directly lends instant credibility and borrowed emotional investment, since viewers already have context for who this is and why an underdog framing is meaningful.",
        "translation": "Reframe \"a real athlete's underdog story\" as \"a guy's own real underdog story with women/dating\" — same real-name-credibility device, applied to a personal story instead of a public figure's.",
        "ca_title": "My Own Story | Dating's Greatest Underdog 🥺🏆",
        "ca_thumbnail": "A real photo of the creator with a bold highlight arrow drawing attention to a specific detail, matching the original's simple real-photo-plus-highlight structure.",
        "notes": "A massive 528.9x subscriber breakout on a channel with under 600 subscribers is strong proof a single well-chosen real photo, with almost no production, can travel enormously far.",
        "status": "Not Adapted",
    },
    {
        "title": "A Heartwarming & Funny Military Homecoming Surprise ❤️👧 \"That's Not My Daddy!\" Emotional Reunion",
        "channel": "Little joy kids",
        "url": "https://www.youtube.com/watch?v=3-X_f8O4tuU",
        "niche": "Military Homecoming Surprise (Child POV)",
        "views": "610,897",
        "views_num": 610897,
        "subscribers": 11300,
        "score": "54.1x subs",
        "pattern": "A real reunion moment with a child as the small, vulnerable visual focal point surrounded by a formal, imposing military formation, maximizing visual contrast between innocence and formality.",
        "trigger": "Emotional contrast (a small child dwarfed by a formal military formation) + the quoted line creating a specific, funny-then-touching emotional beat.",
        "thumbnail": "A real outdoor military ceremony, a child standing amid rows of uniformed soldiers.",
        "formula": "\"A Heartwarming & Funny [Event Type] Surprise ❤️👧 \"[Quoted Line]\" Emotional Reunion\"",
        "why": "Combining \"heartwarming\" and \"funny\" in the same title primes a more complex emotional expectation than a purely sentimental one, and quoting a specific real line gives a concrete, curiosity-driving preview of the moment's actual content.",
        "translation": "Reframe \"a child's funny-then-touching military reunion moment\" as \"a specific, funny-then-touching real quoted moment during an approach\" — same combined humor-plus-heart + quoted-real-line device.",
        "ca_title": "A Funny & Heartwarming Approach Story ❤️ \"Wait, You're Actually Talking To Me?\"",
        "ca_thumbnail": "A real street or public setting, the creator and a woman mid-genuine-reaction, a quoted caption line capturing the specific real moment, natural daylight matching the original's warm tone.",
        "notes": "Combining \"funny\" and \"heartwarming\" in the same title, rather than picking one emotional lane, sets up a more layered, specific expectation than a purely sentimental framing would.",
        "status": "Not Adapted",
    },
    {
        "title": "Soldier Came To Surprise His Sister!!",
        "channel": "Jorge Far",
        "url": "https://www.youtube.com/watch?v=oziVUJ7CJQU",
        "niche": "Military Homecoming Surprise (Close-Up)",
        "views": "449,333",
        "views_num": 449333,
        "subscribers": 32600,
        "score": "13.8x subs",
        "pattern": "A real, tightly-framed close-up embrace, not a wide establishing shot, making the moment feel intimate and immediate rather than observed from a distance.",
        "trigger": "Emotional immediacy from the tight, close framing (the viewer feels inside the embrace, not watching it from afar) + the specific sibling relationship named directly in the title.",
        "thumbnail": "A real, intimate, dim close-up embrace between a soldier and a sibling.",
        "formula": "\"[Family Member] Came To Surprise His/Her [Specific Relation]!!\"",
        "why": "A tight close-up crop creates a more intimate, immediate emotional read than a wide shot, and naming the specific relationship directly keeps the premise concrete rather than generic.",
        "translation": "Reframe \"a tight, intimate close-up reunion embrace\" as \"a tight, intimate close-up moment of genuine connection during an approach\" — same close-crop-intimacy device.",
        "ca_title": "I Came Back To Surprise Her!!",
        "ca_thumbnail": "A real, tightly-framed close-up embrace or intimate moment between the creator and a woman, dim natural lighting, intimate crop matching the original's immediacy.",
        "notes": "The tight, close-up crop, versus a wide establishing shot, is a simple framing choice that meaningfully changes how intimate a reunion-format thumbnail feels.",
        "status": "Not Adapted",
    },
]


def main() -> None:
    client = build_google_sheets_client()
    if not client:
        print("No Google Sheets output was created.")
        return

    if GOOGLE_SPREADSHEET_ID:
        spreadsheet = client.open_by_key(GOOGLE_SPREADSHEET_ID)
    else:
        spreadsheet = client.create("YouTube Outlier Tracker")

    try:
        worksheet = spreadsheet.worksheet(SHEET_NAME)
    except gspread.exceptions.WorksheetNotFound:
        # Renamed from "General Shorts Models" — reuse and rename that tab in place
        # instead of leaving it as an orphaned stale duplicate.
        try:
            worksheet = spreadsheet.worksheet("General Shorts Models")
            worksheet.update_title(SHEET_NAME)
        except gspread.exceptions.WorksheetNotFound:
            worksheet = spreadsheet.add_worksheet(title=SHEET_NAME, rows=100, cols=20)

    worksheet.clear()
    worksheet.append_row(HEADERS)

    values = [
        [
            row["title"], row["channel"], row["url"], row["niche"], row["views"], row["subscribers"], row["score"],
            row["pattern"], row["trigger"], row["thumbnail"], row["formula"], row["why"],
            row["translation"], row["ca_title"], row["ca_thumbnail"], row["notes"], row["status"],
        ]
        for row in SWIPE_FILE
    ]
    worksheet.append_rows(values, value_input_option="USER_ENTERED")
    worksheet.set_basic_filter()

    print(f"Wrote {len(SWIPE_FILE)} swipe file entries to {spreadsheet.url} ({SHEET_NAME})")


if __name__ == "__main__":
    main()
