# Executed by ideas_source.py after ideas_revisions.py (shares its namespace: IDEAS, PARKED, prompt).
# Grows each category to 10 ideas and ranks them. Rank criteria, in order: (1) how many niche outliers
# prove the format and how large their audience is, (2) how much of the video the creator can shoot
# with footage or a setup they already have, (3) brand fit and honesty risk.

NEW2 = [
    # ---------------- DAYGAME ----------------
    dict(
        id="dg-handicap", category="daygame",
        title="I Cold Approached Women Using Only Questions (Difficulty: Hard)",
        pattern="Cold approach challenge with a handicap rule",
        strength="proven",
        evidence=[("Difficulty: Impossible", "Dylan McKnight: 142x channel average, 4.3M views. A cold approach challenge with a difficulty tag."),
                  ("cold approach' 100 girls", "Dylan McKnight again: 80x, 2.4M views, same challenge frame."),
                  ("Impress a Random Beautiful Girl with a Twist", "Zaid Chulbula: 22x, 667K views. A rule or twist makes an approach a story.")],
        why="The three strongest daygame outliers in the tracker all wrap an approach in a challenge with a rule. A handicap turns ordinary approaches into a video with stakes and a clear thing to watch for.",
        hook="Today I can only ask questions. No compliments, no statements. Let's see how far that gets me.",
        thumbnail="A woman answering a question with a curious, amused expression, medium-wide, street setting, creator half in frame.",
        prompt=prompt("curious and amused while answering a question", "sunny downtown sidewalk, passersby softly blurred"),
        footage="A normal approach day, played under one rule. Keep the rule visible on screen so viewers can see it working.",
        risk="Pick a rule you can actually keep for the whole video. Don't stage the results.",
    ),
    dict(
        id="dg-60-min-uncut", category="daygame",
        title="A Realistic 60 Minutes Of Approaching Women (Uncut Infield)",
        pattern="'Realistic' time-box, uncut",
        strength="adapted",
        evidence=[("A Realistic 60 Minutes", "Alex Leon: 31x channel average on an 18.9K channel, the origin of the format."),
                  ("A Realistic 74 Minutes", "Coach Kyle runs the same format on a 581K channel."),
                  ("A Realistic Approach at a Deli", "Coach Kyle again, a single-approach version of the same 'realistic' promise.")],
        why="Two different creators, including a large one, run this exact promise. 'Realistic' plus 'uncut' tells viewers they will see the misses, which is what builds trust for a long infield video.",
        hook="One hour, one street, no cuts. You'll see every miss too.",
        thumbnail="A woman smiling warmly mid-conversation on a sunny street, medium-wide, a small timer badge added later.",
        prompt=prompt("smiling warmly and relaxed, mid-conversation", "sunny pedestrian street with cafes, soft daylight"),
        footage="One continuous hour of approaches with mic audio, misses included.",
        risk="A crowded format, so your city, your numbers and honest misses are what make it yours.",
    ),
    dict(
        id="dg-compilation", category="daygame",
        title="20 Approach Reactions Caught On Camera | Best Of The Week #1",
        pattern="Weekly numbered reaction compilation series",
        strength="adapted",
        evidence=[("25 Approach Reactions Caught On Camera", "Cross-niche compilation series (735K views), adapted to approach reactions in the swipe file."),
                  ("Infield Compilation #52", "Brad Dating Lifestyle: numbered infield compilations are already a running niche series.")],
        why="A weekly numbered series trains viewers to come back, and it is assembled from footage you already have. Lowest production cost on this list.",
        hook="Twenty approaches from this week, and every reaction, in order.",
        thumbnail="A woman's candid mid-reaction on the street (surprised smile), medium-wide, a small '#1' badge added later.",
        prompt=prompt("caught mid-reaction with a surprised, delighted smile", "busy daytime street"),
        footage="A week of approach clips from your library, each cut at her first clear reaction.",
        risk="Cut every clip at her first response. Never add words for her.",
    ),
    dict(
        id="dg-new-city", category="daygame",
        title="Approaching Women In A City I've Never Been To (Day 1, Uncut)",
        pattern="New city or country infield series",
        strength="adapted",
        evidence=[("Infield Compilation #52", "Brad Dating Lifestyle: 12x, city-by-city infield series."),
                  ("Cold Approaching in India is Easy", "Dating With Nishant: 18x, a place-based approach video."),
                  ("Toronto for 12 Hours", "Chris Goldy: a city named in the title.")],
        why="A new place gives an ordinary approach a novelty hook and makes a natural series (Day 1, Day 2). Several niche creators use a place name as the hook.",
        hook="I landed an hour ago and I don't know a single street. Let's see what this city is like.",
        thumbnail="A woman laughing on an unfamiliar street with landmark architecture behind her, medium-wide, creator half in frame.",
        prompt=prompt("laughing warmly, clearly enjoying the conversation", "historic city street with distinctive architecture, late afternoon light"),
        footage="A trip. Film arrival, the first approaches and one honest takeaway.",
        risk="Needs travel. Be respectful of local norms and never generalize about a country's women.",
    ),
    dict(
        id="dg-eye-contact", category="daygame",
        title="I Held Eye Contact With 10 Strangers For 60 Seconds (Here's What Happened)",
        pattern="Eye contact challenge",
        strength="adapted",
        evidence=[("Last To Break Eye Contact", "Cross-niche eye contact challenge, 5.0M views (adapted to a cold approach in the swipe file)."),
                  ("How Women React Around Attractive Men", "Zoomology: 12x, 367K views. Viewers like watching real reactions to presence.")],
        why="A single clear rule, a visible clock, and a genuine human reaction on every clip. It is flirty without needing a pickup line.",
        hook="Ten strangers, sixty seconds of eye contact each. I'm not saying a word until someone speaks first.",
        thumbnail="A woman holding a steady gaze toward the camera with a hint of a smile, medium-wide, soft daylight.",
        prompt=prompt("holding a steady gaze with a hint of a smile", "quiet park path, dappled daylight"),
        footage="Ten consented volunteers or willing strangers, each with a 60 second timer on screen.",
        risk="Get clear consent from each person and stop if anyone is uncomfortable. Evidence is cross-niche.",
    ),
    dict(
        id="dg-almost-failed", category="daygame",
        title="6 Times An Approach Almost Went Wrong (And How I Recovered)",
        pattern="Numbered near-miss stories",
        strength="adapted",
        evidence=[("6 Times My Approach Almost Completely Failed", "Cross-niche: a 6-times near-miss compilation at 1.8M views, adapted in the swipe file."),
                  ("you'll cringe", "Jak Piggott: 27x, 800K views. A self-testing approach video with a 'cringe' promise.")],
        why="Showing recovery from awkward moments is both entertaining and useful, and it builds trust that a highlight reel never does.",
        hook="Six times an approach started to go wrong. I'll show you exactly how I got it back.",
        thumbnail="A woman with a small, amused smile just after an awkward moment, medium-wide, creator visibly relaxed.",
        prompt=prompt("giving a small amused smile after an awkward beat", "quiet street corner with soft daylight"),
        footage="Six clips where the start was awkward and the interaction recovered. Cut at her first clear response.",
        risk="Only use real recoveries. Do not dramatize.",
    ),
    # ---------------- BARGAME ----------------
    dict(
        id="bg-30-days", category="bargame",
        title="I Tried Cold Approaching Women At Bars For 30 Days (Here's What Changed)",
        pattern="Time-boxed cold approach challenge",
        strength="adapted",
        evidence=[("Difficulty: Impossible", "Dylan McKnight: 142x, 4.3M views. Not bar-specific, the format is proven for cold approach in general."),
                  ("cold approach' 100 girls", "Dylan McKnight: 80x, 2.4M views."),
                  ("Cold Approaching Older Women In Public", "Cold Approach Rizz: 48x, 1.1M views, an 'I Tried ... Here's What Happened' title."),
                  ("you'll cringe", "Jak Piggott: 27x, 800K views.")],
        why="The 'I tried ... for N days' frame is the most successful cold approach format in the tracker. Nobody has applied it to bars with real footage.",
        hook="Thirty days of bars. I'm keeping notes on what actually changes.",
        thumbnail="A woman at a bar looking over with an easy smile, warm bar light, medium-wide, creator entering the frame.",
        prompt=prompt("looking over with an easy, friendly smile", "stylish bar with warm pendant lights and blurred patrons"),
        footage="Your weekly bar footage across a month, plus a short reflection on what changed.",
        risk="The proof is for cold approach generally, not bars specifically. Say so if asked.",
    ),
    dict(
        id="bg-breakdown", category="bargame",
        title="Watching My Own Bar Approaches Back: What Worked And What Didn't",
        pattern="Infield breakdown",
        strength="proven",
        evidence=[("Hot Seat at Home By Tyler RSD", "Xlabel: 38x. A nightgame infield review."),
                  ("How To Create Sexual Tension During Cold Approach", "ApproachCraft: 30x. An infield breakdown of real footage."),
                  ("Owen Cook Nightgame Infield Breakdown", "Insane Flirt: 15x. Nightgame breakdowns keep resurfacing.")],
        why="Breakdowns turn footage you already shot into teaching content, and 'what didn't work' makes it credible. Cheap to make and easy to split into shorts.",
        hook="I'm going to pause my own footage and tell you exactly what I'd do differently.",
        thumbnail="A woman mid-reaction at a bar, paused-frame feel, medium-wide, creator visibly reviewing at the edge.",
        prompt=prompt("mid-reaction with a warm smile, frozen-frame feel", "bar with warm lighting and blurred patrons"),
        footage="Three or four bar approaches with clean audio, each paused at two or three key moments.",
        risk="Narration must describe reactions directionally, never quote her.",
    ),
    dict(
        id="bg-truth-drink", category="bargame",
        title="Truth Or Drink With A Stranger At The Bar",
        pattern="Game-show question format",
        strength="adapted",
        evidence=[("Truth or Drink", "Cut: graded 'truth or drink' questions with real people at 1.7M views."),
                  ("Omegle Dating Show", "Family Friendly: 107x, 3.2M views. Dating-as-game structure.")],
        why="A game gives two strangers something to do together and hands the edit a built-in structure. It works as a flirty first interaction.",
        hook="I'm going to play Truth Or Drink with someone I just met. You'll see how it goes.",
        thumbnail="A woman laughing over a drink at a bar counter, medium-wide, creator across from her at the edge of frame.",
        prompt=prompt("laughing while holding a drink, clearly having fun", "cozy bar counter with warm pendant lights"),
        footage="A consenting stranger, a short list of questions, and mic audio on both of you.",
        risk="Needs her consent to film and to the game. Keep questions light and let her skip any.",
    ),
    dict(
        id="bg-ask-bar", category="bargame",
        title="I Asked Women At The Bar What Makes A Good Opener",
        pattern="Ask strangers for advice",
        strength="adapted",
        evidence=[("100 Married Couples for Dating Advice", "Sprouht: 33x, asking real people for dating advice."),
                  ("Asking Strangers How to Approach a Girl", "Benjamin Seda: 10x, 299K views on a 1.5M channel.")],
        why="Real women answering on camera puts a woman front and center, and it is direct research for your own openers.",
        hook="I'm asking women at the bar what actually makes a good opener, and I'll use what they tell me.",
        thumbnail="A woman answering thoughtfully at a bar, medium-wide, creator listening at the edge.",
        prompt=prompt("thoughtful and amused, mid-answer to a question", "bar with warm lighting and blurred patrons"),
        footage="Short consented interviews at the bar, then one or two openers that use the advice.",
        risk="Use only what each woman actually says. Get consent from every person on camera.",
    ),
    dict(
        id="bg-went-wrong", category="bargame",
        title="5 Bar Approaches That Went Wrong (And How I'd Fix Them)",
        pattern="Numbered near-miss stories",
        strength="adapted",
        evidence=[("6 Times My Approach Almost Completely Failed", "Cross-niche near-miss compilation, 1.8M views."),
                  ("A New Level of Rejection", "Smosh Pit: a 3.1M-view rejection-stories format."),
                  ("you'll cringe", "Jak Piggott: 27x, 800K views.")],
        why="It shows you learning in public, which makes viewers trust your advice more. Uses misses you already have from weekly bar footage.",
        hook="Five approaches at the bar that didn't land. Here is what I'd do differently.",
        thumbnail="A woman with a polite, slightly awkward smile at a bar, medium-wide, creator visibly reflecting.",
        prompt=prompt("giving a polite, slightly awkward smile", "bar with warm lighting and blurred patrons"),
        footage="Five clear misses from weekly bar footage, each cut at her first response.",
        risk="Never mock the woman or dramatize her reaction. The lesson is about your approach.",
    ),
    dict(
        id="bg-tier-bars", category="bargame",
        title="Ranking Every Type Of Bar To Meet Women (TIER LIST)",
        pattern="(TIER LIST) title format",
        strength="adapted",
        evidence=[("Signs She Likes You (TIER LIST)", "The only tier-list title in the tracked niche data, at a low score."),
                  ("How to Go to a Bar Alone", "Gentlemen's Collective: 50x, 1.3M views. Bar topic demand is real.")],
        why="Bar demand is proven and tier lists are live in dating on YouTube, but the format is untested in your tracker, so it ranks last.",
        hook="Dive bar, cocktail lounge, rooftop, sports bar. I ranked them by what actually happened to me.",
        thumbnail="A woman's reaction in a stylish bar with a tier badge added on top, medium-wide.",
        prompt=prompt("smiling, engaged in conversation", "stylish rooftop bar at dusk with warm lights"),
        footage="One representative approach per bar type, over several weeks.",
        risk="Rank on real outcomes, not reputation. Tier-list format is unproven in the tracked niche.",
    ),
    # ---------------- VIDEO CHAT E-DATES ----------------
    dict(
        id="vc-country", category="video-chat-edates",
        title="E-Dating Women From 10 Different Countries In One Night",
        pattern="'Women from [country]' series",
        strength="proven",
        evidence=[("INDIAN GEN Z GIRLS", "justabhix: 129x, 479K views on a 3.7K channel."),
                  ("FOUND THE CUTEST INDIAN GIRL", "Its Kunal: 125x, 3.7M views."),
                  ("Finding love with russian girl", "adarshuc: 150x, 4.5M views."),
                  ("My  Wife From Pakistan", "Adrishya: 147x, 4.4M views.")],
        why="A place in the title is the most repeated hook across the video chat outliers, and it makes a natural series (the next ten countries).",
        hook="Ten e-dates tonight, ten different countries. I want to hear what each one is like.",
        thumbnail="A woman on a video call smiling warmly with a hint of a flag or landmark behind her, medium framing.",
        prompt=prompt("smiling warmly on a video call, seen on a laptop screen", "lamp-lit room, a small map or postcard visible behind the laptop"),
        footage="Ten e-dates with consent, PII and usernames blurred, a running list of countries on screen.",
        risk="Keep it curious and respectful, never stereotype a country. Source channels have large audiences in specific regions.",
    ),
    dict(
        id="vc-wingman", category="video-chat-edates",
        title="I Found My Best Friend A Date On Video Chat",
        pattern="Matchmaker / wingman challenge",
        strength="proven",
        evidence=[("FINDING LARRAY A MAN ON OMEGLE", "Quenlin Blackwell: 120x, 3.6M views."),
                  ("FIND SUNDAY A BOYFRIEND ON OMEGLE", "Kalogeras Sisters: 148x, 4.4M views.")],
        why="Two large channels ran the same matchmaker idea to millions of views. It gives the woman the spotlight and you a warm, funny host role.",
        hook="My best friend is single and picky. I'm going to find him a date in one night.",
        thumbnail="A woman on a video call laughing, seen over the shoulders of two men, medium framing.",
        prompt=prompt("laughing on a video call, seen over the shoulders of two men", "lamp-lit living room in the evening"),
        footage="A friend who agrees to be filmed, a set of e-dates, and permission from anyone shown.",
        risk="Needs a willing friend and consent from every woman on screen. Blur usernames and personal info.",
    ),
    dict(
        id="vc-hype", category="video-chat-edates",
        title="I Let My Friends Hype Me Up On Video Chat E-Dates",
        pattern="Hype-crew e-dates",
        strength="adapted",
        evidence=[("FOUND MY Love with 20 HYPEMAN", "adarshuc: 201x, 6.0M views."),
                  ("Girls Flirting", "Godl Highlights: 130x, 214K views. A fanbase or crew changes the dynamic.")],
        why="A hype crew adds comedy and gives you reactions to react to, and the format has multi-million-view precedent.",
        hook="Three friends. One rule: they can only hype me up. Let's see what happens.",
        thumbnail="A woman on a video call laughing at something off-screen, medium framing, warm lamp light.",
        prompt=prompt("laughing at something off-screen on a video call", "lamp-lit room, a laptop and a couch with friends softly blurred"),
        footage="Friends who agree to be filmed and a set of consenting e-dates.",
        risk="Both large source channels are outside your audience's region, so this is adapted. Keep the tone warm.",
    ),
    dict(
        id="vc-rate-me", category="video-chat-edates",
        title="10 Strangers Rate My First Impression On Video Chat (Brutally Honest)",
        pattern="'What strangers say about me' feedback",
        strength="adapted",
        evidence=[("What OmeTV Strangers Say Behind My Back", "Tristan Clausen: 122x, 3.6M views."),
                  ("Guessing People's Names 1-20", "Peter Prankster: 132x, 4.0M views, a visible score and feedback.")],
        why="Honest feedback from strangers is inherently watchable, and it makes the women the experts, so they are the focus.",
        hook="I'm asking ten strangers to rate my first impression, and I'm not allowed to argue.",
        thumbnail="A woman on a video call giving a thoughtful, honest look, medium framing.",
        prompt=prompt("thoughtful and honest expression on a video call, seen on a laptop screen", "lamp-lit room in the evening"),
        footage="Ten consenting strangers, each asked the same three questions, PII blurred.",
        risk="Keep it kind even when the feedback is blunt. Never edit her words to change the meaning.",
    ),
    dict(
        id="vc-truth-drink", category="video-chat-edates",
        title="Truth Or Drink E-Date: 10 Questions With A Stranger",
        pattern="Game-show question format",
        strength="adapted",
        evidence=[("Truth or Drink", "Cut: graded questions between real people, 1.7M views."),
                  ("Omegle Dating Show", "Family Friendly: 107x, 3.2M views.")],
        why="A question game gives the e-date structure and quick emotional beats without needing a plot.",
        hook="Ten questions, one stranger, and she can skip any of them.",
        thumbnail="A woman on a video call mid-laugh with a drink in hand, medium framing.",
        prompt=prompt("laughing with a drink in hand on a video call, seen on a laptop screen", "cozy lamp-lit room"),
        footage="A consenting stranger and a printed list of ten questions. PII blurred.",
        risk="Let her skip any question, and keep the tone warm.",
    ),
    # ---------------- EXPLAINER ----------------
    dict(
        id="ex-robert-greene", category="explainer",
        title="I Tested Robert Greene's Rules Of Seduction In Real Conversations",
        pattern="Famous framework tested on real people",
        strength="proven",
        evidence=[("How To Master Seduction", "Raj Shamani: 163x, 4.4M views. Robert Greene in the title."),
                  ("The Psychology of Making Them Crave You", "Silent Mastery: 183x, 318K views on a small channel."),
                  ("Master the Art of Seduction By Robert Greene", "Vaibhav Kadnar: 26x. Book review demand.")],
        why="Robert Greene titles show up repeatedly among the strongest explainer outliers, and nobody tests the ideas on camera. That is the gap.",
        hook="Robert Greene wrote the book on seduction. I tried the rules on real conversations to see which ones hold up.",
        thumbnail="A woman at a cafe table with a paperback book beside her, listening with a curious smile, medium-wide.",
        prompt=prompt("listening with a curious smile, a paperback book on the table beside her", "cafe table by the window in soft light"),
        footage="A few real conversations where one specific rule was applied, described directionally.",
        risk="Present the rules as ideas to test, not as manipulation. Keep it about honest connection.",
    ),
    dict(
        id="ex-unforgettable", category="explainer",
        title="How To Be Unforgettable In A 5 Minute Conversation (Real Examples)",
        pattern="Make an impression, taught with examples",
        strength="proven",
        evidence=[("How to Make Her WANT You", "Feminine Connection: 400x."),
                  ("3 Powerful Phrases That Trigger Instant Attraction", "The Relationship psychology: 116x."),
                  ("The Psychology of Making Them Crave You", "Silent Mastery: 183x.")],
        why="The 'make her want you' cluster holds three of the top outliers. This takes the same demand and teaches it as being memorable and genuine, not as pressure.",
        hook="Five minutes is enough to be remembered. Here's what I do and what it looks like.",
        thumbnail="A woman smiling with real interest mid-conversation, medium-wide, creator engaged.",
        prompt=prompt("smiling with real interest, leaning slightly in", "cafe patio in soft daylight"),
        footage="Five clips where a specific habit (a question, a callback, a pause) is visible.",
        risk="Do not frame it as making someone want you. It is about being interesting and kind.",
    ),
    dict(
        id="ex-attractive-signs", category="explainer",
        title="7 Signs You're More Attractive Than You Think (Real Reactions I've Filmed)",
        pattern="Numbered 'signs you are attractive'",
        strength="proven",
        evidence=[("Highly Attractive Man", "Elvzen: 57x, 156K views on a 2.8K channel."),
                  ("Very Attractive", "ThinkDot: 43x, 277K views."),
                  ("More Attractive Than You Think", "Stoic & Soul: 17x, 128K views.")],
        why="A separate demand cluster from 'signs she likes you': viewers want reassurance about themselves. Real reactions from your footage back it up.",
        hook="Seven signs that people find you more attractive than you think, and I have the footage to show it.",
        thumbnail="A woman giving a warm, appreciative smile toward the camera, medium-wide, number badge added later.",
        prompt=prompt("giving a warm, appreciative smile toward the camera", "sunny cafe patio"),
        footage="Seven short clips of genuine positive reactions to you, described directionally.",
        risk="Keep it about confidence and reading reactions, not about looks.",
    ),
    dict(
        id="ex-flirt-no-cheese", category="explainer",
        title="How To Flirt Without Being Cheesy (5 Moves I Filmed Live)",
        pattern="How-to flirt with live proof",
        strength="proven",
        evidence=[("How to Unlock Your Flirting Superpowers", "TED: 57x, 1.7M views."),
                  ("Ways To Flirt Subtly", "Psych2Go: 33x, 981K views."),
                  ("How to Flirt SO Good", "Benjamin Seda: 20x, 591K views.")],
        why="Flirting how-tos have proven demand across three large channels, and all three are talking heads or animation. Live footage is the difference.",
        hook="Flirting doesn't need a line. Here are five moves, and I'll show each one working.",
        thumbnail="A woman smiling and holding eye contact mid-flirt, medium-wide, creator engaged.",
        prompt=prompt("smiling and holding eye contact, relaxed and playful", "sunny street cafe"),
        footage="Five clips, each isolating one move.",
        risk="Broad topic with strong competition. Keep claims modest.",
    ),
    dict(
        id="ex-second-date", category="explainer",
        title="5 Signs She Wants To See You Again (Filmed After Real First Conversations)",
        pattern="Numbered signs, later-stage angle",
        strength="proven",
        evidence=[("6 Signs a Woman Secretly Wants Intimacy With You", "FREJA INSPIRATION: 58x, 141K views."),
                  ("9 Signs She Already Likes You", "Attraction Explained: 54x."),
                  ("If She Shows These 5 Signs", "Liz Rose Psychology: 54x.")],
        why="Same demand cluster as 'signs she likes you', aimed at the next step. Gives you a second signs video that doesn't repeat the first.",
        hook="You had a good conversation. Here are five signs she'd like to see you again.",
        thumbnail="A woman smiling as she says goodbye, warm body language, medium-wide, evening light.",
        prompt=prompt("smiling warmly as she says goodbye, relaxed body language", "quiet street at golden hour"),
        footage="Five clips near the end of real conversations where one sign is visible.",
        risk="Signals are probabilities, not guarantees. Say so.",
    ),
]

# Existing ideas whose evidence or label changed while ranking.
OVERRIDES2 = {
    "dg-100-women": dict(
        evidence=[("cold approach' 100 girls", "Dylan McKnight: 80x, 2.4M views. The 100-approach challenge."),
                  ("12 Hours Straight", "Chris Goldy: a time-boxed marathon."),
                  ("I cold approached 150 women", "Benjamin Seda: 150 approaches on a 1.5M channel.")],
    ),
    "ex-talk-anyone": dict(strength="adapted"),
}

# (rank, why it sits here). One rank per category, 1 = most potential.
RANK = {
    # daygame
    "dg-handicap": (1, "Three niche outliers above 20x, including 142x and 4.3M views, all built on a challenge with a rule."),
    "dg-100-women": (2, "The 100-approach challenge already reached 2.4M views in this niche, and it is one day of shooting."),
    "dg-60-min-uncut": (3, "Proven twice (a small channel at 31x, a large one repeating it), and a single continuous shoot."),
    "dg-ask-women": (4, "Puts real women on camera by design and has a second half, but the evidence is adjacent formats."),
    "dg-intimidating": (5, "A running niche series (Part 2 and Part 3 exist) but at modest scores."),
    "dg-compilation": (6, "Cheapest to make from existing footage, but the evidence is a cross-niche compilation format."),
    "dg-places-tier": (7, "Already scripted, but tier lists are unproven in your tracked niche."),
    "dg-new-city": (8, "Good series hook but needs travel, and the proof is scattered place-based videos."),
    "dg-almost-failed": (9, "Trust-building, and the closest niche source (27x) outscores the eye-contact idea's source."),
    "dg-eye-contact": (10, "Fresh and flirty, but the evidence is cross-niche (5.0M views elsewhere) and needs consented participants, and its closest niche source is weaker (12x)."),
    # bargame
    "bg-alone": (1, "The only bar topic with real outlier proof (two videos near 50x, 1.3M views) and a clear gap: real footage."),
    "bg-breakdown": (2, "Proven twice by independent channels (38x, 30x), both directly bar/nightgame, and needs no new shoot, just footage you already have."),
    "bg-30-days": (3, "The strongest cold approach format in the tracker (142x, 4.3M views), but proven for cold approach generally, not bars specifically, and needs a full month's shoot."),
    "bg-line-reaction": (4, "One clip is one episode, and reaction-first titles are the strongest cross-niche pattern."),
    "bg-10-lines": (5, "Ranking gives each clip a reason to exist, and reuses weekly footage, evidence is borrowed from the general cold-approach format."),
    "bg-truth-drink": (6, "Strong game format at 1.7M views cross-niche, but needs a consenting stranger."),
    "bg-pov": (7, "One bar POV outlier from a 750-subscriber channel backs it."),
    "bg-ask-bar": (8, "Adjacent advice format, needs several consented interviews."),
    "bg-went-wrong": (9, "Trust-building but adapted from a cross-niche format."),
    "bg-tier-bars": (10, "Tier lists are unproven in your tracker."),
    # video chat e-dates
    "vc-country": (1, "Four separate outliers at 125x to 150x (up to 4.5M views) use a place as the hook."),
    "vc-real-life": (2, "Multiple channels at 164x to 224x built on the online to real life arc, but it needs consent."),
    "vc-10-edates": (3, "Three outliers at 107x to 172x run the multi-date format, and it is a single night's shoot."),
    "vc-wingman": (4, "Two large channels at 120x and 148x ran this to millions of views."),
    "vc-hype": (5, "201x on the source, but that channel's audience differs from yours."),
    "vc-tier": (6, "Uses your existing library with no new shoot, but the tier-list format is unproven."),
    "vc-rate-me": (7, "122x on the closest source, adapted to a feedback frame."),
    "vc-truth-drink": (8, "Game structure with cross-niche proof, needs a consenting stranger."),
    "vc-guess": (9, "One outlier from a large channel."),
    "vc-3am": (10, "Late-night framing has proof at 115x but lands on chaotic content that conflicts with your brand."),
    # explainer
    "ex-7-signs": (1, "594x is the top score in the entire tracker, and the demand cluster is deep."),
    "ex-robert-greene": (2, "Three explainer outliers between 26x and 183x carry Robert Greene, and nobody tests it on camera."),
    "ex-unforgettable": (3, "Three of the top outliers (400x, 183x, 116x) sit in this cluster, reframed as being memorable."),
    "ex-not-interested": (4, "400x on the source video, taken the respectful way."),
    "ex-attractive-signs": (5, "A separate demand cluster (57x, 43x) with real proof from your footage."),
    "ex-flirt-no-cheese": (6, "Three large channels at 57x, 33x and 20x cover flirting how-tos."),
    "ex-how-women-flirt": (7, "Three channels at 19x to 33x, moderate scores."),
    "ex-second-date": (8, "Strong cluster (54x to 58x) but overlaps with the 7 signs video."),
    "ex-talk-anyone": (9, "Broad how-to with heavy competition and one strong source."),
    "ex-10-seconds": (10, "Proven at 30x on a small channel, teaching format you can shoot."),
}

IDEAS += NEW2
for _i in IDEAS:
    _i.update(OVERRIDES2.get(_i["id"], {}))
    _r = RANK[_i["id"]]
    _i["rank"], _i["rank_reason"] = _r
    _i["potential"] = "Top pick" if _r[0] <= 3 else "Strong" if _r[0] <= 6 else "Worth testing"
_ids = {i["id"] for i in IDEAS}
_missing = set(RANK) - _ids
assert not _missing, f"ranked ids without an idea: {_missing}"

FORMAT_TAGS = {
    "dg-handicap": ["challenge", "game", "i-tried"], "dg-100-women": ["challenge", "trust-tag", "i-tried"],
    "dg-60-min-uncut": ["challenge", "trust-tag"], "dg-ask-women": ["i-tried"], "dg-intimidating": ["series", "place"],
    "dg-compilation": ["series", "reaction"], "dg-places-tier": ["tier", "place"], "dg-new-city": ["place", "series"],
    "dg-eye-contact": ["game", "challenge", "reaction"], "dg-almost-failed": ["number-list", "reaction"],
    "bg-alone": ["how-to", "place"], "bg-30-days": ["challenge", "i-tried"], "bg-line-reaction": ["reaction", "i-tried"],
    "bg-10-lines": ["i-tried", "challenge", "tier"], "bg-breakdown": ["breakdown"], "bg-truth-drink": ["game"],
    "bg-pov": ["pov", "trust-tag", "place"], "bg-ask-bar": ["i-tried"], "bg-went-wrong": ["number-list"],
    "bg-tier-bars": ["tier", "place"],
    "vc-country": ["place", "challenge", "series"], "vc-real-life": ["online-to-real", "i-tried"],
    "vc-10-edates": ["challenge", "online-to-real", "tier"], "vc-wingman": ["online-to-real"], "vc-hype": ["game"],
    "vc-tier": ["tier"], "vc-rate-me": ["i-tried", "challenge"], "vc-truth-drink": ["game"], "vc-guess": ["game", "challenge"],
    "vc-3am": ["series", "challenge"],
    "ex-7-signs": ["number-list", "signs", "hidden"], "ex-robert-greene": ["psychology", "i-tried"],
    "ex-unforgettable": ["how-to", "psychology"], "ex-not-interested": ["how-to"], "ex-attractive-signs": ["number-list", "signs"],
    "ex-flirt-no-cheese": ["how-to", "number-list"], "ex-how-women-flirt": ["psychology"], "ex-second-date": ["number-list", "signs"],
    "ex-talk-anyone": ["how-to"], "ex-10-seconds": ["how-to", "breakdown"],
}
for _i in IDEAS:
    _i["formats"] = FORMAT_TAGS[_i["id"]]

IDEAS.sort(key=lambda i: (i["category"], i["rank"]))

PARKED = [
    {"title": "I Ran Into A Girl I Approached A Year Ago. Her Reaction", "why": "Needs a real, consented reunion, and the evidence is a cross-niche reunion format. Revisit only if it happens naturally."},
    {"title": "Speed E-Dating 10 Strangers", "why": "Same video as the 10 e-dates idea, repackaged."},
    {"title": "12 Subtle Body Language Signs / 3 Signs She Wants You To Talk To Her", "why": "Same topic as the 7 signs idea. Test one signs video first."},
    {"title": "A Body Language Expert Reviews My Real Approaches", "why": "Needs a guest. Evidence is one expert-interview outlier at 16x."},
    {"title": "What Hundreds Of Approaches Taught Me About Attraction", "why": "A lessons-learned summary. Evidence is adjacent (dating advice summaries) and it works better after the first few videos exist."},
]
