"""One-off writer for the "General Outlier Models" tab: a curated swipe file of viral
YouTube packaging (title + thumbnail psychology) from outside the cold-approach niche,
each translated into a cold-approach-ready title and thumbnail concept.

Entries here must be real, statistically verified outliers found by
general_outlier_finder.py (run via GitHub Actions, since computing view/subscriber/
channel-average multipliers needs live channel stats from the YouTube API) — and must
be genuine RELATIVE outliers, not just big channels doing normal big-channel numbers.
Concretely: a video only qualifies on raw views (1M+) if the channel has under 100K
subscribers, where 1M+ views is itself remarkable. Channels at or above 100K subscribers
must qualify via a relative signal instead — 5x+ subscriber breakout or 20x+ channel-
average breakout — since 1M views means nothing for a channel whose average video
already clears that. (An earlier batch of entries let big channels like MrBeast qualify
purely on absolute views; those got removed once this rule was tightened.)

That finder script only surfaces candidates; picking which ones cleanly translate into
a cold-approach idea — both the title AND the thumbnail concept — and writing the
analysis below is a manual step. Cold-approach thumbnail concepts should put a woman
front and center as the visual star (per the channel's packaging convention), regardless
of whether the original video's thumbnail did. Entries must also be in English — a
language filter (is_english_title in youtube_outliers.py) now screens the finder's
output, but it only catches non-Latin scripts, not other Latin-script languages, so
still verify by eye. This file is not a live API pull itself — run it manually whenever
new entries are added.
"""
import os

import gspread

from youtube_outliers import GOOGLE_SPREADSHEET_ID, build_google_sheets_client

SHEET_NAME = os.getenv("GENERAL_OUTLIER_SHEET_NAME", "General Outlier Models")

HEADERS = [
    "Original Video Title",
    "Original Channel",
    "Video URL",
    "Original Niche",
    "Views",
    "Subscribers",
    "Outlier Score",
    "Core Packaging Pattern",
    "Psychological Trigger",
    "Thumbnail Breakdown",
    "Title Formula",
    "Why It Worked",
    "Cold Approach Translation (Concept)",
    "Cold Approach Title",
    "Cold Approach Thumbnail Concept",
    "Notes",
    "Status",
]

SWIPE_FILE = [
    {
        "title": "Alone, Broke, Over 60… I Sold Everything to Start Over (My Real Story)",
        "channel": "Offended Outcast",
        "url": "https://www.youtube.com/watch?v=RndUKvYAhHs",
        "niche": "Personal Reinvention/Redemption Documentary (Vlog)",
        "views": "3,005,620 (channel averages ~26,046/video — a verified 115.4x outlier, published 2026-04-11, within the last 90 days)",
        "views_num": 3005620,
        "subscribers": None,
        "score": "115.4x channel avg",
        "pattern": "A raw, unstyled \"diary\" visual (a plain selfie shot, zero graphics/text) paired with a title that does 100% of the emotional heavy lifting — the plainness of the image itself signals \"this is real, not produced,\" building trust and curiosity at once.",
        "trigger": "Vulnerability/empathy (a man exposing failure at a life stage where reinvention feels impossible) + authenticity signal (unpolished visual = \"this can't be staged\") + a stacked-adjective vulnerability hit (\"alone,\" \"broke,\" \"over 60\" — each independently painful, devastating together).",
        "thumbnail": "A plain, close-cropped selfie-style shot of a man in his 60s (ballcap, glasses, plaid flannel shirt) standing alone on a rural dirt road surrounded by forest, looking directly into the camera with a tired, resigned expression, natural overcast daylight, muted green/earth tones, zero text overlay, zero graphic design — the total absence of typical thumbnail polish is itself the authenticity signal.",
        "formula": "[Stacked vulnerable adjectives, comma-separated] + [age/life-stage marker] + \"… I \" + [drastic action taken] + \" (My Real Story)\"",
        "why": "Each word in the opening stack (\"Alone,\" \"Broke,\" \"Over 60\") is independently a strong emotional hook, and stacking three compounds the stakes before the sentence even finishes; \"My Real Story\" explicitly promises non-fiction, and the deliberately unpolished thumbnail backs that promise visually instead of contradicting it with slick production.",
        "translation": "Reframe the \"stacked vulnerable stats + drastic action + authenticity\" mechanic around social isolation instead of financial/life-stage failure — the same raw, unproduced visual style, the same title structure staking out real, specific vulnerability before revealing the turnaround.",
        "ca_title": "Shy, Friendless, 30 Years Old… I Walked Up To A Stranger To Change My Life (My Real Story)",
        "ca_thumbnail": "Plain, close-cropped selfie-style shot of the creator alone on an ordinary sidewalk or park path, looking directly into the camera with a tired, vulnerable expression (not smiling, not performing), natural daylight, muted/neutral colors, zero text overlay and zero graphic polish — the visual should look like a real diary entry, not a produced thumbnail, so the plainness itself signals honesty.",
        "notes": "Verified via general_outlier_finder.py: 115.4x the channel's own average views, published 2026-04-11 (within the 90-day window). A fundamentally different packaging style than flashy/high-production examples — no graphic design needed, low cost to produce, relies entirely on emotional authenticity. Worth testing as a low-effort, high-frequency format.",
        "status": "Not Adapted",
    },
    {
        "title": "They Convinced A Stranger He Was INVISIBLE",
        "channel": "MotivationSeedz",
        "url": "https://www.youtube.com/watch?v=-2_4Y4X0DhM",
        "niche": "Hidden-Camera Prank/Social Experiment",
        "views": "11,276,941 (98.2K subscribers — 114.8x its subscriber count in views, a genuine breakout for this small channel)",
        "views_num": 11276941,
        "subscribers": 98200,
        "score": "114.8x subs",
        "pattern": "Shows the actual trick mechanic mid-demonstration in the thumbnail (a specific action, captioned) rather than a generic \"prank face\" reaction shot, pre-selling the cleverness of the method itself.",
        "trigger": "Curiosity about a specific, nameable mechanic (\"how do you even convince someone of that?\") + small-channel-breakout energy — raw, unpolished footage reads as more real than a produced prank.",
        "thumbnail": "Two men outdoors in a park-like setting, one gesturing toward the other mid-explanation, bold caption text \"GRAB THE CAN\" pinned to the moment — a specific, concrete instruction caught on camera rather than an abstract reaction shot.",
        "formula": "\"They Convinced A Stranger He Was [Absurd/Specific Claim]\"",
        "why": "Naming the exact, absurd claim in the title creates a specific curiosity gap (\"how do you convince someone of THAT, specifically?\"), and showing the actual mechanic being demonstrated in the thumbnail proves there's a real, teachable method underneath the prank.",
        "translation": "Reframe \"convinced a stranger he was invisible\" as \"convinced a stranger of something specific and absurd about themselves/the situation\" as a way into a real conversation — same \"show the specific mechanic, not just a generic reaction\" thumbnail principle.",
        "ca_title": "I Convinced A Stranger She Already Knew Me From Somewhere",
        "ca_thumbnail": "Creator mid-gesture explaining something to a woman on a street, bold caption text pinned to the exact moment (e.g. \"SAY THIS FIRST\"), casual daylight outdoor setting, unpolished/candid framing rather than a posed reaction shot.",
        "notes": "Small-channel breakout (114.8x average) confirms this doesn't need production value — the specificity of the claim and showing the real mechanic did the work.",
        "status": "Not Adapted",
    },
    {
        "title": "Strangers Witness Bullying – Do They Step Up to Help? (Kindness Test) #kindness",
        "channel": "respect.w",
        "url": "https://www.youtube.com/watch?v=hwYfRcI9cDM",
        "niche": "Social Experiment/Kindness Test",
        "views": "4,471,297 (32.4K subscribers — 138x its subscriber count in views, a genuine breakout for a small channel)",
        "views_num": 4471297,
        "subscribers": 32400,
        "score": "138x subs",
        "pattern": "A plain genre-label (\"Social Experiment\") stamped directly on real, unstaged-looking street footage, with the entire premise framed as a moral test of onlookers rather than of the creator.",
        "trigger": "Moral curiosity (\"would people actually help, or just watch?\") + the viewer's own self-assessment (\"would I have stepped in?\") + the authenticity read of visibly candid, non-produced footage.",
        "thumbnail": "Two people on a street corner mid-interaction (one appears distressed, another moving toward them), several passersby visible in the background, bold yellow \"Social Experiment\" banner stamped across the top, muted overcast lighting, unpolished handheld framing.",
        "formula": "\"[Strangers/Subjects] + [Moral Test Scenario] – Do They [Verb]? (Kindness/Test Label)\"",
        "why": "Framing the video as a test of bystanders rather than a story about the creator makes every viewer implicitly grade themselves against the outcome, and the plain \"Social Experiment\" label functions as a genre-trust stamp the same way \"TRUE\" does for horror stories.",
        "translation": "Reframe \"do strangers step up to help a stranger in distress\" as \"do strangers react warmly or coldly to an approach\" — same plain genre-label + candid unstaged-street-footage formula, testing social warmth instead of moral courage.",
        "ca_title": "Strangers Watched Me Get Rejected - Here's What They Did Next (Social Experiment)",
        "ca_thumbnail": "Creator mid-conversation with a woman who's walking away, several passersby visible in the background clearly reacting/watching, bold yellow \"Social Experiment\" banner across the top, muted natural daylight, unpolished handheld framing to preserve the candid feel.",
        "notes": "The plain genre-label stamp (\"Social Experiment,\" like \"TRUE\" for horror) is a reusable trust device across many different specific premises.",
        "status": "Not Adapted",
    },
    {
        "title": "His Teammates Bullied Him So He joined Their Rivals For Revenge | Roger Guedes",
        "channel": "impetus",
        "url": "https://www.youtube.com/watch?v=ATMXOkCm2vE",
        "niche": "Sports Narrative/Underdog Revenge (narrated true-story edit)",
        "views": "8,590,220 (7,570 subscribers — 1,134.8x its subscriber count in views, an extreme breakout for a tiny channel)",
        "views_num": 8590220,
        "subscribers": 7570,
        "score": "1134.8x subs",
        "pattern": "A real athlete's documented career story is re-cut and re-captioned into a revenge-arc narrative, with a single emotionally-raw real photo doing all the thumbnail work.",
        "trigger": "Vicarious vindication (watching someone who was wronged \"win\" against the people who wronged them) + the authenticity of a real, unstaged emotional photo rather than a produced shot.",
        "thumbnail": "A real photo of a soccer player sitting on the grass, head down, clearly emotionally raw, a bold red arrow pointing at him, white caption text \"WAS CRYING\" stamped directly over the moment, muted natural stadium lighting.",
        "formula": "\"His [Group] [Wronged Him] So He [Took A Specific Retaliatory Action] For Revenge | [Real Name]\"",
        "why": "This channel didn't create original footage — it found a real, emotionally raw moment and wrapped a revenge narrative around it, proving a strong true-story arc plus one powerful authentic image can outperform original production entirely, even on a tiny channel with almost no baseline audience.",
        "translation": "Reframe \"athlete gets revenge on the team that wronged him\" as \"someone who got rejected/ignored comes back transformed and gets a completely different reaction\" — same real-raw-photo + retaliation-arc caption formula, applied to a real cold-approach moment instead of a repurposed sports photo.",
        "ca_title": "She Rejected Him In High School, So He Came Back Like This",
        "ca_thumbnail": "A real, candid photo of the creator looking visibly down/dejected in an earlier, less put-together state, a bold red arrow pointing at his own past self, white caption text \"GOT REJECTED\" stamped over the moment, muted natural lighting — sets up an implied before/after the video itself resolves.",
        "notes": "Proof a swipe-file entry doesn't need original high production — a real photo plus a sharp narrative caption is enough, especially valuable for a channel just starting out.",
        "status": "Not Adapted",
    },
    {
        "title": "How to Tell If Your Crush Likes You 🤫 (Psychologically Proven) #shorts #psychology",
        "channel": "Subconscious Code",
        "url": "https://www.youtube.com/watch?v=w1w-K7d45hA",
        "niche": "Relationship Psychology/Listicle",
        "views": "271,037 (3,120 subscribers — 86.9x its subscriber count in views, a genuine breakout for a tiny channel)",
        "views_num": 271037,
        "subscribers": 3120,
        "score": "86.9x subs",
        "pattern": "Animated, faceless characters illustrate a specific behavioral \"tell,\" paired with an authority-borrowing claim (\"Psychologically Proven\") that lends credibility without needing any real footage or a real face at all.",
        "trigger": "Practical, personally-applicable curiosity (\"does this apply to MY situation right now?\") + borrowed scientific authority + zero production barrier (fully animated, no filming required).",
        "thumbnail": "Simple 3D-animated characters — a blue figure and a red-haired figure — in a hallway-like setting, on-screen caption text \"or if she smiles\" as one item in an implied checklist, flat bright colors, minimal detail.",
        "formula": "\"How To Tell If [Relationship Signal] (Psychologically Proven)\"",
        "why": "\"Psychologically Proven\" borrows scientific authority to make a subjective claim feel objective and trustworthy, and the fully-animated, faceless format means the video can be produced with zero filming, camera-shyness, or location constraints at all.",
        "translation": "This is already squarely in the cold-approach/dating advice niche — the direct translation is a format lesson (animated, checklist-style, authority-claim) rather than a content reframe.",
        "ca_title": "How To Tell If She Wants You To Approach Her (Psychologically Proven)",
        "ca_thumbnail": "Simple animated characters in a public setting (café or street), on-screen caption text listing one specific signal (e.g. \"or if she glances back twice\"), flat bright colors, minimal detail, no real faces needed.",
        "notes": "A genuinely zero-cost format (fully animated, no filming) that could run as a low-effort, high-frequency companion series to in-field approach footage.",
        "status": "Not Adapted",
    },
    {
        "title": "Millionaire Ignores Man In Need Prank!",
        "channel": "Crime Catchers",
        "url": "https://www.youtube.com/watch?v=Crd2Qr1zSOM",
        "niche": "Status/Wealth-Disguise Social Test",
        "views": "11,510,047 (224K subscribers — 51.4x its subscriber count in views, a genuine breakout)",
        "views_num": 11510047,
        "subscribers": 224000,
        "score": "51.4x subs",
        "pattern": "A social status/wealth-disguise test captured candidly, where the caption spells out the subject's authentic in-the-moment reaction rather than describing the setup.",
        "trigger": "Curiosity about how people treat someone based on perceived status (would they help a \"millionaire\" who looks like they need help, or ignore someone who seems poor?) + the voyeuristic pull of a caught, unscripted reaction.",
        "thumbnail": "A man laughing genuinely inside an elevator, a small \"*LAUGHS*\" caption capturing his real-time reaction, casual candid framing.",
        "formula": "\"[Status Label] [Verb: Ignores/Helps] [Someone] In Need Prank!\"",
        "why": "Framing the test around a status label immediately raises a judgment question the viewer wants answered, and capturing a genuine, specific reaction (not a generic shocked face) makes the moment feel authentically unscripted.",
        "translation": "Reframe \"does a disguised millionaire get ignored\" as \"does she react differently to me depending on how I show up\" — same status-test mechanic, same real-reaction-as-caption device, aimed at social/attraction dynamics instead of wealth perception.",
        "ca_title": "I Approached The Same Girl Twice - Once Looking Rough, Once Looking Sharp",
        "ca_thumbnail": "A woman mid-reaction with a genuine, specific expression (visibly warmer and more interested) as the clear focal point of the frame, a small caption capturing her real reaction in words, candid unstaged framing, casual daylight street setting.",
        "notes": "Using the subject's own real, specific reaction as the caption (not a generic \"SHOCKED\") makes the moment feel authentic rather than staged.",
        "status": "Not Adapted",
    },
    {
        "title": "A Billionaire Watched His Son Beg Strangers for Shoes  Nobody Helped  Then She Appeared",
        "channel": "Afro Seoul — Cinematic Stories",
        "url": "https://www.youtube.com/watch?v=SHq7DfX38vM",
        "niche": "Narrated Moral Story/Social Class Drama",
        "views": "168,316 (4,470 subscribers — 37.7x its subscriber count in views, a genuine breakout for a tiny channel)",
        "views_num": 168316,
        "subscribers": 4470,
        "score": "37.7x subs",
        "pattern": "A staged, narrated moral vignette where a vulnerable child is ignored by everyone until one woman steps in — the thumbnail alone tells the entire emotional arc via a single cinematic image.",
        "trigger": "Moral tension (will anyone help?) + a cinematic, emotionally-loaded visual (a well-dressed woman kneeling to help a barefoot child) + the \"then she appeared\" framing promising a turnaround hero.",
        "thumbnail": "A woman in business attire kneeling on a wet nighttime city street, gently helping a barefoot child put on new shoes, dramatic neon-lit backdrop, cinematic lighting and color grade.",
        "formula": "\"[Powerful Observer] Watched [Vulnerable Person] [Ignored By Everyone]… Then [Hero] Appeared\"",
        "why": "The thumbnail is a complete emotional story in one frame — you don't need the title to understand the stakes — and \"then she appeared\" promises a resolution without revealing it.",
        "translation": "Reframe \"a stranger steps in to help a child when nobody else would\" as \"a woman responds warmly when a guy's approach is being coldly dismissed by everyone else\" — same single-frame emotional-arc thumbnail, same hero-appears structure.",
        "ca_title": "Every Girl Ignored Him… Then She Didn't",
        "ca_thumbnail": "A woman warmly engaging with the creator on a city street at night, other people visible walking past/ignoring him in the background, cinematic moody lighting, her posture and expression clearly the emotional turning point of the frame.",
        "notes": "A single, cinematic frame that tells the whole emotional arc without needing the title is a high-value, if production-intensive, device.",
        "status": "Not Adapted",
    },
    {
        "title": "If Your Crush Starts Flirting With You 🤫 #shorts #psychology",
        "channel": "Decoded Logic",
        "url": "https://www.youtube.com/watch?v=BCbKFnpwR_4",
        "niche": "Relationship Psychology/Listicle (Animated)",
        "views": "2,117,303 (110K subscribers — 19.2x its subscriber count in views, a genuine breakout)",
        "views_num": 2117303,
        "subscribers": 110000,
        "score": "19.2x subs",
        "pattern": "The same zero-filming animated checklist format as the Subconscious Code entry — a second, independent channel succeeding with it confirms it's a repeatable style, not a fluke.",
        "trigger": "Practical, personally-applicable curiosity + zero-friction animated production + borrowed authority via the \"psychology\" framing.",
        "thumbnail": "Simple 3D-animated characters — a red figure labeled \"Crush\" and a blue figure labeled \"You\" — in a hallway setting, \"flirting\" captioned near the interaction.",
        "formula": "\"If Your Crush Starts [Specific Behavior] #psychology\"",
        "why": "Same mechanism as the other animated example — no filming, no face required, a specific relatable behavioral cue as the hook.",
        "translation": "Already squarely in-niche — same format, direct lesson for a low-cost recurring companion series.",
        "ca_title": "If She Does This, She Wants You To Approach",
        "ca_thumbnail": "Simple animated characters in a public setting, on-screen caption naming one specific behavioral signal, flat bright colors, no real faces needed.",
        "notes": "Including a second example of this exact format alongside Subconscious Code's is deliberate — two independent channels succeeding with it is stronger evidence it's worth building a recurring series around.",
        "status": "Not Adapted",
    },
    {
        "title": "Asking strangers for gas in the hood #fypシ゚viral #360video #detroit #bikelife #socialexperiment",
        "channel": "MotorPsycho",
        "url": "https://www.youtube.com/watch?v=pEGdCxg37as",
        "niche": "Street Social Experiment",
        "views": "493,518 (51.6K subscribers — 9.6x its subscriber count in views, a genuine breakout)",
        "views_num": 493518,
        "subscribers": 51600,
        "score": "9.6x subs",
        "pattern": "A real, candid street interaction asking strangers for a small favor, filmed in a specific, characterful location that gives it grounded, unpolished authenticity.",
        "trigger": "Curiosity about how strangers respond to a small, specific ask + the specificity of the real location adding grounded authenticity + the voyeuristic pull of real, unscripted interactions.",
        "thumbnail": "A real street scene, a man in casual clothes handing over cash/items to another man, plain daylight urban backdrop, unproduced handheld framing.",
        "formula": "\"Asking Strangers For [Small Specific Favor] In [Specific Real Location]\"",
        "why": "Naming a specific, real location (not generic \"the city\") grounds the premise, and asking for something small and concrete makes the interaction easy to follow and the outcome easy to judge.",
        "translation": "Reframe \"asking strangers for gas\" as \"asking strangers for directions/a favor as an opener\" — same specific-location grounding and small-concrete-ask structure, aimed at initiating conversation with women instead of testing generosity.",
        "ca_title": "Asking Random Girls For Directions To See Who'd Actually Talk To Me",
        "ca_thumbnail": "A real street scene, creator mid-conversation with a woman, plain daylight urban backdrop, unproduced handheld framing matching the candid aesthetic.",
        "notes": "Naming a specific, real location is a cheap way to make an ordinary premise feel grounded and authentic rather than generic.",
        "status": "Not Adapted",
    },
    {
        "title": "Monkey Prank Ended by One Kind Girl...",
        "channel": "Logan Pierce",
        "url": "https://www.youtube.com/watch?v=CPMI-YuC7-w",
        "niche": "Street Prank/Social Reaction",
        "views": "211,865 (1,460 subscribers — 145.1x its subscriber count in views, a massive breakout for a tiny channel)",
        "views_num": 211865,
        "subscribers": 1460,
        "score": "145.1x subs",
        "pattern": "An escalating public prank interrupted by an unexpected act of kindness from a bystander, with the title naming the resolution (a kind girl) rather than the setup.",
        "trigger": "Curiosity about the twist (how does a random girl end the prank?) + the satisfying, wholesome reversal of an otherwise chaotic-sounding premise + a massive subscriber breakout proving a tiny channel can win with the right moment.",
        "thumbnail": "A real city crosswalk scene, a person in costume with a red circle highlighting them, a bystander visible nearby, \"GUYS\" caption capturing a real reaction, daylight urban setting.",
        "formula": "\"[Chaotic Premise] Ended By [Unexpected Kind Person]...\"",
        "why": "Naming the resolution's cause (a kind girl) instead of the chaotic setup flips the curiosity toward \"how did she factor into this,\" and the trailing \"...\" withholds exactly how.",
        "translation": "Reframe \"a chaotic prank interrupted by a kind stranger\" as \"an awkward public moment saved by a woman's warm reaction\" — same \"name the unexpected resolution, withhold how\" title structure.",
        "ca_title": "My Worst Approach Attempt Ever... Saved By One Girl's Reaction",
        "ca_thumbnail": "A real street scene, creator mid-awkward-moment, a woman visible nearby with a warm/amused expression clearly about to intervene, candid unposed daylight framing.",
        "notes": "A 145x subscriber breakout on a channel with under 1,500 subscribers is strong proof this specific title structure (name the resolution, not the setup) can work regardless of channel size.",
        "status": "Not Adapted",
    },
    {
        "title": "Crazy Glitter Bomb Prank on Stupid Porch Pirate! They get Instant Karma.",
        "channel": "PorchPirateInstantKarma",
        "url": "https://www.youtube.com/watch?v=IpZj5yvf4nI",
        "niche": "Security-Cam Justice/Revenge Prank",
        "views": "423,154 (66.8K subscribers — 6.3x its subscriber count in views, a genuine breakout)",
        "views_num": 423154,
        "subscribers": 66800,
        "score": "6.3x subs",
        "pattern": "Real doorbell-camera footage of a package thief getting caught in a glitter bomb trap, with on-screen labels (\"WRONG HOUSE,\" \"THIEF\") narrating the moment in real time as it unfolds.",
        "trigger": "Justice/karma satisfaction (a wrongdoer visibly and immediately regrets their choice) + real-time on-screen labels heightening the \"gotcha\" moment + authentic security-cam footage feeling unquestionably real.",
        "thumbnail": "A real doorbell-camera POV shot of a person recoiling from an exploding glitter trap, bold captions \"WRONG HOUSE\" and \"THIEF\" labeling the moment, muted daylight porch setting.",
        "formula": "\"Crazy [Device] Prank on Stupid [Wrongdoer]! They Get Instant Karma.\"",
        "why": "The real-time on-screen labels narrate the \"gotcha\" as it happens instead of requiring a summary title, and calling the target \"stupid\" upfront primes the viewer to enjoy their comeuppance without guilt.",
        "translation": "Reframe \"a porch pirate gets an instant-karma glitter surprise\" as \"a guy who disrespects a woman gets an instant social comeuppance\" — same real-time on-screen-label narration and unapologetic \"they had it coming\" framing.",
        "ca_title": "Crazy Comeback When A Guy Disrespected Her! He Got Instant Karma.",
        "ca_thumbnail": "A real street scene, a woman's confident reaction as a disrespectful guy visibly backpedals, bold real-time captions labeling the moment as it happens, natural daylight setting.",
        "notes": "This is the same core mechanic as the porch-pirate Shorts already in the General Shorts Outliers swipe file — a third real example of it succeeding further confirms the format is genuinely repeatable, not a fluke.",
        "status": "Not Adapted",
    },
    {
        "title": "Sneaking Onto Billionaires Estate to Visit Abandoned Mansion Once Owned by Bruce Forsyth!",
        "channel": "SIDE QUEST EXPLORING",
        "url": "https://www.youtube.com/watch?v=a8wqklwE8mU",
        "niche": "Forbidden Access/Urban Exploration",
        "views": "222,901 (20K subscribers — 11.1x its subscriber count in views, a genuine breakout)",
        "views_num": 222901,
        "subscribers": 20000,
        "score": "11.1x subs",
        "pattern": "The same forbidden-access exploration format as elsewhere in this niche, anchored to a real, named former owner for extra grounded specificity.",
        "trigger": "Forbidden curiosity (trespassing onto a real, named billionaire's estate) + the specificity of a real celebrity former owner making the premise feel grounded and researchable + decay/mystery visuals.",
        "thumbnail": "A real exterior shot of a grand, decaying mansion, an inset photo of the named former owner in formal wear, bold caption \"ABANDONED AND LEFT TO ROT,\" daylight setting.",
        "formula": "\"Sneaking Onto [Real Place] to Visit Abandoned [Location] Once Owned by [Named Real Person]!\"",
        "why": "Naming a specific real former owner (not a generic \"mystery mansion\") gives the premise instant grounded credibility, and \"sneaking onto\" adds a forbidden-access thrill on top of the exploration curiosity.",
        "translation": "Reframe \"sneaking into a named celebrity's abandoned estate\" as \"approaching someone at a real, named high-difficulty venue\" — same naming-real-specifics-for-credibility device.",
        "ca_title": "Approaching The Most Exclusive Table At The City's Hardest Club To Get Into",
        "ca_thumbnail": "A real venue exterior/interior shot, creator approaching a specific real group, bold caption naming the difficulty, similar grounded documentary framing.",
        "notes": "A second independent channel succeeding with the same \"named-specifics forbidden access\" format is stronger proof of repeatability than one example alone.",
        "status": "Not Adapted",
    },
    {
        "title": "Survival Challenge in Heavy Snow and Blizzard-21°C Temperature Alone in the Deep Wild, and Cold Jungle",
        "channel": "Wild solo camp",
        "url": "https://www.youtube.com/watch?v=VkO0ZKzW55I",
        "niche": "Extreme Survival Documentary",
        "views": "450,154 (40.8K subscribers — 11.0x its subscriber count in views, a genuine breakout)",
        "views_num": 450154,
        "subscribers": 40800,
        "score": "11.0x subs",
        "pattern": "Real, unnarrated wilderness survival footage in extreme conditions, letting the harsh visual environment alone communicate the stakes without needing a dramatic title.",
        "trigger": "Awe/respect for endurance under extreme conditions + the specificity of a real, extreme temperature (-21°C) making the stakes concrete + atmospheric, cinematic winter visuals.",
        "thumbnail": "A real snowy wilderness scene at night, a person carrying firewood toward a glowing shelter built into a large tree, heavy snowfall, moody atmospheric lighting.",
        "formula": "\"Survival Challenge in [Extreme Specific Condition], Alone in [Location Type]\"",
        "why": "A specific, extreme, concrete number (-21°C) makes the difficulty instantly legible, and the atmospheric visual alone (no text needed) sells the mood.",
        "translation": "Reframe \"surviving alone in extreme cold\" as \"approaching under the most difficult/intimidating real conditions\" — same specific-extreme-difficulty-number framing and atmospheric, minimal-text visual mood.",
        "ca_title": "Approaching Women At -21°C In A Blizzard (Extreme Difficulty Challenge)",
        "ca_thumbnail": "A real snowy street scene at night, creator approaching a woman in harsh winter conditions, moody atmospheric lighting, minimal on-screen text.",
        "notes": "A concrete, extreme specific number (a temperature, a distance, a count) is a cheap and reusable way to make a difficulty claim feel real rather than vague.",
        "status": "Not Adapted",
    },
    {
        "title": "He Handed Strangers Money and Drove Away",
        "channel": "True Tales",
        "url": "https://www.youtube.com/watch?v=K_As0VX-Gfw",
        "niche": "Narrated True Story (Zero-Filming Format)",
        "views": "181,410 (8,170 subscribers — 22.2x its subscriber count in views, a genuine breakout)",
        "views_num": 181410,
        "subscribers": 8170,
        "score": "22.2x subs",
        "pattern": "A real story narrated over on-screen text and a simple visual, naming a real person — proof that a compelling true story alone, without any original filming, can still break out.",
        "trigger": "Curiosity about a real, named generous stranger's story + the \"who was this person and why\" mystery + the wholesome payoff of an anonymous act of generosity.",
        "thumbnail": "On-screen text reciting the narrated story over a simple background image, minimal graphic design, small heart emoji branding in the corner.",
        "formula": "\"He/She [Did A Generous Anonymous Act] and [Left/Drove Away]\"",
        "why": "This format requires zero original footage — just a compelling true story and text-to-screen narration — proving the story itself, not the production, is what's carrying the video.",
        "translation": "Reframe \"an anonymous stranger's generous act, narrated\" as \"a real, narrated story about a moment of connection with a woman\" — same zero-filming, narrated-text-over-simple-visual format.",
        "ca_title": "He Told Her One Sentence Then Walked Away Forever",
        "ca_thumbnail": "On-screen text reciting the story over a simple, moody background image, minimal graphic design, small branding element in the corner.",
        "notes": "A genuinely zero-production format — worth testing as an extremely low-effort companion series alongside in-field footage.",
        "status": "Not Adapted",
    },
    {
        "title": "Japan's TERRIFYING Project to Win the World Cup!!",
        "channel": "Zeyad.",
        "url": "https://www.youtube.com/watch?v=qK6ED0SN-Zc",
        "niche": "Sports Strategy Documentary/Analysis",
        "views": "633,553 (2,790 subscribers — 227.1x its subscriber count in views, a massive breakout for a tiny channel)",
        "views_num": 633553,
        "subscribers": 2790,
        "score": "227.1x subs",
        "pattern": "A tactical/strategic breakdown framed with dramatic, ominous language (\"terrifying\") rather than neutral analysis language, paired with a composed, authoritative portrait thumbnail.",
        "trigger": "Curiosity about what could possibly make a strategy \"terrifying\" rather than just effective + the authority signal of a composed portrait with tactical diagrams + national pride/rivalry undertones.",
        "thumbnail": "A composed portrait of a football manager in formal attire, tactical formation diagrams and national team crest overlaid, bold red-accented \"TERRIFYING\" text, dramatic red/dark color grade.",
        "formula": "\"[Nation/Group]'s TERRIFYING [Plan/Project] to [Ambitious Goal]!!\"",
        "why": "\"Terrifying\" reframes a neutral strategic analysis as something with real stakes and menace, and the composed authority-figure portrait plus diagrams signals serious, credible analysis rather than clickbait speculation.",
        "translation": "Reframe \"a nation's terrifying strategic plan\" as \"a guy's terrifying-effective systematic approach method\" — same ominous-language-on-a-neutral-topic device, same authority-portrait-plus-diagram credibility signal.",
        "ca_title": "The Terrifying System That Gets Her Number Every Time",
        "ca_thumbnail": "A composed portrait of the creator in confident attire, simple diagram/notes overlaid suggesting a systematic method, bold red-accented \"TERRIFYING\" text, dramatic moody color grade.",
        "notes": "A massive 227x breakout on a channel with under 3,000 subscribers shows that dramatic reframing language on an otherwise ordinary analysis topic can travel far beyond a niche audience.",
        "status": "Not Adapted",
    },
    {
        "title": "Baby Waited All Day for Dad—The Reunion Will Leave You in Tears 😭👶💕 #baby #dad #emotional #family",
        "channel": "Little Joy Tales",
        "url": "https://www.youtube.com/watch?v=57rbmpTpxkk",
        "niche": "Family Reunion Reaction (Compilation)",
        "views": "59,984,104 (210K subscribers — 285.6x its subscriber count in views, and 30.0x its own channel average, both genuine breakouts)",
        "views_num": 59984104,
        "subscribers": 210000,
        "score": "285.6x subs, 30.0x avg",
        "pattern": "Pairs a high-stakes, vulnerable real photo of the father with a small inset of the baby's pure, uncomplicated joy, letting the viewer read the whole emotional arc in one frame.",
        "trigger": "Parental/family bond urgency (a vulnerable real moment softened by a child's love) + real, uncomposed documentary authenticity.",
        "thumbnail": "A man lying down connected to medical monitoring leads on his chest, looking upward; inset in the corner, a toddler's joyfully reaching, laughing face; muted clinical lighting on his side, warm candid lighting on the baby's inset.",
        "formula": "\"[Vulnerable Family Member] Waited All Day For [Loved One]—The Reunion Will Leave You In Tears\"",
        "why": "Pairing a high-stakes real photo with a small inset of pure joy creates instant emotional contrast that the title's promise (\"will leave you in tears\") pays off before the click.",
        "translation": "Reframe \"a medically vulnerable dad reunited with his baby\" as \"a woman waiting anxiously reunited with someone she's been missing\" — same high-stakes-photo + joyful-reaction-inset contrast, aimed at romantic reunion instead of family reunion.",
        "ca_title": "She Waited All Day For Him—Her Reaction Will Leave You In Tears",
        "ca_thumbnail": "A woman standing anxiously in a real setting, looking toward an unseen arrival; inset in the corner, her own joyfully reacting face the moment she sees him, warm candid lighting, natural setting.",
        "notes": "A doubly-confirmed outlier (285.6x subs AND 30x channel average simultaneously) — not a fluke on either metric alone.",
        "status": "Not Adapted",
    },
    {
        "title": "Adorable reaction to game night proposal! ❤️",
        "channel": "Colton Black",
        "url": "https://www.youtube.com/watch?v=BF0QK-UFN-0",
        "niche": "Proposal Reaction (Family/Game Night)",
        "views": "23,975,680 (41.9K subscribers — 572.2x its subscriber count in views, and 615.8x its own channel average, an extreme double breakout)",
        "views_num": 23975680,
        "subscribers": 41900,
        "score": "572.2x subs, 615.8x avg",
        "pattern": "A prank-style emotional swerve — an ordinary game night produces a big, visible reaction that reads as annoyance before it resolves into a sweet payoff, captured candidly at the exact moment.",
        "trigger": "Comedic tension from a mismatched emotional cue (\"mad\" instead of happy) that resolves into a sweet payoff, plus real, unstaged reaction footage.",
        "thumbnail": "A woman seated at a table playing a board game (Scrabble tiles visible), hand near her face in a shocked/annoyed expression, bold caption \"She gets MAD\" pinned to the moment, casual daylight indoor setting.",
        "formula": "\"[Escalating Emotion Caption] reaction to [Ordinary Setting] proposal!\"",
        "why": "Leading with a caption that promises the \"wrong\" emotion creates a curiosity gap resolved only by watching, and doing it inside a mundane setting makes the surprise land harder.",
        "translation": "Reframe \"she gets mad, then it turns into a proposal\" as \"she looks unimpressed at first, then completely changes when she realizes what's actually happening\" — same mismatched-emotion-then-swerve device, applied to a cold approach reaction.",
        "ca_title": "She Looked Annoyed... Until She Realized What Was Actually Happening",
        "ca_thumbnail": "A woman seated in a casual setting with an annoyed/dismissive initial expression, hand near her face, bold caption \"She looked ANNOYED\" pinned to the moment, natural daylight setting.",
        "notes": "A rare double-signal outlier (572x subs AND 616x channel average at once) on a mid-size channel — strong proof the mismatched-emotion mechanic, not channel size, drove reach.",
        "status": "Not Adapted",
    },
    {
        "title": "This Porch Pirate Regret Stealing In Seconds Caught on Camera🎬😂",
        "channel": "Karma Strikes Porch",
        "url": "https://www.youtube.com/watch?v=WP5PUpOpVZA",
        "niche": "Security-Cam Karma/Justice",
        "views": "22,655,582 (113K subscribers — 200.5x its subscriber count in views, a massive breakout)",
        "views_num": 22655582,
        "subscribers": 113000,
        "score": "200.5x subs",
        "pattern": "Real doorbell-camera footage capturing a thief's immediate regret in the act, with a blunt, unapologetic caption judging the wrongdoer directly.",
        "trigger": "Instant justice/karma satisfaction + authentic security-cam footage + a caption that openly sides with the viewer against the wrongdoer.",
        "thumbnail": "A nighttime porch security-cam shot of a person recoiling/reacting mid-theft, bold caption \"You Got What You Deserve\" stamped over the scene, dim outdoor porch lighting, real timestamp/camera-UI framing.",
        "formula": "\"This [Wrongdoer] Regret [Action] In Seconds Caught on Camera\" + blunt on-screen judgment caption",
        "why": "The caption renders a verdict instead of just describing the moment, letting viewers enjoy the comeuppance guilt-free, and \"caught on camera\" promises unstaged, real proof.",
        "translation": "Reframe \"a porch pirate instantly regrets stealing\" as \"a guy who disrespects a woman instantly regrets it\" — same instant-regret + judgmental-caption formula.",
        "ca_title": "He Regretted Disrespecting Her In Seconds — Caught On Camera",
        "ca_thumbnail": "A real street/night setting, a man visibly recoiling/backpedaling after a woman's sharp response, bold caption \"He Got What He Deserved\" stamped over the scene, natural dim lighting, candid framing.",
        "notes": "Same core \"instant karma + blunt caption\" mechanic already validated elsewhere in this file (PorchPirateInstantKarma, RoadGoneWrongTV) — a further independent confirmation the format travels.",
        "status": "Not Adapted",
    },
    {
        "title": "Soldier Surprises His Mom in Class 😭#shortsvideo",
        "channel": "Ziffy Explain",
        "url": "https://www.youtube.com/watch?v=0AinvGzvm-4",
        "niche": "Military Homecoming Surprise",
        "views": "21,111,049 (3.73M subscribers — 5.7x its subscriber count in views, and 23.9x its own channel average, a genuine breakout even for a large channel)",
        "views_num": 21111049,
        "subscribers": 3730000,
        "score": "5.7x subs, 23.9x avg",
        "pattern": "The exact reveal moment is staged in the thumbnail itself — the soldier already holding the reveal sign, the recipient mid-turn to notice him — collapsing the whole emotional arc into one anticipatory freeze-frame.",
        "trigger": "Anticipation of an emotional reunion (the viewer is one beat ahead of the subject discovering the surprise) + the plain sign doing the emotional work without narration.",
        "thumbnail": "A soldier in uniform standing at a doorway holding a handwritten \"I'M HOME\" sign, a woman in a red top just beginning to turn and notice him from inside, a small clock icon overlay signaling the moment is about to happen, bright indoor lighting.",
        "formula": "\"[Military Member] Surprises [Family Member] in [Mundane Real Setting]\"",
        "why": "Freezing the frame one beat before recognition creates unbearable anticipation only the video resolves, and a large channel still clearing 23.9x its own average proves the mechanic isn't dependent on audience novelty.",
        "translation": "Reframe \"a soldier surprises his mom by showing up\" as \"a guy surprises someone who has no idea he's about to walk in\" — same one-beat-before-recognition freeze-frame device.",
        "ca_title": "She Had No Idea He Was About To Walk In",
        "ca_thumbnail": "The creator standing at a doorway or entrance holding a simple handwritten sign, a woman just beginning to turn and notice him, small clock icon overlay building anticipation, bright natural indoor lighting.",
        "notes": "A large (3.7M-subscriber) channel still clearing this bar via channel-average multiplier confirms the freeze-frame device works regardless of channel size.",
        "status": "Not Adapted",
    },
    {
        "title": "They're finally reunited.#usa🇺🇸 #reunion #surprise",
        "channel": "Vaulted Lists",
        "url": "https://www.youtube.com/watch?v=p-PnqJsNOsM",
        "niche": "Reunion Compilation (Aggregator)",
        "views": "13,916,023 (14.5K subscribers — 959.7x its subscriber count in views, and 51.1x its own channel average, an extreme double breakout)",
        "views_num": 13916023,
        "subscribers": 14500,
        "score": "959.7x subs, 51.1x avg",
        "pattern": "Re-shares a real, already-powerful reunion photo with a minimal, plain caption, letting the image carry the entire video with almost no added packaging.",
        "trigger": "Vicarious warmth from witnessing a genuine long-awaited reunion + minimal captioning reading as authentic rather than manufactured.",
        "thumbnail": "A real photo of a military reunion, multiple uniformed figures and family members embracing on a driveway, muted daylight, minimal-to-no on-screen text.",
        "formula": "\"They're finally reunited.#[hashtags]\"",
        "why": "A near-caption-less approach on an already emotionally loaded real photo signals \"this speaks for itself,\" and a 960x subscriber multiplier on a tiny aggregator channel shows curation alone can travel enormously far.",
        "translation": "Reframe \"a found reunion photo shared with minimal captioning\" as \"a real moment of romantic reconnection shared the same understated way\" — same let-the-photo-speak device.",
        "ca_title": "They're finally back together.",
        "ca_thumbnail": "A real, candid photo of a couple embracing in an ordinary outdoor setting, muted natural daylight, minimal to no on-screen text, letting the image carry the emotional weight.",
        "notes": "Proof pure curation (re-sharing a powerful real photo with almost no packaging) can outperform heavily produced content — a near-zero-effort format worth testing sparingly.",
        "status": "Not Adapted",
    },
    {
        "title": "Before and After: Complete Renovation of An old woman Bedroom#beforeandafter #transformation",
        "channel": "Space Revival",
        "url": "https://www.youtube.com/watch?v=SgaDaJV3Vmw",
        "niche": "Home Renovation/Transformation Reveal",
        "views": "13,098,817 (37.3K subscribers — 351.2x its subscriber count in views, and 33.9x its own channel average, a double breakout)",
        "views_num": 13098817,
        "subscribers": 37300,
        "score": "351.2x subs, 33.9x avg",
        "pattern": "Leads with the \"before\" (decay, hardship, an elderly woman in a run-down room) rather than the after, so the thumbnail sells the stakes of the transformation instead of spoiling the payoff.",
        "trigger": "Empathy for visible hardship + the promise of a satisfying, complete transformation withheld until the video plays.",
        "thumbnail": "A real, dimly lit and visibly deteriorated room, an elderly woman seated among clutter and disrepair while a worker crouches beside her helping, muted natural window light, no text overlay needed.",
        "formula": "\"Before and After: Complete [Transformation Type] of [Specific Vulnerable Subject]\"",
        "why": "Showing the \"before\" state creates a stakes-first hook (this looks bad, how does it get fixed?) rather than a payoff-first one, and a vulnerable, sympathetic subject raises the emotional stakes.",
        "translation": "Reframe \"the before state of a room transformation\" as \"the before state of a person's confidence transformation\" — same stakes-first, show-the-hardship-not-the-fix device.",
        "ca_title": "Before And After: Her Complete Confidence Transformation",
        "ca_thumbnail": "A real, candid \"before\" moment showing a woman in an ordinary, unglamorous setting with a genuine, unposed expression, natural window light, no text overlay — letting the contrast do the work once the video plays.",
        "notes": "The withheld-payoff structure (show the hardship, not the fix) is a reusable way to make a transformation format feel earned rather than gimmicky.",
        "status": "Not Adapted",
    },
    {
        "title": "The Viral Gift 🎁✨ [Kindzilla] # kindzilla #funny #shorts #hero #kindness #justice",
        "channel": "Kindzilla",
        "url": "https://www.youtube.com/watch?v=DLhAVf99DC8",
        "niche": "Kindness/Small-Gesture Reveal (Kids)",
        "views": "12,700,072 (391K subscribers — 32.5x its subscriber count in views, a genuine breakout)",
        "views_num": 12700072,
        "subscribers": 391000,
        "score": "32.5x subs",
        "pattern": "A small, specific, kid-scale act of kindness (a bracelet exchange) captured candidly and framed with the channel's recurring branded name as a trust signal for the genre.",
        "trigger": "Warmth from witnessing an unprompted, small generous gesture + brand-name recognition for viewers already familiar with the channel's format.",
        "thumbnail": "Two boys facing each other indoors, one handing over a small item (bracelet), candid unposed framing, natural indoor lighting.",
        "formula": "\"The Viral [Object] 🎁✨ [Channel Branding] #kindness\"",
        "why": "Keeping the act small and specific makes it feel achievable and real, and consistent branding across entries builds a recognizable, trusted \"kindness content\" identity.",
        "translation": "Reframe \"kids exchanging a small gift\" as \"a small, specific generous gesture between a guy and a woman he's just met\" — same small-scale-specific-kindness framing.",
        "ca_title": "I Gave Her Something Small — Her Reaction Went Viral",
        "ca_thumbnail": "The creator and a woman facing each other outdoors, mid-handoff of a small item, candid unposed framing, natural daylight.",
        "notes": "A recurring branded \"kindness series\" identity is a reusable device for building trust and repeat viewership across many individually low-stakes moments.",
        "status": "Not Adapted",
    },
    {
        "title": "When A Biker Teaches A Newbie A Important Lesson!",
        "channel": "CrazyCam",
        "url": "https://www.youtube.com/watch?v=wZVVWKt7Qhc",
        "niche": "Dashcam Teaching Moment",
        "views": "8,639,402 (16.5K subscribers — 523.6x its subscriber count in views, a massive breakout)",
        "views_num": 8639402,
        "subscribers": 16500,
        "score": "523.6x subs",
        "pattern": "Real dashcam footage of an in-the-moment verbal exchange, with the subject's own words captioned verbatim, letting the real dialogue itself sell the \"teaching moment.\"",
        "trigger": "Curiosity about what lesson could come from an ordinary drive + authenticity of real, unscripted verbatim dialogue.",
        "thumbnail": "A real dashcam interior shot, the driver mid-conversation, a caption quoting his exact words (\"Car Driver: Yeah I Hear You\"), natural daylight through the windshield.",
        "formula": "\"When A [Everyday Figure] Teaches A [Novice] A[n] Important Lesson!\"",
        "why": "Quoting the subject's real, exact words makes the moment feel unmistakably authentic, and framing an ordinary interaction as containing \"an important lesson\" adds stakes to a mundane setting.",
        "translation": "Reframe \"a biker teaching a driving newbie a lesson\" as \"a woman teaching the creator something unexpected about himself/approaching\" — same verbatim-quote-as-caption authenticity device.",
        "ca_title": "She Taught Me An Important Lesson I Didn't Expect",
        "ca_thumbnail": "A real candid shot of the creator mid-conversation with a woman, a caption quoting her exact words, natural daylight outdoor setting.",
        "notes": "Quoting real, verbatim dialogue as the on-screen caption, rather than a summary, is a cheap, reusable authenticity device.",
        "status": "Not Adapted",
    },
    {
        "title": "Solider surprise visit to wedding ❤️ #surprise #wedding #cominghome #foryour #military",
        "channel": "Sophia Wilson",
        "url": "https://www.youtube.com/watch?v=0-xwVQKlw6A",
        "niche": "Military Homecoming Surprise (Wedding)",
        "views": "8,379,274 (180K subscribers — 46.6x its subscriber count in views, a genuine breakout)",
        "views_num": 8379274,
        "subscribers": 180000,
        "score": "46.6x subs",
        "pattern": "Combines two high-emotion event types (a wedding and a military reunion) into one moment, so the thumbnail's stakes are doubled without needing added graphic design.",
        "trigger": "Compounded emotional payoff (two big-life-moment triggers at once) + real, candid event photography.",
        "thumbnail": "A real wedding aisle scene, a bride in her dress reacting as a soldier in dress uniform approaches, other guests visible, natural daylight, no text overlay needed.",
        "formula": "\"[Military Member] surprise visit to [Major Life Event]\"",
        "why": "Stacking two independently powerful emotional contexts compounds the payoff without requiring extra title complexity or graphic work.",
        "translation": "Reframe \"a soldier surprising a wedding\" as \"a guy showing up at a major moment in a woman's life, uninvited but welcome\" — same compounded-occasion stacking device.",
        "ca_title": "I Showed Up To Her Biggest Day Uninvited — Here's What Happened",
        "ca_thumbnail": "A real event scene (formal occasion), a woman reacting with surprise as the creator approaches, other guests visible in the background, natural daylight, no text overlay.",
        "notes": "Stacking two independently strong emotional contexts in one moment is a low-cost way to raise stakes without extra production.",
        "status": "Not Adapted",
    },
    {
        "title": "Standing up for others can remind us that respect matters in every situation",
        "channel": "Lemon Kind Souls",
        "url": "https://www.youtube.com/watch?v=mh_1l1JytqU",
        "niche": "Street Justice/Standing Up For Others",
        "views": "7,566,614 (41.6K subscribers — 181.9x its subscriber count in views, and 44.9x its own channel average, a double breakout)",
        "views_num": 7566614,
        "subscribers": 41600,
        "score": "181.9x subs, 44.9x avg",
        "pattern": "Real street footage of someone taking direct, visible action against a stranger's disrespectful behavior, the caption framing it as a message about respect rather than describing the specific incident.",
        "trigger": "Satisfaction of watching someone hold a stranger accountable in real time + a universal, relatable framing that applies the specific incident to a broader life lesson.",
        "thumbnail": "A real coastal street scene, a man pouring something onto/at a poorly parked car in visible protest, palm trees and ocean visible in the background, natural daylight, minimal to no text overlay.",
        "formula": "\"[Universal Life Lesson Statement] can remind us that [Value] matters in every situation\"",
        "why": "Framing a specific, satisfying real incident as a universal lesson gives the video a shareable, quotable takeaway beyond the moment itself.",
        "translation": "Reframe \"standing up to a stranger's disrespectful parking\" as \"standing up for someone during an uncomfortable public moment\" — same universal-lesson-framing-on-a-specific-incident device.",
        "ca_title": "Standing Up For Her Reminded Me That Respect Matters In Every Situation",
        "ca_thumbnail": "A real street scene, the creator visibly stepping in during a tense moment involving a woman, natural daylight, minimal text overlay.",
        "notes": "Framing a specific incident as a universal, quotable lesson is a reusable device for giving otherwise-niche content broader shareability.",
        "status": "Not Adapted",
    },
    {
        "title": "Homeless Man Tests Strangers’ Kindness#shorts #kindness",
        "channel": "Golden Ties",
        "url": "https://www.youtube.com/watch?v=REs8JW4QcDY",
        "niche": "Kindness Test/Social Experiment",
        "views": "7,267,395 (41.9K subscribers — 173.4x its subscriber count in views, and 25.2x its own channel average, a double breakout)",
        "views_num": 7267395,
        "subscribers": 41900,
        "score": "173.4x subs, 25.2x avg",
        "pattern": "A real disguised-status kindness test, the thumbnail freezing the exact moment of the generous act itself rather than a before/after or reaction shot.",
        "trigger": "Curiosity about how strangers respond to someone in visible need + the warm payoff of witnessing genuine generosity mid-act.",
        "thumbnail": "A real street scene, an older man with a weathered appearance receiving a burger from another person's hands, close-cropped on the handoff itself, natural daylight, no text overlay.",
        "formula": "\"[Disguised/Vulnerable Status] Man Tests Strangers' Kindness\"",
        "why": "Freezing the moment of the generous act itself lets the thumbnail promise exactly what the video delivers, and framing it as a \"test\" invites the viewer to judge the outcome.",
        "translation": "Reframe \"a homeless man tests strangers' kindness\" as \"a guy tests how strangers react to him in a vulnerable or lower-status presentation\" — same freeze-the-generous-act-mid-motion device.",
        "ca_title": "I Approached Looking Like I Had Nothing — Here's Who Actually Talked To Me",
        "ca_thumbnail": "A real street scene, the creator in an unassuming, lower-status presentation mid-conversation with a woman who's clearly engaging warmly, natural daylight, no text overlay.",
        "notes": "Freezing the thumbnail on the exact generous act, not a reaction shot, is a repeatable device across kindness-test content.",
        "status": "Not Adapted",
    },
    {
        "title": "Karen Blocking Drivers Way Gets Instant Karma",
        "channel": "Police Bodycam USA",
        "url": "https://www.youtube.com/watch?v=SPW6Vpvv8sI",
        "niche": "Bodycam Confrontation/Karma",
        "views": "7,092,043 (141K subscribers — 50.3x its subscriber count in views, a genuine breakout)",
        "views_num": 7092043,
        "subscribers": 141000,
        "score": "50.3x subs",
        "pattern": "Real bodycam/security footage of a confrontational person refusing to comply, labeled with the internet-recognizable \"Karen\" archetype and a blunt real-time status caption.",
        "trigger": "Satisfaction of watching an entitled, rule-breaking person face consequences + the shorthand recognition of the archetype doing instant characterization work.",
        "thumbnail": "A real street/parking-lot bodycam scene, a person standing defiantly beside a car, bold \"Karen\" label and \"*Refuses to leave*\" status caption stamped over the moment, daylight setting, authentic camera-UI framing.",
        "formula": "\"[Archetype Label] [Bad Behavior] Gets Instant Karma\"",
        "why": "A widely-recognized shorthand archetype does instant characterization without backstory, and a real-time status caption narrates the standoff as it's still unresolved, creating tension.",
        "translation": "Reframe \"an entitled person refusing to comply gets karma\" as \"a disrespectful guy refusing to back off gets an instant social comeback\" — same archetype-label + real-time-status-caption device.",
        "ca_title": "He Refused To Leave Her Alone — Then This Happened",
        "ca_thumbnail": "A real street scene, a woman standing her ground against a persistent guy, bold \"*Refuses to leave*\" status caption stamped over the moment, natural daylight, authentic candid framing.",
        "notes": "The archetype-label device is a reusable one-word characterization shortcut across the whole karma/justice genre.",
        "status": "Not Adapted",
    },
    {
        "title": "This Man Felt the Girl’s Sadness and Did Something Unexpected #emotional #shorts #kind #touching",
        "channel": "MARKEY",
        "url": "https://www.youtube.com/watch?v=t8DX630lW0Y",
        "niche": "Wholesome Stranger Skit/Reaction",
        "views": "6,737,812 (185K subscribers — 36.4x its subscriber count in views, a genuine breakout)",
        "views_num": 6737812,
        "subscribers": 185000,
        "score": "36.4x subs",
        "pattern": "A close, emotionally raw shot of a visibly upset person, paired with a title that withholds exactly what the \"unexpected\" response was.",
        "trigger": "Empathy for visible distress + curiosity about the specific unexpected response withheld by the title.",
        "thumbnail": "A close-up shot of a young girl mid-cry, genuine raw emotional expression, a partial caption (\"TOUCHED YOUR...\") cut off to build curiosity, dim ambient lighting.",
        "formula": "\"This [Person] Felt The [Subject]'s [Emotion] and Did Something Unexpected\"",
        "why": "A raw, close emotional shot creates instant empathy, and promising an \"unexpected\" response without revealing it, plus a caption cut off mid-sentence, compounds the curiosity gap.",
        "translation": "Reframe \"a man noticing a girl's sadness and responding\" as \"a guy noticing a woman's real emotional state during an approach and responding in a way she didn't expect\" — same raw-close-up + withheld-response structure.",
        "ca_title": "He Noticed She Was Having A Hard Day — What He Did Next Surprised Her",
        "ca_thumbnail": "A close-up shot of a woman with a genuine, vulnerable expression, a partial caption cut off mid-sentence to build curiosity, dim ambient natural lighting.",
        "notes": "Cutting the on-screen caption off mid-sentence, rather than completing the thought, is a cheap way to add a curiosity gap on top of the title's own hook.",
        "status": "Not Adapted",
    },
    {
        "title": "Brake Checker Cop Karma 🚨",
        "channel": "RoadGoneWrongTV",
        "url": "https://www.youtube.com/watch?v=tUinEIlxYE8",
        "niche": "Dashcam Karma (Traffic)",
        "views": "5,576,953 (13.1K subscribers — 425.7x its subscriber count in views, a massive breakout)",
        "views_num": 5576953,
        "subscribers": 13100,
        "score": "425.7x subs",
        "pattern": "Real dashcam footage of a specific, nameable traffic offense, labeled bluntly in bold text with the exact wrongdoing, letting viewers recognize the setup instantly.",
        "trigger": "Satisfaction of watching a specific bad-driving behavior get consequences + recognition of a common, relatable road-rage scenario.",
        "thumbnail": "A real nighttime dashcam shot, a vehicle brake-checking ahead, bold red-accented \"BRAKE CHECKER\" text label, a circular highlight/zoom on the offending car, authentic dashcam framing.",
        "formula": "\"[Specific Named Offense] Cop/Driver Karma\"",
        "why": "Naming the exact offense in bold text lets viewers who've experienced it instantly self-select in, and the karma payoff is a near-universal satisfaction across drivers.",
        "translation": "Reframe \"a specific named bad-driving behavior getting karma\" as \"a specific named disrespectful approach behavior getting an instant social consequence\" — same named-offense + circular-highlight device.",
        "ca_title": "The 'Ignore Her Completely' Guy Gets Instant Karma",
        "ca_thumbnail": "A real street scene at night, bold red-accented text naming the specific behavior, a circular highlight/zoom on the guy in question, authentic candid framing.",
        "notes": "Naming the exact offense in bold text, rather than a vague label, is a reusable specificity device across the whole karma genre.",
        "status": "Not Adapted",
    },
    {
        "title": "Officer Surprises Struggling Veteran With A New Wheelchair ❤️ #respect #kindness #everydayhero",
        "channel": "Story Nest",
        "url": "https://www.youtube.com/watch?v=bLQy8Yca2W4",
        "niche": "Kindness/Generosity Surprise (Veteran)",
        "views": "2,549,891 (23.4K subscribers — 109.0x its subscriber count in views, and 34.2x its own channel average, a double breakout)",
        "views_num": 2549891,
        "subscribers": 23400,
        "score": "109.0x subs, 34.2x avg",
        "pattern": "A specific, dignity-preserving act of generosity (a needed mobility aid, not cash) toward a sympathetic, vulnerable real subject.",
        "trigger": "Empathy for visible hardship + admiration for a thoughtful, specific act of generosity rather than a generic one.",
        "thumbnail": "A real outdoor scene, uniformed officers standing beside an elderly man in a wheelchair, family members visible nearby reacting warmly, natural daylight, no heavy text overlay.",
        "formula": "\"[Authority Figure] Surprises [Sympathetic Vulnerable Person] With [Specific Needed Gift]\"",
        "why": "Choosing a specific, genuinely useful gift makes the generosity feel thoughtful rather than performative, and pairing an authority figure with a vulnerable civilian adds a respect-across-status dimension.",
        "translation": "Reframe \"an officer surprising a veteran with a specific needed gift\" as \"a guy surprising someone with something specifically thoughtful, not generic\" — same specific-not-generic-generosity device.",
        "ca_title": "I Surprised Her With The One Thing She Actually Needed",
        "ca_thumbnail": "A real outdoor scene, the creator and a woman with a genuinely surprised, moved expression at receiving something visibly specific and thoughtful, natural daylight, no heavy text overlay.",
        "notes": "Specificity of the gift, not its size, is what makes generosity content land — a small, thoughtful, needed gift outperforms a generic big one.",
        "status": "Not Adapted",
    },
    {
        "title": "He saved her from the most embarrassing moment ❤️🩹 #kindness #shorts",
        "channel": "Couple Clips",
        "url": "https://www.youtube.com/watch?v=dWFVJ6K2Vhg",
        "niche": "Wholesome Couple Reaction Skit",
        "views": "2,561,428 (12.6K subscribers — 203.3x its subscriber count in views, a massive breakout)",
        "views_num": 2561428,
        "subscribers": 12600,
        "score": "203.3x subs",
        "pattern": "Frames the \"embarrassing moment\" as already resolved by the title, so the thumbnail can focus entirely on building anticipation for his reaction rather than showing the incident itself.",
        "trigger": "Curiosity about a specific reaction promised twice (title + caption) but withheld visually + relatability of a universal embarrassing-moment fear.",
        "thumbnail": "A candid indoor shot of a man reacting with visible surprise, hands near his face, bold captions \"She Didn't Expect This Reaction\" and \"AND HIS REACTION\" stacked to build anticipation, natural indoor lighting.",
        "formula": "\"He Saved Her From The Most Embarrassing Moment\"",
        "why": "Resolving the plot in the title itself removes suspense about the outcome and replaces it with suspense about the specific reaction, which the stacked captions repeatedly promise but never show until the video plays.",
        "translation": "Reframe \"he saved her from an embarrassing moment\" as \"he stepped in during an awkward moment for a stranger and her reaction wasn't what he expected\" — same resolved-plot-but-withheld-reaction structure.",
        "ca_title": "I Stepped In During Her Awkward Moment — Her Reaction Wasn't What I Expected",
        "ca_thumbnail": "A candid outdoor shot of a woman reacting with visible surprise, bold stacked captions building anticipation for her specific reaction, natural daylight.",
        "notes": "Resolving \"what happened\" in the title while withholding \"how they reacted\" is a reusable way to keep curiosity alive even after spoiling the plot.",
        "status": "Not Adapted",
    },
    {
        "title": "Skate Thief Gets Instant Karma — Caught on Camera",
        "channel": "Takesh! Samurai",
        "url": "https://www.youtube.com/watch?v=L6BW8Vq1p0Q",
        "niche": "Street Karma/Instant Justice",
        "views": "4,602,891 (3.45K subscribers — 1,334.2x its subscriber count in views, and 94.4x its own channel average, an extreme breakout on a tiny channel)",
        "views_num": 4602891,
        "subscribers": 3450,
        "score": "1334.2x subs, 94.4x avg",
        "pattern": "An extremely tiny channel breaks out over 1,300x with a real street theft caught and resolved on camera, proving the mechanic, not the channel, drives the reach.",
        "trigger": "Satisfaction of watching a specific, nameable theft get immediate consequences + proof-of-concept that this can happen to anyone filming their own street footage.",
        "thumbnail": "A close-up candid shot of a young man's face outdoors, a bold red banner reading \"Skate Thief Instant Karma,\" a small score/point graphic in the corner, natural daylight.",
        "formula": "\"[Specific Named Theft] Gets Instant Karma\"",
        "why": "A tiny channel (3,450 subscribers) hitting a 1,334x multiplier is close to the strongest possible proof this specific mechanic, not subscriber base or editing budget, drives the reach.",
        "translation": "Reframe \"someone stealing a skateboard gets instant karma\" as \"a guy trying to steal a woman's attention dishonestly gets an instant, visible social consequence\" — same named-specific-wrongdoing + instant-karma structure.",
        "ca_title": "The 'Fake Confidence' Guy Gets Instant Karma",
        "ca_thumbnail": "A close-up candid shot of the creator's face outdoors, a bold red banner naming the specific behavior, natural daylight, unpolished handheld framing.",
        "notes": "One of the strongest single data points in this batch for \"format over channel size\" — a channel with under 3,500 subscribers still cleared over 1,300x.",
        "status": "Not Adapted",
    },
    {
        "title": "The Most Unreal Proposal Ever 🥹💍 #trending #trend #shorts",
        "channel": "Aesthetic_Lyrixx",
        "url": "https://www.youtube.com/watch?v=EIkIgK0wPGI",
        "niche": "Proposal Reaction",
        "views": "3,829,494 (2.91K subscribers — 1,316.0x its subscriber count in views, and 140.0x its own channel average, an extreme breakout on a tiny channel)",
        "views_num": 3829494,
        "subscribers": 2910,
        "score": "1316.0x subs, 140.0x avg",
        "pattern": "A cinematic black-and-white treatment of a real proposal moment, paired with a quote-style caption that frames the moment as legendary rather than just describing it.",
        "trigger": "Aesthetic/emotional elevation of an ordinary event-type into something that feels timeless and shareable + curiosity about what makes this one specifically \"unreal.\"",
        "thumbnail": "A black-and-white candid photo of a couple on an elevated urban structure mid-proposal, a stylized quote-style caption (\"A proposal the world will never forget\") overlaid, dramatic monochrome grade.",
        "formula": "\"The Most Unreal [Event Type] Ever\"",
        "why": "Stripping color and adding a quote-style caption elevates an otherwise-common event type into something that reads as artistically significant, likely why a sub-3,000-subscriber channel cleared over 1,300x its own base.",
        "translation": "Reframe \"the most unreal proposal ever\" as \"the most unreal reaction to an approach ever\" — same monochrome-cinematic-treatment + quote-style-caption elevation device.",
        "ca_title": "The Most Unreal Reaction To An Approach Ever",
        "ca_thumbnail": "A black-and-white candid photo of the creator and a woman mid-genuine-reaction in an urban setting, a stylized quote-style caption overlaid, dramatic monochrome grade.",
        "notes": "A second extreme (1,000x+) breakout from a near-zero-subscriber channel in this batch — further evidence packaging, not audience size, is the deciding factor.",
        "status": "Not Adapted",
    },
    {
        "title": "I Bought A $1.3M Mansion...They Left Everything Behind",
        "channel": "Jesse Stolz",
        "url": "https://www.youtube.com/watch?v=PzyorkHczpQ",
        "niche": "Real Estate Mystery/Documentary",
        "views": "1,407,757 (44.6K subscribers — 31.6x its subscriber count in views, and 29.8x its own channel average, a double breakout)",
        "views_num": 1407757,
        "subscribers": 44600,
        "score": "31.6x subs, 29.8x avg",
        "pattern": "A real purchase/exploration documentary that leads with the mystery of an abandonment rather than the property itself, using a direct-address pointing gesture to draw the eye to the specific detail.",
        "trigger": "Curiosity about why someone would leave everything behind (implied backstory mystery) + the personal, direct-address framing making it feel like a real, ongoing investigation.",
        "thumbnail": "A real exterior shot of a large mansion, the creator in the foreground pointing toward it in a ballcap, bold caption \"THEY LEFT EVERYTHING BEHIND\" across the top, natural daylight.",
        "formula": "\"I Bought A $[Price] [Property]...They Left Everything Behind\"",
        "why": "Naming a specific, real, large dollar figure grounds the claim, and \"they left everything behind\" opens a mystery about the previous owners the video promises to explore, not just show off the purchase.",
        "translation": "Reframe \"buying a mystery-abandoned mansion\" as \"approaching a woman with an unexplained, specific mystery detail as the hook\" — same specific-real-detail-implies-a-story device.",
        "ca_title": "I Approached Her... She Had One Detail Nobody Could Explain",
        "ca_thumbnail": "The creator pointing toward a woman in a real setting, bold caption naming the specific unexplained detail, natural daylight, direct-address framing.",
        "notes": "A specific real dollar figure or detail, not a vague superlative, is what makes the mystery premise feel grounded and click-worthy.",
        "status": "Not Adapted",
    },
    {
        "title": "The Hardest Stage of Life Is Between 65 and 75. Here’s Why!",
        "channel": "Candle of Wisdom",
        "url": "https://www.youtube.com/watch?v=h8NzdUh7C0Y",
        "niche": "Life-Stage Wisdom/Advice (Talking Head)",
        "views": "1,124,603 (97.3K subscribers — 11.6x its subscriber count in views, and 27.3x its own channel average, a double breakout)",
        "views_num": 1124603,
        "subscribers": 97300,
        "score": "11.6x subs, 27.3x avg",
        "pattern": "A direct, authoritative talking-head claim naming a very specific, counterintuitive age range, with \"no one tells you\" promising insider information withheld from the mainstream conversation.",
        "trigger": "Curiosity from a specific, oddly precise claim (why THAT decade specifically?) + the \"secret knowledge\" appeal of information no one tells you.",
        "thumbnail": "An older man speaking directly to camera outdoors, bold on-screen text stating the exact claim and age range, a parenthetical \"(No One Tells You)\" tag, natural daylight, simple unproduced framing.",
        "formula": "\"The Hardest [Life Stage] Is Between [Specific Age Range]. Here's Why! (No One Tells You)\"",
        "why": "A precise, specific numeric range feels more credible and intriguing than a vague claim, and framing it as suppressed/overlooked knowledge adds a why-hasn't-anyone-said-this-before hook.",
        "translation": "Reframe \"the hardest life stage is a specific age range\" as \"the hardest part of approaching/dating is a specific, named phase, not the one people assume\" — same precise-claim + withheld-knowledge structure.",
        "ca_title": "The Hardest Part Of Approaching Isn't What You Think. Here's Why! (No One Tells You)",
        "ca_thumbnail": "The creator speaking directly to camera outdoors, bold on-screen text stating the specific counterintuitive claim, natural daylight, simple unproduced framing.",
        "notes": "Zero-production, direct-to-camera talking-head format proven to work at scale — a viable low-cost companion series alongside in-field footage.",
        "status": "Not Adapted",
    },
    {
        "title": "Military sister surprises her brother at high school graduation after serving in Iran War",
        "channel": "Queen City News",
        "url": "https://www.youtube.com/watch?v=GXGla1zJ9h8",
        "niche": "Local News/Military Surprise",
        "views": "1,146,027 (264K subscribers — 204.2x its own channel average, a genuine breakout even without a subscriber-multiplier signal)",
        "views_num": 1146027,
        "subscribers": 264000,
        "score": "204.2x avg",
        "pattern": "A real local-news clip capturing an unscripted graduation-ceremony surprise, with the specific military context raising the stakes of an already-emotional milestone event.",
        "trigger": "Compounded emotional payoff (graduation milestone + military homecoming) + authenticity of real, unscripted news-camera footage.",
        "thumbnail": "A real graduation ceremony stage, a uniformed figure walking down the aisle toward a graduate, an audience visible in the background, natural indoor event lighting, no added text overlay needed.",
        "formula": "\"[Family Member] Surprises [Relative] at [Major Milestone Event] After [Specific Real Context]\"",
        "why": "Stacking a milestone event with a military-service context compounds the emotional stakes, and a specific real detail grounds the story as more than generic \"soldier comes home\" content.",
        "translation": "Reframe \"a sister surprising her brother at graduation after military service\" as \"a woman showing up at a guy's major milestone moment after a meaningful specific absence\" — same compounded-milestone + specific-real-context device.",
        "ca_title": "She Showed Up To My Biggest Day After Everything That Happened Between Us",
        "ca_thumbnail": "A real event setting, a woman walking toward the creator mid-milestone-moment, an audience/crowd visible in the background, natural indoor or outdoor event lighting.",
        "notes": "This entry cleared the bar purely on channel-average multiplier (204.2x) with no subscriber-multiplier signal at all — a reminder the three signals are independent, not redundant.",
        "status": "Not Adapted",
    },
    {
        "title": "She Had NO Idea What Was Coming… 👀❤️ | Engagement Surprise (Part 1) #engagementdance",
        "channel": "RAHUL SINGH RAJAWAT",
        "url": "https://www.youtube.com/watch?v=I9dJTJSp8pk",
        "niche": "Engagement/Dance Surprise",
        "views": "2,423,370 (14.4K subscribers — 168.3x its subscriber count in views, a massive breakout)",
        "views_num": 2423370,
        "subscribers": 14400,
        "score": "168.3x subs",
        "pattern": "A real engagement-event moment framed from the surprised subject's point of view before the surprise happens, with \"(Part 1)\" promising a continuing series.",
        "trigger": "Anticipation of an imminent surprise the subject doesn't yet know about + serialized \"Part 1\" framing that encourages follow/subscribe behavior.",
        "thumbnail": "A real formal event scene, a woman in ornate traditional dress among other guests, a caption \"She had NO idea...\" overlaid, warm indoor event lighting.",
        "formula": "\"She Had NO Idea What Was Coming… [Event Type] (Part 1)\"",
        "why": "Capturing the moment just before the subject knows what's coming creates a \"get there first\" anticipation the viewer wants resolved, and marking it \"(Part 1)\" turns a single moment into a serialized hook.",
        "translation": "Reframe \"she had no idea an engagement surprise was coming\" as \"she had no idea what was about to happen during this approach\" — same before-the-reveal anticipation + serialized \"Part 1\" device.",
        "ca_title": "She Had NO Idea What Was About To Happen (Part 1)",
        "ca_thumbnail": "A real event or street setting, a woman mid-conversation with no visible awareness of what's coming, a caption \"She had NO idea...\" overlaid, warm natural lighting.",
        "notes": "The \"(Part 1)\" tag is a cheap, reusable device for turning a single strong moment into a serialized hook that encourages subscribing for the follow-up.",
        "status": "Not Adapted",
    },
    {
        "title": "He Turned Thrown-Away Flowers Into Love for Strangers#kindness#reversal",
        "channel": "Nicolas Vigloru",
        "url": "https://www.youtube.com/watch?v=h3Qt6AkoVH4",
        "niche": "Stranger Kindness Documentary",
        "views": "631,431 (64K subscribers — 9.9x its subscriber count in views, a genuine breakout)",
        "views_num": 631431,
        "subscribers": 64000,
        "score": "9.9x subs",
        "pattern": "A specific, resourceful act of generosity (rescuing discarded flowers to give away) captured in the recipient's genuine, unposed joy rather than the giver's action.",
        "trigger": "Warmth from witnessing an unexpected, resourceful kindness + the specific \"rescued/thrown-away\" detail making the gesture feel more meaningful than buying something new.",
        "thumbnail": "A real outdoor park scene, an elderly woman smiling genuinely while holding a fresh bouquet of flowers, natural daylight, candid unposed framing, no text overlay needed.",
        "formula": "\"He Turned [Discarded/Overlooked Thing] Into [Gift] for Strangers\"",
        "why": "The detail that the flowers were thrown away, not purchased, reframes an ordinary gift into a resourceful gesture, and centering the thumbnail on the recipient's genuine joy sells the emotional payoff directly.",
        "translation": "Reframe \"turning discarded flowers into gifts for strangers\" as \"turning an overlooked, ordinary moment into a genuine connection with a stranger\" — same resourceful-overlooked-detail + recipient's-genuine-joy framing.",
        "ca_title": "I Turned An Ordinary Moment Into A Real Connection With A Stranger",
        "ca_thumbnail": "A real outdoor scene, a woman smiling genuinely mid-conversation with the creator, natural daylight, candid unposed framing, no text overlay.",
        "notes": "Centering the thumbnail on the recipient's genuine reaction, not the giver's action, is a reusable device across the whole kindness-documentary genre.",
        "status": "Not Adapted",
    },
    {
        "title": "Real Life Superheroes Caught Saving People On Camera",
        "channel": "FAST - Instant Karma",
        "url": "https://www.youtube.com/watch?v=TKK9nzN6eiU",
        "niche": "Hero/Rescue Compilation",
        "views": "767,455 (41.4K subscribers — 18.5x its subscriber count in views, a genuine breakout)",
        "views_num": 767455,
        "subscribers": 41400,
        "score": "18.5x subs",
        "pattern": "A compilation format that labels the specific threat directly in bold text, letting the viewer instantly understand the stakes of a real intervention moment.",
        "trigger": "Relief/admiration from watching someone step in during a genuinely dangerous moment + the specificity of a named threat making the danger concrete rather than abstract.",
        "thumbnail": "A real bodycam/security-style scene, an officer running toward a child, a bold red \"KIDNAPPER\" label with an arrow pointing at the fleeing figure, daylight residential setting.",
        "formula": "\"Real Life [Heroic Archetype] Caught [Specific Heroic Action] On Camera\"",
        "why": "Naming the exact danger in bold text, rather than a vague label, makes the stakes instantly legible, and \"real life\" plus \"caught on camera\" promises unstaged, verifiable footage.",
        "translation": "Reframe \"real people caught saving others from danger\" as \"a guy caught stepping in for a woman in an uncomfortable/unsafe situation\" — same named-specific-danger + \"caught on camera\" authenticity framing.",
        "ca_title": "Real Guy Caught Stepping In When She Needed Him On Camera",
        "ca_thumbnail": "A real street scene, the creator visibly stepping toward a woman in a tense moment, a bold red label naming the specific situation, daylight setting.",
        "notes": "Naming the exact danger/threat in bold text is a reusable specificity device already proven elsewhere in this file (RoadGoneWrongTV's \"BRAKE CHECKER\").",
        "status": "Not Adapted",
    },
    {
        "title": "The Most Extreme Weight Loss Journey Ever",
        "channel": "History By Humans",
        "url": "https://www.youtube.com/watch?v=ubi2OWlQ7rU",
        "niche": "Transformation Documentary (Talking Head)",
        "views": "1,220,449 (11.4K subscribers — 1.2M views, 107.1x its subscriber count in views, and 27.7x its own channel average, a triple-qualifying breakout)",
        "views_num": 1220449,
        "subscribers": 11400,
        "score": "1.2M views, 107.1x subs, 27.7x avg",
        "pattern": "A woman recounting her own transformation directly to camera with an exaggerated, animated expression that itself functions as the hook, rather than showing before/after photos.",
        "trigger": "Curiosity built by the speaker's own visibly heightened reaction (something clearly dramatic is being described) + personal, first-person authenticity of direct-to-camera storytelling.",
        "thumbnail": "A woman speaking directly to camera with a wide-eyed, animated expression mid-sentence, a partial caption (\"...AND WATCH\") cut off to build curiosity, cozy indoor lighting, simple unproduced framing.",
        "formula": "\"The Most Extreme [Transformation Type] Journey Ever\"",
        "why": "Letting the speaker's own exaggerated real-time reaction sell the drama, instead of a static before/after image, makes the thumbnail feel like a genuine, unscripted moment mid-story, and clearing all three outlier signals at once on an 11K-subscriber channel is a rare, especially strong confirmation.",
        "translation": "Reframe \"the most extreme weight loss journey ever\" as \"the most extreme confidence transformation journey ever,\" told the same animated, direct-to-camera way.",
        "ca_title": "The Most Extreme Confidence Transformation Journey Ever",
        "ca_thumbnail": "A woman speaking directly to camera with a wide-eyed, animated expression mid-sentence, a partial caption cut off to build curiosity, cozy natural indoor lighting.",
        "notes": "A rare triple-signal outlier (absolute views + subscriber multiplier + channel-average multiplier all at once) — the strongest possible confirmation in this batch that the packaging, not luck, drove the reach.",
        "status": "Not Adapted",
    },
]


def main() -> None:
    client = build_google_sheets_client()
    if not client:
        print("No Google Sheets output was created.")
        return

    if GOOGLE_SPREADSHEET_ID:
        spreadsheet = client.open_by_key(GOOGLE_SPREADSHEET_ID)
    else:
        spreadsheet = client.create("YouTube Outlier Tracker")

    try:
        worksheet = spreadsheet.worksheet(SHEET_NAME)
    except gspread.exceptions.WorksheetNotFound:
        worksheet = spreadsheet.add_worksheet(title=SHEET_NAME, rows=100, cols=20)

    worksheet.clear()
    worksheet.append_row(HEADERS)

    values = [
        [
            row["title"], row["channel"], row["url"], row["niche"], row["views"], row.get("subscribers") or "", row["score"],
            row["pattern"], row["trigger"], row["thumbnail"], row["formula"], row["why"],
            row["translation"], row["ca_title"], row["ca_thumbnail"], row["notes"], row["status"],
        ]
        for row in SWIPE_FILE
    ]
    worksheet.append_rows(values, value_input_option="USER_ENTERED")
    worksheet.set_basic_filter()

    print(f"Wrote {len(SWIPE_FILE)} swipe file entries to {spreadsheet.url} ({SHEET_NAME})")


if __name__ == "__main__":
    main()
