"""One-off writer for the "General Long Form Outliers" output
(outlier-tracking/general-long-form/data.json): a curated swipe file of viral YouTube
packaging (title + thumbnail psychology) from outside the cold-approach niche, each
translated into a cold-approach-ready title and thumbnail concept.

Entries here must be real, statistically verified outliers found by
general_outlier_finder.py (run via GitHub Actions, since computing view/subscriber/
channel-average multipliers needs live channel stats from the YouTube API) — and must
be genuine RELATIVE outliers, not just big channels doing normal big-channel numbers.
Concretely: a video only qualifies on raw views (1M+) if the channel has under 100K
subscribers, where 1M+ views is itself remarkable. Channels at or above 100K subscribers
must qualify via a relative signal instead — 5x+ subscriber breakout or 20x+ channel-
average breakout — since 1M views means nothing for a channel whose average video
already clears that. (An earlier batch of entries let big channels like MrBeast qualify
purely on absolute views; those got removed once this rule was tightened.)

That finder script only surfaces candidates; picking which ones cleanly translate into
a cold-approach idea — both the title AND the thumbnail concept — and writing the
analysis below is a manual step. Cold-approach thumbnail concepts should put a woman
front and center as the visual star (per the channel's packaging convention), regardless
of whether the original video's thumbnail did. Entries must also be in English — a
language filter (is_english_title in common.py) now screens the finder's
output, but it only catches non-Latin scripts, not other Latin-script languages, so
still verify by eye. This file is not a live API pull itself — run it manually whenever
new entries are added.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from common import write_rows_to_json

SWIPE_FILE = [
    {
        "title": "Reuniting With Ferran After 7 Years Royalty Family Surprise",
        "channel": "Real Princess Sophia",
        "url": "https://www.youtube.com/watch?v=ZOvFdjafmVY",
        "published_at": "2026-08-02",
        "duration": "6:05",
        "niche": "Emotional Reunion Surprise (Family)",
        "views": "3,761,183 views (189,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 3761183,
        "subscribers": 189000,
        "score": "3,761,183 views",
        "pattern": "A specific, named long-gap reunion with a real named person, framed as a family-brand surprise tying into the channel's ongoing family-brand identity.",
        "trigger": "Anticipation heightened by an unusually long, specific time gap, plus brand-recognition for existing viewers of the family's ongoing story.",
        "thumbnail": "A real embrace/reunion moment as the hero image, the specific year-count and name overlaid.",
        "formula": "\"Reuniting With [Named Person] After [Specific Years] [Brand Descriptor] Surprise\"",
        "why": "A specific, unusually long time gap makes the reunion feel more remarkable and researched than \"years later,\" and tying it to an ongoing family brand gives existing viewers a reason to click beyond the reunion alone.",
        "translation": "Reframe \"reuniting with a named family member after a specific long gap\" as \"running into someone from years ago during a real approach\" -- same specific-long-time-gap device applied to an unexpected real-world reconnection.",
        "ca_title": "I Ran Into My High School Crush After 7 Years -- Her Reaction",
        "ca_thumbnail": "A real candid embrace/reaction moment as the hero image, the specific year-count overlaid, warm natural lighting.",
        "notes": "An oddly specific number (7 years, not \"years\") is a small, reusable device for making a claim feel more real and less generic.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "BILLIONAIRE TEST | Kind Girl Risk Her Job To Defend Old Woman Been Humiliated | FULL MOVIE",
        "channel": "VOWFALL Stories",
        "url": "https://www.youtube.com/watch?v=GGLGuU-_UwI",
        "published_at": "2026-07-18",
        "duration": "1:23:08",
        "niche": "Disguise/Status Test (Reversed Gender)",
        "views": "1,184,839 views (65,300 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1184839,
        "subscribers": 65300,
        "score": "1,184,839 views",
        "pattern": "A disguised-status test where the person being tested for kindness is a woman, and the risk she takes raises the stakes of her kindness.",
        "trigger": "Admiration for someone risking something real to defend a vulnerable stranger, plus curiosity about the disguised billionaire's eventual reveal and reaction.",
        "thumbnail": "A real/staged workplace-adjacent confrontation, the kind subject visibly standing up for someone, bold status-test label overlaid.",
        "formula": "\"[Disguised Status] TEST | [Subject] Risk Her [Real Stake] To Defend [Vulnerable Person] Been [Wronged]\"",
        "why": "Making the stake concrete and real turns an abstract kindness test into something with genuine, relatable personal cost for the person being tested.",
        "translation": "Reframe \"a disguised billionaire tests a kind girl who risks her job\" as \"a woman risks social awkwardness/judgment from her friends to genuinely engage during an approach, and the reveal of who the guy really is\" -- same real-personal-stake-plus-disguised-reveal structure.",
        "ca_title": "APPROACH TEST | She Risked Her Friends Judging Her To Actually Talk To Me",
        "ca_thumbnail": "A real street/social scene, a woman visibly choosing to engage despite others nearby, bold label text overlaid matching the original's format.",
        "notes": "Naming a real, specific personal cost, not just \"she was kind,\" is what makes the kindness in these tests feel earned rather than trivial.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "I STOLE a Soft Drink From a Provision Store as a Homeless Mad Man…Her Reaction Left Me in Tears! 😭❤️",
        "channel": "Tunika",
        "url": "https://www.youtube.com/watch?v=DQiW2nrM1Bo",
        "published_at": "2026-07-28",
        "duration": "24:00",
        "niche": "Disguise/Status Test (Provocation)",
        "views": "1,018,767 views (83,500 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1018767,
        "subscribers": 83500,
        "score": "1,018,767 views",
        "pattern": "The disguised tester actively does something mildly provocative rather than passively waiting to be helped, making the \"test\" more of an active social experiment.",
        "trigger": "Curiosity about how a store owner reacts to a disguised low-status person doing something wrong, rather than something neutral, raising the stakes of what \"her reaction\" could mean.",
        "thumbnail": "A real disguised low-status appearance mid-provocative-act, the store setting visible, minimal text.",
        "formula": "\"I STOLE a [Small Item] From a [Real Setting] as a [Disguised Status]...Her [Reaction]\"",
        "why": "Having the disguised subject do something actively provocative creates real uncertainty about the outcome, since the tester isn't purely sympathetic, which raises the stakes of what the reveal could show.",
        "translation": "Reframe \"disguised as homeless, stole a drink, her reaction\" as \"did something a little bold/provocative during a disguised-status approach, and her real reaction\" -- same active-provocation-raises-stakes device.",
        "ca_title": "I Said Something Bold Disguised As The Least Impressive Guy There... Her Reaction",
        "ca_thumbnail": "A real street/venue scene, creator in an unassuming disguised presentation mid-bold-moment, a woman's genuine reaction visible.",
        "notes": "An active provocation, not passive waiting, creates real uncertainty about the outcome, which is what separates this from a purely predictable kindness test.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "[Full] The Day They Hurt Her Daughter, the Mafia Queen Returned🔥",
        "channel": "Queen's Reel",
        "url": "https://www.youtube.com/watch?v=FRIFURFhKKo",
        "published_at": "2026-07-21",
        "duration": "1:40:09",
        "niche": "Status-Reveal/Betrayal (Wealth Twist)",
        "views": "3,726,920 views (53,800 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 3726920,
        "subscribers": 53800,
        "score": "3,726,920 views",
        "pattern": "A betrayal immediately undercut by a huge status reveal the wrongdoer forgot about, the title itself delivering the entire twist upfront.",
        "trigger": "Satisfaction from watching a wrongdoer's own forgetfulness be their downfall, combined with a huge, specific status contrast that recontextualizes the whole \"betrayal.\"",
        "thumbnail": "A composed, confident real/staged shot of the wronged subject, a luxury detail visible, minimal text stating the forgotten status.",
        "formula": "\"My [Relation] Gave [Their Affair Partner] My [Possession]--[He/She] Forgot I'm the [Status Reveal]!\"",
        "why": "Delivering the twist directly in the title works because the twist itself is the hook, knowing \"she's secretly a billionaire\" upfront makes the viewer want to see exactly how that plays out, rather than being surprised by it.",
        "translation": "Reframe \"gave away my car, forgot I'm a billionaire\" as \"dismissed me during an approach, had no idea who I actually was\" -- same title-delivers-the-twist-upfront status-reveal structure.",
        "ca_title": "She Turned Me Down At The Bar--She Had No Idea I Own The Place",
        "ca_thumbnail": "A real, composed, confident shot of the creator in an upscale real setting, minimal text stating the forgotten status.",
        "notes": "Putting the twist in the title itself, rather than saving it, is a legitimate, different strategy from withheld-twist titles used elsewhere, worth testing both approaches.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "CONFRONTING NASIA ELIZ AFTER CHEATING WITH MY BESTFRIEND | LIFE FORCE SKATE AKO TO CHEAT AKO",
        "channel": "Jd Ramos",
        "url": "https://www.youtube.com/watch?v=PYGGDbm70Jo",
        "published_at": "2026-09-04",
        "duration": "33:34",
        "niche": "Real Confrontation (Named, Direct)",
        "views": "621,820 views (49,300 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 621820,
        "subscribers": 49300,
        "score": "621,820 views",
        "pattern": "A direct, real, named-person confrontation over infidelity, using ALL CAPS and real names to signal this is an actual documented personal event, not a dramatization.",
        "trigger": "Voyeuristic pull of a real, raw, unscripted confrontation between real named people, heightened by the emotional stakes of infidelity with a close friend specifically.",
        "thumbnail": "A real, raw close-up of the confrontation moment, genuine emotional expressions visible, minimal graphic design.",
        "formula": "\"CONFRONTING [Real Name] AFTER CHEATING WITH MY [Close Relation]\"",
        "why": "Using real names and ALL CAPS signals authenticity and stakes simultaneously, this reads as a genuine personal documentation, not content manufactured for views, which is precisely what makes it compelling.",
        "translation": "Reframe \"confronting a real named person after being cheated on\" as \"a real, raw confrontation moment during an approach when something unexpected comes out\" -- same raw-real-names-ALL-CAPS authenticity device.",
        "ca_title": "CONFRONTING HER ABOUT WHAT SHE ACTUALLY SAID BEHIND MY BACK",
        "ca_thumbnail": "A real, raw close-up mid-confrontation, genuine emotional expressions visible, minimal graphic design matching the original's low-production authenticity.",
        "notes": "Real names and raw, minimal-production framing are what sell the authenticity here, over-producing this format would undercut it immediately.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "25 Instant Karma Moments Caught On Camera | Best Of The Week #28",
        "channel": "KARMA-HP",
        "url": "https://www.youtube.com/watch?v=JAJVbdKm8bA",
        "published_at": "2026-09-04",
        "duration": "21:26",
        "niche": "Instant Karma Compilation (Traffic/Public)",
        "views": "735,356 views (2,440 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 735356,
        "subscribers": 2440,
        "score": "735,356 views",
        "pattern": "A numbered countdown compilation format aggregating many short real clips of rude/entitled people getting immediate comeuppance, with a repeatable weekly branded series title.",
        "trigger": "Justice/karma satisfaction stacked across many quick payoffs instead of one, plus the reliability of a recurring branded series building return viewership.",
        "thumbnail": "A grid/collage-style thumbnail showing multiple frozen \"gotcha\" moments at once, bold red \"INSTANT KARMA\" text banner, numbered \"#28\" episode marker.",
        "formula": "\"[Count] Instant Karma Moments Caught On Camera | Best Of The Week #[N]\"",
        "why": "Compilations remove the risk of any single clip underperforming, a weak clip is buried among strong ones, and a numbered weekly series trains an audience to return every week the way a TV show does.",
        "translation": "Reframe \"many strangers getting karma\" as \"many guys' approaches failing or succeeding in quick cuts\" -- a rapid-fire compilation format showing several real interaction outcomes back to back, branded as a recurring weekly series.",
        "ca_title": "25 Approach Reactions Caught On Camera | Best Of The Week #1",
        "ca_thumbnail": "A grid of several small frozen reaction shots from different real approaches, bold red \"HER REACTION\" banner, numbered episode marker matching a weekly series identity.",
        "notes": "The branded weekly-numbered-series device is the real takeaway here -- it's a format that could become the channel's own recurring show rather than one-off videos.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "3 Couples with 3 Breakup-Level Confessions | Truth or Drink | Cut",
        "channel": "Cut",
        "url": "https://www.youtube.com/watch?v=SapryT8caj8",
        "published_at": "2026-08-22",
        "duration": "19:09",
        "niche": "Real Couples/Confessions (Direct Dating Niche)",
        "views": "1,743,889 views (12,400,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1743889,
        "subscribers": 12400000,
        "score": "1,743,889 views",
        "pattern": "Real couples answer increasingly vulnerable relationship questions on camera, with \"truth or drink\" as a game-show structure that gives permission for raw honesty.",
        "trigger": "Voyeuristic curiosity about real couples' private vulnerabilities, heightened by the drinking-game structure implying anything might get said.",
        "thumbnail": "A real couple's genuine tense/vulnerable expression mid-confession, minimal branded text.",
        "formula": "\"[Count] Couples with [Severity Level] Confessions | Truth or Drink\"",
        "why": "A game-show framing gives real couples social permission to say things they normally wouldn't on camera, and grading confessions by severity level sets clear stakes before it plays.",
        "translation": "Already squarely in-niche -- real couples' game-format vulnerable confessions is directly relevant dating content; the reusable device is the graded-severity game structure that licenses raw honesty.",
        "ca_title": "3 Couples Answer Breakup-Level Questions | Truth or Drink",
        "ca_thumbnail": "A real couple's genuine tense expression mid-confession, minimal branded text matching a recognizable game-show format.",
        "notes": "One of the most directly translatable entries in this batch -- this format already IS dating content, just needs your own branded execution.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "Finally I Proposed Nega ❤️ With a Guinness Record  | Samsameer_insta",
        "channel": "Samsameer_insta",
        "url": "https://www.youtube.com/watch?v=X_83QO-8BX8",
        "published_at": "2026-08-23",
        "duration": "1:03:00",
        "niche": "Proposal Reaction (Extreme Scale)",
        "views": "2,333,378 views (1,280,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 2333378,
        "subscribers": 1280000,
        "score": "2,333,378 views",
        "pattern": "A real proposal executed at a record-breaking extreme scale, the specific verifiable record claim raising the stakes of an otherwise-common proposal format.",
        "trigger": "Awe at an extreme, specific, verifiable scale claim applied to a universally understood romantic moment.",
        "thumbnail": "The real proposal moment at its extreme scale, her genuine reaction visible, record claim overlaid.",
        "formula": "\"Finally I Proposed [Name] With a Guinness Record\"",
        "why": "A verifiable, named record claim gives an otherwise-common proposal format a concrete, headline-worthy hook.",
        "translation": "Reframe \"proposing with a record-breaking gesture\" as \"a real approach or gesture taken to an extreme, verifiable scale\" -- same specific-verifiable-extreme-claim device applied to a bold romantic gesture.",
        "ca_title": "I Asked Her Out With The World's Largest Bouquet",
        "ca_thumbnail": "A real extreme-scale gesture moment, her genuine reaction visible, record claim overlaid matching the original's format.",
        "notes": "A specific, named, checkable record, not a vague superlative, is what makes an extreme claim feel real rather than exaggerated.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "She finally admitted she's a fraud",
        "channel": "Sydney Watson",
        "url": "https://www.youtube.com/watch?v=IGhFgAei-FI",
        "published_at": "2026-09-09",
        "duration": "25:49",
        "niche": "Confrontation/Reveal (Commentary)",
        "views": "2,028,170 views (1,170,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 2028170,
        "subscribers": 1170000,
        "score": "2,028,170 views",
        "pattern": "A real, named public figure's own admission used as the entire hook, the creator's commentary framing an opponent's words as a self-own.",
        "trigger": "Satisfaction from watching someone's own words become the evidence against them, framed as a long-awaited vindication.",
        "thumbnail": "A real split-screen or reaction shot showing the subject's own admission, minimal text.",
        "formula": "\"[Subject] Finally Admitted [Damaging Truth]\"",
        "why": "\"Finally admitted\" implies this was long-suspected and now proven in the subject's own words, which is more satisfying than an outside accusation because it's self-incriminating.",
        "translation": "Reframe \"she finally admitted she's a fraud\" as \"she finally admitted what she actually thought during the approach\" -- same self-admission-as-vindication device, applied to a genuine reveal moment.",
        "ca_title": "She Finally Admitted She Was Actually Interested The Whole Time",
        "ca_thumbnail": "A real candid reaction shot capturing the admission moment, minimal text matching the original's commentary style.",
        "notes": "Using someone's own words as the proof, not the creator's claim, is what makes this reveal format land as credible rather than one-sided.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "MERYLL SORIANO & DAD, WILLIE REVILLAME: The Journey To Forgiveness & Healing | Karen Davila",
        "channel": "Karen Davila",
        "url": "https://www.youtube.com/watch?v=md_tZjYfJxE",
        "published_at": "2026-08-27",
        "duration": "27:54",
        "niche": "Redemption/Forgiveness (Real Interview)",
        "views": "1,100,937 views (2,740,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1100937,
        "subscribers": 2740000,
        "score": "1,100,937 views",
        "pattern": "A real, sit-down interview format documenting two real named people's actual journey toward reconciliation, credibility-driven by a recognized journalist host.",
        "trigger": "Emotional investment in a real, ongoing reconciliation between real people, grounded by the credibility of a known interview format/host.",
        "thumbnail": "The two real subjects together, a warm but visibly emotional real moment, minimal text naming the theme.",
        "formula": "\"[Named Subject] & [Named Subject]: The Journey To [Reconciliation Theme]\"",
        "why": "A real interview format lends journalistic credibility to an emotional story, and naming both real people plus the specific theme sets clear, grounded expectations.",
        "translation": "Reframe \"a real interview documenting two people's journey to forgiveness\" as \"a real, sit-down conversation revisiting an old rejection or falling-out and how it resolved\" -- same credible-interview-format-plus-named-real-people device.",
        "ca_title": "We Sat Down Years Later To Talk About Why She Rejected Me",
        "ca_thumbnail": "The creator and a woman together in a real sit-down setting, a warm but visibly reflective moment, minimal text naming the theme.",
        "notes": "The interview format itself, not just the story, lends credibility -- a calm, sit-down conversation reads as more serious/real than a street clip.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "Confronting Angry Paris Scammers!",
        "channel": "Zachcray",
        "url": "https://www.youtube.com/watch?v=6I76KruQXzE",
        "published_at": "2026-09-02",
        "duration": "14:55",
        "niche": "Confrontation (Named Real Location)",
        "views": "1,874,462 views (679,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1874462,
        "subscribers": 679000,
        "score": "1,874,462 views",
        "pattern": "Real confrontation content grounded in a specific, named real city, adding travel-content appeal and local specificity to the confrontation genre.",
        "trigger": "Curiosity about a specific, real, named location's particular scam culture, plus travel-content appeal of seeing a real famous city.",
        "thumbnail": "A real in-person confrontation in a recognizable city setting, the creator's genuine intense expression.",
        "formula": "\"Confronting Angry [Wrongdoer Type] in [Named Real City]!\"",
        "why": "Naming a specific real city adds travel-content appeal and local specificity that makes the claim feel grounded and researched.",
        "translation": "Reframe \"confronting scammers in a named real city\" as \"approaching women in a specific, named real city while traveling\" -- same named-real-location specificity device.",
        "ca_title": "Approaching Women In Paris For The First Time",
        "ca_thumbnail": "A real recognizable city backdrop, creator mid-approach with a woman, natural daylight matching a travel-vlog feel.",
        "notes": "Naming a real, specific, recognizable location is a reusable device for adding grounded travel appeal to almost any format in this file.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "Scammer CRIES After I HACK Her Live Webcam!",
        "channel": "NanoBaiter",
        "url": "https://www.youtube.com/watch?v=KqkJF9oVmoA",
        "published_at": "2026-07-20",
        "duration": "17:25",
        "niche": "Scam-Baiting/Confrontation (Extreme Reveal)",
        "views": "8,816,745 views (1,280,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 8816745,
        "subscribers": 1280000,
        "score": "8,816,745 views",
        "pattern": "A confrontation escalated to an extreme technical reveal, with the specific emotional reaction stated as the payoff.",
        "trigger": "Satisfaction of an extreme, technically impressive turnaround against a wrongdoer, with a specific, strong emotional reaction promised upfront.",
        "thumbnail": "A real webcam-captured reaction shot showing genuine distress, bold text naming the emotion.",
        "formula": "\"Scammer CRIES After I HACK Her Live Webcam!\"",
        "why": "Naming the specific emotional reaction rather than a vague \"reacts\" sets a concrete expectation, and the extreme technical method raises the stakes beyond a normal confrontation.",
        "translation": "Reframe \"hacked her webcam, she cried\" as \"did something unexpectedly bold during an approach that led to a genuinely strong, specific emotional reaction\" -- same extreme-method-plus-named-emotional-reaction device.",
        "ca_title": "She CRIED After I Said This During Our Conversation",
        "ca_thumbnail": "A real close-up capturing a genuine strong emotional reaction, bold text naming the specific emotion, natural lighting.",
        "notes": "Naming the exact emotional reaction in the title, not \"reacting,\" is a small but effective specificity upgrade over vaguer emotional promises.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "Telling My Twin I’m Pregnant FULL REACTION - Merrell Twins",
        "channel": "merrelltwins",
        "url": "https://www.youtube.com/watch?v=xJocP_9Q9RY",
        "published_at": "2026-09-08",
        "duration": "15:31",
        "niche": "Relationship Milestone Reveal (Family Reaction)",
        "views": "1,932,603 views (6,540,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1932603,
        "subscribers": 6540000,
        "score": "1,932,603 views",
        "pattern": "A real, unedited full-length reaction to major personal news shared with someone very close, \"FULL REACTION\" signaling nothing was cut for effect.",
        "trigger": "Curiosity about a genuine, unfiltered reaction to major life news, with \"full reaction\" promising authenticity.",
        "thumbnail": "A real close-up capturing the exact moment of reaction, genuine shocked/emotional expression.",
        "formula": "\"Telling My [Close Relation] I'm [Major News] FULL REACTION\"",
        "why": "\"Full reaction\" signals the footage is complete and unedited, which builds trust that the reaction shown is genuinely spontaneous.",
        "translation": "Reframe \"telling my twin I'm pregnant, full reaction\" as \"telling someone close to me about a real approach/dating outcome, and their full, unfiltered reaction\" -- same complete-unedited-reaction-promise device.",
        "ca_title": "Telling My Best Friend I Got Her Number FULL REACTION",
        "ca_thumbnail": "A real close-up capturing a genuine surprised/excited reaction, natural lighting, minimal text.",
        "notes": "Explicitly labeling a reaction as \"full,\" not a highlight, is a cheap trust signal worth using whenever the footage genuinely is complete.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "We surprised Tom Holland and Zendaya with AMAZING Titanium Flashmob at Spider-Man fan event 😍",
        "channel": "Julien Cohen",
        "url": "https://www.youtube.com/watch?v=aMQOcbZ6Ls4",
        "published_at": "2026-07-29",
        "duration": "3:20",
        "niche": "Celebrity Surprise (Flashmob Gimmick)",
        "views": "6,144,764 views (7,980,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 6144764,
        "subscribers": 7980000,
        "score": "6,144,764 views",
        "pattern": "A surprise flashmob performance for real, named A-list celebrities, borrowing maximum name recognition to elevate an otherwise-common street-performance format.",
        "trigger": "Curiosity about how two of the most recognizable celebrities in the world would react to an elaborate real surprise, plus the specific memorable song choice.",
        "thumbnail": "A real moment featuring the recognizable celebrities' genuine reaction, the performance visible around them.",
        "formula": "\"We surprised [Named A-List Celebrities] with AMAZING [Specific Performance] at [Real Setting]\"",
        "why": "Using maximum-recognition real names elevates an otherwise-common flashmob format into something with built-in mass appeal, since millions already care about how these specific people react.",
        "translation": "Reframe \"surprising A-list celebrities with a flashmob\" as \"surprising someone with an elaborate, memorable real gesture in a real public setting\" -- same elaborate-real-gesture-plus-genuine-reaction device, scaled to a realistic version.",
        "ca_title": "I Surprised Her With A Flash Mob In The Middle Of The Street",
        "ca_thumbnail": "A real public setting, a woman's genuine surprised reaction as the focal point, the gesture visible around her.",
        "notes": "The elaborate-real-gesture-plus-genuine-reaction structure works at any scale -- the celebrity names here are what make it shareable, but the mechanic works with ordinary real reactions too.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "Reunited With My Brother After 10 Years (FACE REVEAL)",
        "channel": "Regina & Daniela",
        "url": "https://www.youtube.com/watch?v=5_R6o3wH6_Q",
        "published_at": "2026-08-05",
        "duration": "14:57",
        "niche": "Reunion Surprise (Compounded With Format Gimmick)",
        "views": "1,241,989 views (1,210,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1241989,
        "subscribers": 1210000,
        "score": "1,241,989 views",
        "pattern": "Compounds a long-gap sibling reunion with a \"face reveal,\" a separate, channel-specific content gimmick, doubling the reasons to watch.",
        "trigger": "Anticipation from two separate payoffs promised at once, the reunion itself AND the channel's own long-teased face reveal.",
        "thumbnail": "A real reunion embrace, faces visible for the first time on the channel, minimal text.",
        "formula": "\"Reunited With My [Family Member] After [Specific Years] (FACE REVEAL)\"",
        "why": "Stacking a personal-story payoff with a separate, pre-existing channel anticipation device pulls in two different audiences' reasons to click at once.",
        "translation": "Reframe \"reunion plus a teased face reveal\" as \"a real reunion moment that also resolves a separate piece of anticipation you've built with your own audience\" -- same double-payoff-stacking device, adaptable to whatever anticipation a channel has already built.",
        "ca_title": "I Ran Into My Ex After 10 Years (FIRST TIME SHOWING MY FACE)",
        "ca_thumbnail": "A real candid reunion moment, the creator's face shown clearly for the first time on camera, natural lighting, minimal text.",
        "notes": "This device only works if there's a genuine separate anticipation already built with your audience -- don't fabricate a \"reveal\" that isn't real.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "Marumagal Gave Us a HUGE Surprise! 😍🚗❤️ | New Car Reveal | @Mrrockyy",
        "channel": "Latto’s Kitchen",
        "url": "https://www.youtube.com/watch?v=u_Hvn_QidZc",
        "published_at": "2026-08-19",
        "duration": "8:08",
        "niche": "Family Surprise Reveal (Material Gift)",
        "views": "1,625,889 views (807,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1625889,
        "subscribers": 807000,
        "score": "1,625,889 views",
        "pattern": "A real family surprise built around revealing a significant material gift, the emotional context elevating what could otherwise be a purely materialistic reveal.",
        "trigger": "Warmth from watching a loved one receive an unexpected, significant gift, grounded by the real family relationship giving it emotional weight beyond the object itself.",
        "thumbnail": "A real reaction moment at the reveal, the gift visible, genuine joyful expression.",
        "formula": "\"[Family Member] Gave Us a HUGE Surprise! | [Specific Gift] Reveal\"",
        "why": "Framing a significant material reveal through a real family relationship gives it emotional stakes that a pure purchase-flex video wouldn't have.",
        "translation": "Reframe \"family surprises us with a new car\" as \"someone surprises a person they're interested in with a thoughtful, significant real gesture, and the genuine reaction\" -- same relationship-grounded-significant-reveal device.",
        "ca_title": "I Surprised Her With Something She's Wanted For Years -- Her Reaction",
        "ca_thumbnail": "A real reaction moment at the reveal, the gift/gesture visible, genuine joyful expression, warm natural lighting.",
        "notes": "The relationship context, not the object's value alone, is what makes a material-gift reveal feel warm rather than showy -- keep that framing front and center.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "A New Level Of Entitlement | Reading Reddit Stories",
        "channel": "Smosh Pit",
        "url": "https://www.youtube.com/watch?v=cgD5eMHNYRI",
        "published_at": "2026-07-11",
        "duration": "1:10:04",
        "niche": "Reaction/Story-Reading (Real Cast)",
        "views": "3,128,824 views (9,640,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 3128824,
        "subscribers": 9640000,
        "score": "3,128,824 views",
        "pattern": "A recognizable real cast reacts live to real user-submitted stories, the specific labeled theme (entitlement) setting a clear emotional lens before any story is read.",
        "trigger": "Relatable frustration/schadenfreude toward a named universal social behavior (entitlement), amplified by watching real, known personalities react genuinely as they read.",
        "thumbnail": "The real cast's genuine exaggerated reaction mid-read, bold text naming the specific behavior theme.",
        "formula": "\"A New Level Of [Named Social Behavior] | Reading [Platform] Stories\"",
        "why": "Naming a specific, recognizable social behavior as the theme (rather than \"crazy stories\") gives viewers an instant emotional frame before a single story is read, and real hosts' live reactions carry the format rather than the stories alone.",
        "translation": "Reframe \"reacting to entitled-people stories\" as \"reacting live to real, submitted dating/approach horror stories with a named behavioral theme\" -- same labeled-theme-plus-live-real-reaction device.",
        "ca_title": "A New Level Of Rejection | Reading Your Worst Approach Stories",
        "ca_thumbnail": "The creator's genuine exaggerated reaction mid-read, bold text naming the specific theme, casual studio lighting.",
        "notes": "Naming the specific behavioral theme up front, not just \"stories,\" is what gives an otherwise-generic reaction format a clear emotional hook before it starts.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "We Lived in our Pool for 24 Hours!",
        "channel": "The Anazala Family ",
        "url": "https://www.youtube.com/watch?v=C7B23r2pYFU",
        "duration": "33:32",
        "published_at": "2026-07-18",
        "niche": "family vlog / last-to-leave challenge",
        "views": "19,977,587 views in the last 90 days (14,000,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 19977587,
        "subscribers": 14000000,
        "score": "19,977,587 views",
        "pattern": "Splits domestic novelty (living in a pool) with genuine candid reactions — woman cooking mid-task while man lounges — the contrast of 'normal life' happening somewhere absurd drives curiosity.",
        "trigger": "Novelty + relatable domestic comedy: viewers want to see how normal routines survive in a ridiculous setting.",
        "thumbnail": "Woman in foreground stirring a pot of food while sitting on a floating tray in a pool at night with string lights, man lounging on a floating chair behind her with a laptop, another person visible in the water.",
        "formula": "We [Did Normal Life Activity] In [Unusual Location] For 24 Hours!",
        "why": "Combining a mundane task with an absurd location creates instant contrast-driven curiosity, and a genuine candid facial reaction sells authenticity.",
        "translation": "Reframe as an extended date dare where a couple must do everyday activities under a bizarre restriction, using her candid in-the-moment reaction as the hook.",
        "ca_title": "We Lived On One Date For 24 Hours (She Couldn't Leave)",
        "ca_thumbnail": "Woman cooking on a picnic blanket floating in a pool at night looking amused, guy relaxing behind her on his phone, warm string-light ambiance.",
        "notes": "Needs a genuinely candid (not posed) reaction shot to hit the same authenticity that makes the original work.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "LAST TO LEAVE BACKROOMS!",
        "channel": "Stokes Twins",
        "url": "https://www.youtube.com/watch?v=lFOw4ZuxK4I",
        "duration": "28:21",
        "published_at": "2026-08-15",
        "niche": "horror-comedy last-to-leave challenge",
        "views": "18,991,647 views in the last 90 days (147,000,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 18991647,
        "subscribers": 147000000,
        "score": "18,991,647 views",
        "pattern": "Both a man and woman crawl toward camera with matching exaggerated terrified expressions while blurred costumed 'monsters' loom behind them, creating instant 'what's chasing them' curiosity.",
        "trigger": "Shared fear/anticipation — synced exaggerated reactions from both people amplify the perceived stakes and make viewers want the payoff.",
        "thumbnail": "A man and a pink-haired woman both reaching toward the camera with wide-eyed terrified expressions on a yellow patterned floor, two costumed horror characters blurred in the background, red handprints and 'RUN' text.",
        "formula": "LAST TO [REACT/RUN] WINS [PRIZE]! (SHE'S TERRIFIED)",
        "why": "Mirrored exaggerated expressions on two people create a 'we're in this together' bond while promising an entertaining reveal.",
        "translation": "Reframe as a bold-move reaction challenge where a guy's dare causes a girl's shocked/laughing reaction, keeping the tone playful rather than scary.",
        "ca_title": "I Made Her Scream In Public (Last To Break Character Wins)",
        "ca_thumbnail": "Man and woman both reaching toward the camera with shocked, laughing expressions, blurred crowd behind them, bold neon text overlay.",
        "notes": "Keep tone comedic, not genuinely frightening, so it still reads as playful flirting content rather than horror.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "Last To Leave Cybertruck Keeps It!",
        "channel": "Stay Wild",
        "url": "https://www.youtube.com/watch?v=lyXPGSMOV8Y",
        "duration": "32:09",
        "published_at": "2026-08-23",
        "niche": "last-to-leave vehicle challenge",
        "views": "18,424,076 views in the last 90 days (25,500,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 18424076,
        "subscribers": 25500000,
        "score": "18,424,076 views",
        "pattern": "An absurd confined space (a mini-pool in a truck bed) creates a 'what is happening here' visual hook, with the man smugly relaxed front-and-center and a woman visible behind him as social proof of the shared challenge.",
        "trigger": "Curiosity about an improbable scenario, reinforced by visible proximity between two people enduring it together.",
        "thumbnail": "A young man leans out of a small pool built into a Cybertruck bed smiling confidently, a blonde woman lies in the truck bed behind him, road and a Fortnite screen visible.",
        "formula": "Last To Leave The [Absurd Confined Space] Keeps It!",
        "why": "The novel confined-space visual is inherently scroll-stopping, and pairing both genders in the frame signals a shared date-like dynamic.",
        "translation": "Turn into a proximity-based flirting dare — 'last to leave the car wins a date' — where forced closeness builds visible tension.",
        "ca_title": "Last To Leave The Car Wins A Date With Her",
        "ca_thumbnail": "Man smiling confidently in the front of a quirky vehicle, woman lounging in the back seat looking at him with an amused expression.",
        "notes": "Confined-space formats naturally suggest tension/intimacy, making this one of the easier translations on the list.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "Last To Leave RV Wins",
        "channel": "Rebecca Zamolo",
        "url": "https://www.youtube.com/watch?v=Ac6gsEbkS_4",
        "duration": "33:42",
        "published_at": "2026-07-31",
        "niche": "family/last-to-leave challenge",
        "views": "7,051,992 views in the last 90 days (23,300,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 7051992,
        "subscribers": 23300000,
        "score": "7,051,992 views",
        "pattern": "A close-up of a woman shushing the camera builds secrecy, while the background shows a man and another woman in an intimate late-night moment being 'caught'.",
        "trigger": "Voyeuristic curiosity/secrecy — the shush gesture instantly signals 'something is being hidden' and pulls viewers in to find out what.",
        "thumbnail": "Blonde woman close-up making a 'shh' finger-to-lips gesture with wide eyes, background shows a man and another woman sitting together in an RV bed area at night.",
        "formula": "\"Be Quiet!\" - [Location] Last To Leave Challenge",
        "why": "The shush gesture is an instantly readable secrecy cue that promises a payoff worth discovering.",
        "translation": "Direct fit for cold-approach: frame it as catching a secret flirt moment, with the woman shushing the camera while the guy is caught nearby looking guilty.",
        "ca_title": "\"Be Quiet, He'll Hear!\" - Sneaking A Date Past Her Friends",
        "ca_thumbnail": "Woman in foreground shushing the camera with wide eyes, man visible in the background looking caught/smiling, dim intimate lighting.",
        "notes": "This shush/secrecy device is one of the most literal 1:1 translations to flirting content on this list — high test priority.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "Puppies are Reunited after 2 Years! Will they remember?",
        "channel": "The Ninja Fam!",
        "url": "https://www.youtube.com/watch?v=O4-YG3L8pog",
        "duration": "31:02",
        "published_at": "2026-08-15",
        "niche": "pet reunion emotional vlog",
        "views": "5,063,354 views in the last 90 days (4,570,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 5063354,
        "subscribers": 4570000,
        "score": "5,063,354 views",
        "pattern": "A 'then vs. years-later' contrast triggers nostalgia, paired with the woman's genuinely overwhelmed, open-arm reaction to seeing the pets grown up.",
        "trigger": "Nostalgia + emotional stakes (will they recognize me) — a universally strong hook that promises a satisfying payoff.",
        "thumbnail": "Woman with wide-open arms and a shocked/happy expression standing in front of a large group of grown golden doodle dogs, '2 years later' text overlay.",
        "formula": "[People/Pets] Reunited After [Time Period] - Will They Remember [Her]?",
        "why": "Nostalgia combined with an emotional recognition test is one of the most reliably high-performing hooks across niches.",
        "translation": "Reframe as reconnecting with someone approached years ago, testing whether she remembers him, using her surprised reaction as the payoff.",
        "ca_title": "I Found The Girl I Approached 2 Years Ago... Does She Remember Me?",
        "ca_thumbnail": "Woman with a shocked, hands-to-face reaction meeting a man on the street, '2 Years Later' text overlay.",
        "notes": "Reunion/nostalgia hooks translate cleanly and rarely feel forced when reframed around reconnecting with someone.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "Last To Leave Pool Wins",
        "channel": "Rebecca Zamolo",
        "url": "https://www.youtube.com/watch?v=I97iCYHN2KQ",
        "duration": "25:49",
        "published_at": "2026-09-03",
        "niche": "family last-to-leave challenge",
        "views": "5,020,070 views in the last 90 days (23,300,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 5020070,
        "subscribers": 23300000,
        "score": "5,020,070 views",
        "pattern": "A playful underwater 'peeking eyes' shot creates a quirky, instantly recognizable visual tied to a classic endurance challenge title.",
        "trigger": "Suspense of endurance combined with a cute/quirky visual — viewers want to see who breaks first.",
        "thumbnail": "Man, woman, and young girl all submerged up to their eyes underwater in a pool, staring wide-eyed at the camera, 'Last To Leave' text overlay.",
        "formula": "Last To Leave The [Pool/Water] Wins!",
        "why": "The underwater peeking-eyes visual is instantly distinctive and signals a fun, competitive, low-stakes challenge.",
        "translation": "Reframe as a staring-contest style attraction dare — last one to break eye contact or composure while submerged/close wins.",
        "ca_title": "Last To Break Eye Contact Underwater Wins A Kiss",
        "ca_thumbnail": "Man and woman submerged to their eyes in a pool, staring intensely at each other with playful competitive tension.",
        "notes": "Easy to recreate visually with just two people and a pool; strong quirky-hook variety pick.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "I Went Back To School For 24 Hours...",
        "channel": "Topper Guild",
        "url": "https://www.youtube.com/watch?v=Z1zLSyzkPDI",
        "duration": "20:57",
        "published_at": "2026-08-20",
        "niche": "school prank / last-to-leave challenge",
        "views": "3,741,828 views in the last 90 days (94,600,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 3741828,
        "subscribers": 94600000,
        "score": "3,741,828 views",
        "pattern": "An angry authority figure confronts a silenced man while a lineup of reacting classmates watches, creating a 'rule-breaker gets caught' tension hook.",
        "trigger": "Authority/rebellion tension — viewers want to see if the rule-breaker gets away with it.",
        "thumbnail": "Older woman playing an angry teacher pointing a ruler at a man with tape over his mouth, a lineup of students including two women also taped, standing in a school hallway.",
        "formula": "I Went Back To [Rule-Bound Place] For 24 Hours (Undercover)",
        "why": "The 'forbidden/silenced' visual plus an angry authority figure promises a rule-breaking payoff that's fun to watch unfold.",
        "translation": "Reframe as a 'silent flirting challenge' where the guy can't speak to the girl he likes without getting caught by a chaperone, adding stakes to an approach concept.",
        "ca_title": "I Wasn't Allowed To Talk To Her For 24 Hours (Undercover Dating Challenge)",
        "ca_thumbnail": "Woman playing a stern chaperone scolding a man with tape over his mouth, the girl he likes standing nearby with an amused reaction.",
        "notes": "Authority/rule-based tension is a fresh twist distinct from the typical last-to-leave format, good for variety.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
    {
        "title": "KINAWAWA NILA SI SOPHIA! *LAST TO LEAVE THE TENT!*",
        "channel": "Sabby and Sophia",
        "url": "https://www.youtube.com/watch?v=wCRJCIhCAp4",
        "duration": "47:54",
        "published_at": "2026-08-17",
        "niche": "group camping / last-to-leave challenge",
        "views": "2,531,226 views in the last 90 days (8,040,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 2531226,
        "subscribers": 8040000,
        "score": "2,531,226 views",
        "pattern": "A warm, candid group photo of young people crammed into a tent with genuine laughing expressions creates a 'this looks fun, I want in' social-proof hook.",
        "trigger": "Social proof/FOMO — visible genuine joy across multiple faces signals authentic fun and pulls viewers into the group energy.",
        "thumbnail": "Large group of young men and women squeezed together inside a tent outdoors, many genuinely laughing and smiling, close physical proximity, warm daylight.",
        "formula": "[Group] Last To Leave The [Tent/Confined Space] Wins!",
        "why": "Real candid group joy builds trust and curiosity about the social dynamic inside, distinct from staged posed group shots.",
        "translation": "Reframe as a group hangout dare where a man and woman share a genuine laughing moment in close proximity, spotlighting real chemistry.",
        "ca_title": "Last To Leave The Tent With Your Crush Wins",
        "ca_thumbnail": "Group of guys and girls crammed in a tent laughing, with one man and woman close together sharing a genuine laugh in the center of the frame.",
        "notes": "Good variety pick since it showcases a group-proximity dynamic rather than a strict 1:1 pairing.",
        "status": "Not Adapted",
        "scanned_at": "2026-09-25",
    },
]


def _score_num(score_str: str) -> float:
    """Pull the leading numeric multiplier out of a display string like '115.4x channel
    average views' or '114.8x subs' so the dashboard can sort by it."""
    match = re.match(r'[\d,.]+', score_str or "")
    if not match:
        return 0.0
    try:
        return float(match.group().replace(",", ""))
    except ValueError:
        return 0.0


def _video_id(url: str) -> str:
    """Extract the video ID from a youtube.com/watch?v=... URL, for building a static
    thumbnail CDN URL (i.ytimg.com/vi/<id>/...) without needing an API key."""
    match = re.search(r'[?&]v=([\w-]{6,})', url or "")
    return match.group(1) if match else ""


def to_dashboard_row(row: dict) -> dict:
    """Map a SWIPE_FILE entry's field names to the shape the dashboard's data.json
    expects for General Long/Short Form Outliers cards."""
    vid = _video_id(row["url"])
    return {
        "title": row["title"],
        "channel": row["channel"],
        "videoUrl": row["url"],
        "vid": vid,
        "thumbnailUrl": f"https://i.ytimg.com/vi/{vid}/mqdefault.jpg" if vid else "",
        "niche": row["niche"],
        "views": row.get("views_num", 0),
        "viewsRaw": row["views"],
        "scoreRaw": row["score"],
        "scoreNum": _score_num(row["score"]),
        "pattern": row["pattern"],
        "trigger": row["trigger"],
        "titleFormula": row["formula"],
        "translation": row["translation"],
        "coldTitle": row["ca_title"],
        "coldThumbnail": row["ca_thumbnail"],
        "notes": row["notes"],
        "status": row["status"],
        "duration": row.get("duration", ""),
        "publishedAt": row.get("published_at", ""),
    }


def main() -> None:
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data.json")
    write_rows_to_json(path, [to_dashboard_row(row) for row in SWIPE_FILE])
    print(f"Wrote {len(SWIPE_FILE)} swipe file entries to {path}")


if __name__ == "__main__":
    main()
