"""One-off writer for the "General Long Form Outliers" output
(outlier-tracking/general-long-form/data.json): a curated swipe file of viral YouTube
packaging (title + thumbnail psychology) from outside the cold-approach niche, each
translated into a cold-approach-ready title and thumbnail concept.

Entries here must be real, statistically verified outliers found by
general_outlier_finder.py (run via GitHub Actions, since computing view/subscriber/
channel-average multipliers needs live channel stats from the YouTube API) — and must
be genuine RELATIVE outliers, not just big channels doing normal big-channel numbers.
Concretely: a video only qualifies on raw views (1M+) if the channel has under 100K
subscribers, where 1M+ views is itself remarkable. Channels at or above 100K subscribers
must qualify via a relative signal instead — 5x+ subscriber breakout or 20x+ channel-
average breakout — since 1M views means nothing for a channel whose average video
already clears that. (An earlier batch of entries let big channels like MrBeast qualify
purely on absolute views; those got removed once this rule was tightened.)

That finder script only surfaces candidates; picking which ones cleanly translate into
a cold-approach idea — both the title AND the thumbnail concept — and writing the
analysis below is a manual step. Cold-approach thumbnail concepts should put a woman
front and center as the visual star (per the channel's packaging convention), regardless
of whether the original video's thumbnail did. Entries must also be in English — a
language filter (is_english_title in common.py) now screens the finder's
output, but it only catches non-Latin scripts, not other Latin-script languages, so
still verify by eye. This file is not a live API pull itself — run it manually whenever
new entries are added.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from common import write_rows_to_json

SWIPE_FILE = [
    {
        "title": "Japan's TERRIFYING Project to Win the World Cup!!",
        "channel": "Zeyad.",
        "url": "https://www.youtube.com/watch?v=qK6ED0SN-Zc",
        "published_at": "2026-06-10",
        "duration": "14:34",
        "niche": "Sports Strategy Documentary/Analysis",
        "views": "633,553 (2,790 subscribers — 227.1x its subscriber count in views, a massive breakout for a tiny channel)",
        "views_num": 633553,
        "subscribers": 2790,
        "score": "633,553 views",
        "pattern": "A tactical/strategic breakdown framed with dramatic, ominous language (\"terrifying\") rather than neutral analysis language, paired with a composed, authoritative portrait thumbnail.",
        "trigger": "Curiosity about what could possibly make a strategy \"terrifying\" rather than just effective + the authority signal of a composed portrait with tactical diagrams + national pride/rivalry undertones.",
        "thumbnail": "A composed portrait of a football manager in formal attire, tactical formation diagrams and national team crest overlaid, bold red-accented \"TERRIFYING\" text, dramatic red/dark color grade.",
        "formula": "\"[Nation/Group]'s TERRIFYING [Plan/Project] to [Ambitious Goal]!!\"",
        "why": "\"Terrifying\" reframes a neutral strategic analysis as something with real stakes and menace, and the composed authority-figure portrait plus diagrams signals serious, credible analysis rather than clickbait speculation.",
        "translation": "Reframe \"a nation's terrifying strategic plan\" as \"a guy's terrifying-effective systematic approach method\" — same ominous-language-on-a-neutral-topic device, same authority-portrait-plus-diagram credibility signal.",
        "ca_title": "The Terrifying System That Gets Her Number Every Time",
        "ca_thumbnail": "A composed portrait of the creator in confident attire, simple diagram/notes overlaid suggesting a systematic method, bold red-accented \"TERRIFYING\" text, dramatic moody color grade.",
        "notes": "A massive 227x breakout on a channel with under 3,000 subscribers shows that dramatic reframing language on an otherwise ordinary analysis topic can travel far beyond a niche audience.",
        "status": "Not Adapted",
    },
    {
        "title": "I Bought A $1.3M Mansion...They Left Everything Behind",
        "channel": "Jesse Stolz",
        "url": "https://www.youtube.com/watch?v=PzyorkHczpQ",
        "published_at": "2026-06-26",
        "duration": "21:10",
        "niche": "Real Estate Mystery/Documentary",
        "views": "1,407,757 (44.6K subscribers — 31.6x its subscriber count in views, and 29.8x its own channel average, a double breakout)",
        "views_num": 1407757,
        "subscribers": 44600,
        "score": "1,407,757 views",
        "pattern": "A real purchase/exploration documentary that leads with the mystery of an abandonment rather than the property itself, using a direct-address pointing gesture to draw the eye to the specific detail.",
        "trigger": "Curiosity about why someone would leave everything behind (implied backstory mystery) + the personal, direct-address framing making it feel like a real, ongoing investigation.",
        "thumbnail": "A real exterior shot of a large mansion, the creator in the foreground pointing toward it in a ballcap, bold caption \"THEY LEFT EVERYTHING BEHIND\" across the top, natural daylight.",
        "formula": "\"I Bought A $[Price] [Property]...They Left Everything Behind\"",
        "why": "Naming a specific, real, large dollar figure grounds the claim, and \"they left everything behind\" opens a mystery about the previous owners the video promises to explore, not just show off the purchase.",
        "translation": "Reframe \"buying a mystery-abandoned mansion\" as \"approaching a woman with an unexplained, specific mystery detail as the hook\" — same specific-real-detail-implies-a-story device.",
        "ca_title": "I Approached Her... She Had One Detail Nobody Could Explain",
        "ca_thumbnail": "The creator pointing toward a woman in a real setting, bold caption naming the specific unexplained detail, natural daylight, direct-address framing.",
        "notes": "A specific real dollar figure or detail, not a vague superlative, is what makes the mystery premise feel grounded and click-worthy.",
        "status": "Not Adapted",
    },
    {
        "title": "The Hardest Stage of Life Is Between 65 and 75. Here’s Why!",
        "channel": "Candle of Wisdom",
        "url": "https://www.youtube.com/watch?v=h8NzdUh7C0Y",
        "published_at": "2026-05-21",
        "duration": "19:39",
        "niche": "Life-Stage Wisdom/Advice (Talking Head)",
        "views": "1,124,603 (97.3K subscribers — 11.6x its subscriber count in views, and 27.3x its own channel average, a double breakout)",
        "views_num": 1124603,
        "subscribers": 97300,
        "score": "1,124,603 views",
        "pattern": "A direct, authoritative talking-head claim naming a very specific, counterintuitive age range, with \"no one tells you\" promising insider information withheld from the mainstream conversation.",
        "trigger": "Curiosity from a specific, oddly precise claim (why THAT decade specifically?) + the \"secret knowledge\" appeal of information no one tells you.",
        "thumbnail": "An older man speaking directly to camera outdoors, bold on-screen text stating the exact claim and age range, a parenthetical \"(No One Tells You)\" tag, natural daylight, simple unproduced framing.",
        "formula": "\"The Hardest [Life Stage] Is Between [Specific Age Range]. Here's Why! (No One Tells You)\"",
        "why": "A precise, specific numeric range feels more credible and intriguing than a vague claim, and framing it as suppressed/overlooked knowledge adds a why-hasn't-anyone-said-this-before hook.",
        "translation": "Reframe \"the hardest life stage is a specific age range\" as \"the hardest part of approaching/dating is a specific, named phase, not the one people assume\" — same precise-claim + withheld-knowledge structure.",
        "ca_title": "The Hardest Part Of Approaching Isn't What You Think. Here's Why! (No One Tells You)",
        "ca_thumbnail": "The creator speaking directly to camera outdoors, bold on-screen text stating the specific counterintuitive claim, natural daylight, simple unproduced framing.",
        "notes": "Zero-production, direct-to-camera talking-head format proven to work at scale — a viable low-cost companion series alongside in-field footage.",
        "status": "Not Adapted",
    },
    {
        "title": "Real Life Superheroes Caught Saving People On Camera",
        "channel": "FAST - Instant Karma",
        "url": "https://www.youtube.com/watch?v=TKK9nzN6eiU",
        "published_at": "2026-04-18",
        "duration": "27:01",
        "niche": "Hero/Rescue Compilation",
        "views": "767,455 (41.4K subscribers — 18.5x its subscriber count in views, a genuine breakout)",
        "views_num": 767455,
        "subscribers": 41400,
        "score": "767,455 views",
        "pattern": "A compilation format that labels the specific threat directly in bold text, letting the viewer instantly understand the stakes of a real intervention moment.",
        "trigger": "Relief/admiration from watching someone step in during a genuinely dangerous moment + the specificity of a named threat making the danger concrete rather than abstract.",
        "thumbnail": "A real bodycam/security-style scene, an officer running toward a child, a bold red \"KIDNAPPER\" label with an arrow pointing at the fleeing figure, daylight residential setting.",
        "formula": "\"Real Life [Heroic Archetype] Caught [Specific Heroic Action] On Camera\"",
        "why": "Naming the exact danger in bold text, rather than a vague label, makes the stakes instantly legible, and \"real life\" plus \"caught on camera\" promises unstaged, verifiable footage.",
        "translation": "Reframe \"real people caught saving others from danger\" as \"a guy caught stepping in for a woman in an uncomfortable/unsafe situation\" — same named-specific-danger + \"caught on camera\" authenticity framing.",
        "ca_title": "Real Guy Caught Stepping In When She Needed Him On Camera",
        "ca_thumbnail": "A real street scene, the creator visibly stepping toward a woman in a tense moment, a bold red label naming the specific situation, daylight setting.",
        "notes": "Naming the exact danger/threat in bold text is a reusable specificity device already proven elsewhere in this file (RoadGoneWrongTV's \"BRAKE CHECKER\").",
        "status": "Not Adapted",
    },
    {
        "title": "6 Spider-Man explores abandoned buildings, faces aliens, ghost protectors, and The Nun! 😱 Season 1",
        "channel": "Friendly Hero TV",
        "url": "https://www.youtube.com/watch?v=9PWXNhI0xIU",
        "published_at": "2026-07-10",
        "duration": "1:24:49",
        "niche": "Forbidden Access/Urban Exploration (Costume Gimmick)",
        "views": "1,579,107 views in the last 90 days (12,300 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1579107,
        "subscribers": 12300,
        "score": "1,579,107 views",
        "pattern": "A recognizable costume (Spider-Man) worn while exploring genuinely abandoned real locations, adding a playful, low-stakes character to otherwise-eerie forbidden-access content.",
        "trigger": "Novelty of a familiar, non-threatening character encountering real danger/mystery, softening the fear factor into something more fun and shareable, plus curiosity about the specific things found.",
        "thumbnail": "The costumed figure mid-exploration inside a decayed real building, dramatic flashlight lighting, bold text naming a specific found object/threat.",
        "formula": "\"[Costume Character] explores abandoned [buildings/places], faces [specific found things]\"",
        "why": "Wearing a recognizable costume turns a potentially scary premise into something playful and rewatchable, and specifically naming what's found gives concrete curiosity hooks instead of vague \"creepy stuff.\"",
        "translation": "Reframe \"a costumed character exploring abandoned places\" as \"a guy in a fun costume/bit approaching women in a real, specific public setting\" -- same playful-character-in-a-real-environment device.",
        "ca_title": "Spider-Man Approaches Women At The Mall, Faces Rejection, Villains, and One Yes",
        "ca_thumbnail": "The creator in a recognizable costume mid-approach with a woman in a real public setting, bold text naming a specific outcome, playful dramatic lighting.",
        "notes": "The costume does double duty -- it's an icebreaker in the actual approach AND a scroll-stopping visual hook on the thumbnail.",
        "status": "Not Adapted",
    },
    {
        "title": "6 Times Urban Explorers Barely Escaped Death",
        "channel": "Tenebris",
        "url": "https://www.youtube.com/watch?v=1SQKHjI0htY",
        "published_at": "2026-09-11",
        "duration": "33:55",
        "niche": "Forbidden Access/Urban Exploration (Danger Compilation)",
        "views": "1,822,500 views in the last 90 days (38,200 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1822500,
        "subscribers": 38200,
        "score": "1,822,500 views",
        "pattern": "A compilation of several different real close-call moments during urban exploration, the danger itself (not one specific location) is the hook.",
        "trigger": "Vicarious thrill/relief from near-misses, plus the numbered structure promising escalating specific stories rather than one vague scare.",
        "thumbnail": "A real explorer mid-precarious-moment (collapsing floor, high ledge), bold \"BARELY ESCAPED DEATH\" text.",
        "formula": "\"[Count] Times Urban Explorers Barely Escaped Death\"",
        "why": "Numbering distinct real close calls promises variety and escalation within one video, and \"barely escaped\" implies genuine danger without needing to fabricate a single elaborate threat.",
        "translation": "Reframe \"several real close calls while exploring\" as \"several real approaches that almost went wrong before recovering\" -- same numbered-near-miss-compilation structure.",
        "ca_title": "6 Times My Approach Almost Completely Failed (Before It Didn't)",
        "ca_thumbnail": "A real candid mid-conversation shot showing a tense moment, bold \"ALMOST FAILED\" text, natural daylight street setting.",
        "notes": "The near-miss-then-recovery structure creates tension without needing a single big dramatic incident -- several small real ones stacked together does the same job.",
        "status": "Not Adapted",
    },
    {
        "title": "Reuniting With Ferran After 7 Years Royalty Family Surprise",
        "channel": "Real Princess Sophia",
        "url": "https://www.youtube.com/watch?v=ZOvFdjafmVY",
        "published_at": "2026-08-02",
        "duration": "6:05",
        "niche": "Emotional Reunion Surprise (Family)",
        "views": "3,744,506 views in the last 90 days (188,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 3744506,
        "subscribers": 188000,
        "score": "3,744,506 views",
        "pattern": "A specific, named long-gap reunion with a real named person, framed as a family-brand surprise tying into the channel's ongoing family-brand identity.",
        "trigger": "Anticipation heightened by an unusually long, specific time gap, plus brand-recognition for existing viewers of the family's ongoing story.",
        "thumbnail": "A real embrace/reunion moment as the hero image, the specific year-count and name overlaid.",
        "formula": "\"Reuniting With [Named Person] After [Specific Years] [Brand Descriptor] Surprise\"",
        "why": "A specific, unusually long time gap makes the reunion feel more remarkable and researched than \"years later,\" and tying it to an ongoing family brand gives existing viewers a reason to click beyond the reunion alone.",
        "translation": "Reframe \"reuniting with a named family member after a specific long gap\" as \"running into someone from years ago during a real approach\" -- same specific-long-time-gap device applied to an unexpected real-world reconnection.",
        "ca_title": "I Ran Into My High School Crush After 7 Years -- Her Reaction",
        "ca_thumbnail": "A real candid embrace/reaction moment as the hero image, the specific year-count overlaid, warm natural lighting.",
        "notes": "An oddly specific number (7 years, not \"years\") is a small, reusable device for making a claim feel more real and less generic.",
        "status": "Not Adapted",
    },
    {
        "title": "I Returned to Pakistan to Give Back to a Stranger Who Changed My Life",
        "channel": "Isaac Elam",
        "url": "https://www.youtube.com/watch?v=K31fVNPNK6s",
        "published_at": "2026-08-15",
        "duration": "34:22",
        "niche": "Stranger Changed My Life (Reciprocity/Return)",
        "views": "531,006 views in the last 90 days (52,800 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 531006,
        "subscribers": 52800,
        "score": "531,006 views",
        "pattern": "A follow-up/return narrative -- the creator physically travels back to find and repay a specific stranger who once helped them, turning a one-time kindness into a documented full-circle story.",
        "trigger": "Warmth from watching gratitude actually acted upon, not just described, plus the specificity of returning to a real place for a real person raises the stakes of the \"give back.\"",
        "thumbnail": "A real reunion/gratitude moment in the original location, warm natural lighting, minimal text.",
        "formula": "\"I Returned to [Real Place] to Give Back to a Stranger Who Changed My Life\"",
        "why": "Physically returning to enact gratitude turns an abstract \"thank you\" into a concrete, filmable event with its own real payoff moment.",
        "translation": "Reframe \"returning to repay a stranger who helped me\" as \"returning to find and thank someone whose brief encounter mattered more than they knew\" -- same enacted-gratitude, full-circle-return structure.",
        "ca_title": "I Went Back To Find The Girl Whose One Sentence Changed My Life",
        "ca_thumbnail": "A real reunion moment in a recognizable public setting, warm natural lighting, minimal text overlay.",
        "notes": "Turning a story into an enacted follow-up event, not just a recap, gives it a real, fresh payoff moment instead of just retelling old footage.",
        "status": "Not Adapted",
    },
    {
        "title": "BILLIONAIRE TEST | Kind Girl Risk Her Job To Defend Old Woman Been Humiliated | FULL MOVIE",
        "channel": "VOWFALL Stories",
        "url": "https://www.youtube.com/watch?v=GGLGuU-_UwI",
        "published_at": "2026-07-18",
        "duration": "1:23:08",
        "niche": "Disguise/Status Test (Reversed Gender)",
        "views": "1,122,229 views in the last 90 days (63,100 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1122229,
        "subscribers": 63100,
        "score": "1,122,229 views",
        "pattern": "A disguised-status test where the person being tested for kindness is a woman, and the risk she takes raises the stakes of her kindness.",
        "trigger": "Admiration for someone risking something real to defend a vulnerable stranger, plus curiosity about the disguised billionaire's eventual reveal and reaction.",
        "thumbnail": "A real/staged workplace-adjacent confrontation, the kind subject visibly standing up for someone, bold status-test label overlaid.",
        "formula": "\"[Disguised Status] TEST | [Subject] Risk Her [Real Stake] To Defend [Vulnerable Person] Been [Wronged]\"",
        "why": "Making the stake concrete and real turns an abstract kindness test into something with genuine, relatable personal cost for the person being tested.",
        "translation": "Reframe \"a disguised billionaire tests a kind girl who risks her job\" as \"a woman risks social awkwardness/judgment from her friends to genuinely engage during an approach, and the reveal of who the guy really is\" -- same real-personal-stake-plus-disguised-reveal structure.",
        "ca_title": "APPROACH TEST | She Risked Her Friends Judging Her To Actually Talk To Me",
        "ca_thumbnail": "A real street/social scene, a woman visibly choosing to engage despite others nearby, bold label text overlaid matching the original's format.",
        "notes": "Naming a real, specific personal cost, not just \"she was kind,\" is what makes the kindness in these tests feel earned rather than trivial.",
        "status": "Not Adapted",
    },
    {
        "title": "I STOLE a Soft Drink From a Provision Store as a Homeless Mad Man…Her Reaction Left Me in Tears! 😭❤️",
        "channel": "Tunika",
        "url": "https://www.youtube.com/watch?v=DQiW2nrM1Bo",
        "published_at": "2026-07-28",
        "duration": "24:00",
        "niche": "Disguise/Status Test (Provocation)",
        "views": "907,954 views in the last 90 days (76,800 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 907954,
        "subscribers": 76800,
        "score": "907,954 views",
        "pattern": "The disguised tester actively does something mildly provocative rather than passively waiting to be helped, making the \"test\" more of an active social experiment.",
        "trigger": "Curiosity about how a store owner reacts to a disguised low-status person doing something wrong, rather than something neutral, raising the stakes of what \"her reaction\" could mean.",
        "thumbnail": "A real disguised low-status appearance mid-provocative-act, the store setting visible, minimal text.",
        "formula": "\"I STOLE a [Small Item] From a [Real Setting] as a [Disguised Status]...Her [Reaction]\"",
        "why": "Having the disguised subject do something actively provocative creates real uncertainty about the outcome, since the tester isn't purely sympathetic, which raises the stakes of what the reveal could show.",
        "translation": "Reframe \"disguised as homeless, stole a drink, her reaction\" as \"did something a little bold/provocative during a disguised-status approach, and her real reaction\" -- same active-provocation-raises-stakes device.",
        "ca_title": "I Said Something Bold Disguised As The Least Impressive Guy There... Her Reaction",
        "ca_thumbnail": "A real street/venue scene, creator in an unassuming disguised presentation mid-bold-moment, a woman's genuine reaction visible.",
        "notes": "An active provocation, not passive waiting, creates real uncertainty about the outcome, which is what separates this from a purely predictable kindness test.",
        "status": "Not Adapted",
    },
    {
        "title": "Exposing the Truth of MrBeast's Mansion",
        "channel": "Asher Armstrong",
        "url": "https://www.youtube.com/watch?v=XjCauBFTbmw",
        "published_at": "2026-08-11",
        "duration": "29:16",
        "niche": "Investigative/Expose (Named Mega-Celebrity)",
        "views": "826,289 views in the last 90 days (16,500 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 826289,
        "subscribers": 16500,
        "score": "826,289 views",
        "pattern": "An investigative-style expose format aimed at a named mega-celebrity's property, borrowing the format's inherent credibility rather than a documentary tone.",
        "trigger": "Curiosity about \"the truth\" behind something a famous person has publicly shown, implying there's more to the story than what's public.",
        "thumbnail": "A real or composited shot of the celebrity's known property, \"EXPOSING THE TRUTH\" text in an investigative red/yellow style.",
        "formula": "\"Exposing the Truth of [Named Mega-Celebrity]'s [Public-Facing Thing]\"",
        "why": "\"Exposing the truth\" borrows journalistic credibility and implies insider knowledge, which works especially well against a mega-celebrity since the contrast between their public image and the \"real truth\" is inherently interesting.",
        "translation": "Reframe \"exposing the truth of a celebrity's mansion\" as \"exposing the truth behind a well-known dating myth or a specific public figure's approach advice\" -- same investigative-credibility-framing device.",
        "ca_title": "Exposing The Truth About What Actually Gets Her Number",
        "ca_thumbnail": "A real street scene styled with investigative red/yellow text treatment, \"EXPOSING THE TRUTH\" banner, creator mid-approach in frame.",
        "notes": "The investigative-journalism visual language, not documentary softness, is what separates this from a normal exploration video, worth testing on myth-busting dating content specifically.",
        "status": "Not Adapted",
    },
    {
        "title": "[Full] The Day They Hurt Her Daughter, the Mafia Queen Returned🔥",
        "channel": "Queen's Reel",
        "url": "https://www.youtube.com/watch?v=FRIFURFhKKo",
        "published_at": "2026-07-21",
        "duration": "1:40:09",
        "niche": "Status-Reveal/Betrayal (Wealth Twist)",
        "views": "3,348,064 views in the last 90 days (51,200 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 3348064,
        "subscribers": 51200,
        "score": "3,348,064 views",
        "pattern": "A betrayal immediately undercut by a huge status reveal the wrongdoer forgot about, the title itself delivering the entire twist upfront.",
        "trigger": "Satisfaction from watching a wrongdoer's own forgetfulness be their downfall, combined with a huge, specific status contrast that recontextualizes the whole \"betrayal.\"",
        "thumbnail": "A composed, confident real/staged shot of the wronged subject, a luxury detail visible, minimal text stating the forgotten status.",
        "formula": "\"My [Relation] Gave [Their Affair Partner] My [Possession]--[He/She] Forgot I'm the [Status Reveal]!\"",
        "why": "Delivering the twist directly in the title works because the twist itself is the hook, knowing \"she's secretly a billionaire\" upfront makes the viewer want to see exactly how that plays out, rather than being surprised by it.",
        "translation": "Reframe \"gave away my car, forgot I'm a billionaire\" as \"dismissed me during an approach, had no idea who I actually was\" -- same title-delivers-the-twist-upfront status-reveal structure.",
        "ca_title": "She Turned Me Down At The Bar--She Had No Idea I Own The Place",
        "ca_thumbnail": "A real, composed, confident shot of the creator in an upscale real setting, minimal text stating the forgotten status.",
        "notes": "Putting the twist in the title itself, rather than saving it, is a legitimate, different strategy from withheld-twist titles used elsewhere, worth testing both approaches.",
        "status": "Not Adapted",
    },
    {
        "title": "CONFRONTING NASIA ELIZ AFTER CHEATING WITH MY BESTFRIEND | LIFE FORCE SKATE AKO TO CHEAT AKO",
        "channel": "Jd Ramos",
        "url": "https://www.youtube.com/watch?v=PYGGDbm70Jo",
        "published_at": "2026-09-04",
        "duration": "33:34",
        "niche": "Real Confrontation (Named, Direct)",
        "views": "554,773 views in the last 90 days (48,900 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 554773,
        "subscribers": 48900,
        "score": "554,773 views",
        "pattern": "A direct, real, named-person confrontation over infidelity, using ALL CAPS and real names to signal this is an actual documented personal event, not a dramatization.",
        "trigger": "Voyeuristic pull of a real, raw, unscripted confrontation between real named people, heightened by the emotional stakes of infidelity with a close friend specifically.",
        "thumbnail": "A real, raw close-up of the confrontation moment, genuine emotional expressions visible, minimal graphic design.",
        "formula": "\"CONFRONTING [Real Name] AFTER CHEATING WITH MY [Close Relation]\"",
        "why": "Using real names and ALL CAPS signals authenticity and stakes simultaneously, this reads as a genuine personal documentation, not content manufactured for views, which is precisely what makes it compelling.",
        "translation": "Reframe \"confronting a real named person after being cheated on\" as \"a real, raw confrontation moment during an approach when something unexpected comes out\" -- same raw-real-names-ALL-CAPS authenticity device.",
        "ca_title": "CONFRONTING HER ABOUT WHAT SHE ACTUALLY SAID BEHIND MY BACK",
        "ca_thumbnail": "A real, raw close-up mid-confrontation, genuine emotional expressions visible, minimal graphic design matching the original's low-production authenticity.",
        "notes": "Real names and raw, minimal-production framing are what sell the authenticity here, over-producing this format would undercut it immediately.",
        "status": "Not Adapted",
    },
    {
        "title": "Dan Soder Finally Tells Louis C.K. His Most Embarrassing Story 🤣😭💀",
        "channel": "Comedy Commodity",
        "url": "https://www.youtube.com/watch?v=lw-srZPM734",
        "published_at": "2026-07-09",
        "duration": "3:00",
        "niche": "Embarrassing Moment Story (Comedy Clip)",
        "views": "932,894 views in the last 90 days (73,200 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 932894,
        "subscribers": 73200,
        "score": "932,894 views",
        "pattern": "A stand-up/podcast clip built entirely around a real comedian telling their own most embarrassing story, borrowed credibility from a recognizable name doing the telling.",
        "trigger": "Relatable curiosity about embarrassment specifically because a normally-confident, funny public figure is admitting to their own low moment, plus the comedic framing implying it's been anticipated.",
        "thumbnail": "A real clip freeze-frame of the storyteller mid-reaction/laugh, the other person's name included for cross-audience appeal.",
        "formula": "\"[Storyteller] Finally Tells [Other Recognizable Name] His Most Embarrassing Story\"",
        "why": "\"Finally tells\" implies anticipation/history behind the story, and including two recognizable names doubles the potential audience pulled in by name recognition alone.",
        "translation": "Reframe \"a comedian finally tells his most embarrassing story\" as \"someone finally admits their most embarrassing dating/approach story\" -- same anticipation-framing device, applied to a relatable dating admission instead of a general life story.",
        "ca_title": "I Finally Told Her My Most Embarrassing Rejection Story",
        "ca_thumbnail": "A real candid mid-laugh moment between the creator and a woman, casual lighting, minimal text.",
        "notes": "\"Finally tells\" is a small but effective word choice, it implies the story already has weight/history before a single detail is revealed.",
        "status": "Not Adapted",
    },
    {
        "title": "25 Instant Karma Moments Caught On Camera | Best Of The Week #28",
        "channel": "KARMA-HP",
        "url": "https://www.youtube.com/watch?v=JAJVbdKm8bA",
        "published_at": "2026-09-04",
        "duration": "21:26",
        "niche": "Instant Karma Compilation (Traffic/Public)",
        "views": "615,579 views in the last 90 days (2,030 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 615579,
        "subscribers": 2030,
        "score": "615,579 views",
        "pattern": "A numbered countdown compilation format aggregating many short real clips of rude/entitled people getting immediate comeuppance, with a repeatable weekly branded series title.",
        "trigger": "Justice/karma satisfaction stacked across many quick payoffs instead of one, plus the reliability of a recurring branded series building return viewership.",
        "thumbnail": "A grid/collage-style thumbnail showing multiple frozen \"gotcha\" moments at once, bold red \"INSTANT KARMA\" text banner, numbered \"#28\" episode marker.",
        "formula": "\"[Count] Instant Karma Moments Caught On Camera | Best Of The Week #[N]\"",
        "why": "Compilations remove the risk of any single clip underperforming, a weak clip is buried among strong ones, and a numbered weekly series trains an audience to return every week the way a TV show does.",
        "translation": "Reframe \"many strangers getting karma\" as \"many guys' approaches failing or succeeding in quick cuts\" -- a rapid-fire compilation format showing several real interaction outcomes back to back, branded as a recurring weekly series.",
        "ca_title": "25 Approach Reactions Caught On Camera | Best Of The Week #1",
        "ca_thumbnail": "A grid of several small frozen reaction shots from different real approaches, bold red \"HER REACTION\" banner, numbered episode marker matching a weekly series identity.",
        "notes": "The branded weekly-numbered-series device is the real takeaway here -- it's a format that could become the channel's own recurring show rather than one-off videos.",
        "status": "Not Adapted",
    },
    {
        "title": "2000 Craziest Moments Idiots in Cars Get Instant Karma Caught on Camera | Best of The Week !",
        "channel": "WOTA US",
        "url": "https://www.youtube.com/watch?v=mNEwkIIQw5o",
        "published_at": "2026-07-19",
        "duration": "1:56:04",
        "niche": "Instant Karma Compilation (Road Rage)",
        "views": "810,215 views in the last 90 days (10,500 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 810215,
        "subscribers": 10500,
        "score": "810,215 views",
        "pattern": "Similar numbered compilation but road-rage specific, \"idiots in cars\" branding as a recognizable sub-genre.",
        "trigger": "Same justice satisfaction, narrowed to a specific relatable daily annoyance (bad drivers) that gives the compilation a clear identity within the karma genre.",
        "thumbnail": "Dashcam-style freeze frame of a car mid-collision-avoidance or confrontation, bold yellow \"IDIOTS IN CARS\" text, red \"INSTANT KARMA\" stamp.",
        "formula": "\"[Count] Craziest Moments Idiots in [Specific Context] Get Instant Karma Caught on Camera | Best Of [Timeframe] #[N]\"",
        "why": "Narrowing \"karma\" to one specific recognizable annoyance rather than generic \"rude people\" gives the series a clear identity that's easy to subscribe to and recommend by name.",
        "translation": "Reframe \"idiots in cars getting karma\" as \"guys with a specific bad approach habit getting called out\" -- same narrow-identity compilation device, themed around one recognizable dating mistake instead of driving.",
        "ca_title": "Guys Who Won't Take No For An Answer Get Instant Karma | Best Of The Month #1",
        "ca_thumbnail": "A frozen mid-confrontation street shot, bold yellow text naming the specific bad-behavior type, red \"INSTANT KARMA\" stamp matching the branded look.",
        "notes": "Same insight as the other karma entry -- the value here is specifically the narrow, nameable sub-genre identity, not karma content in general.",
        "status": "Not Adapted",
    },
    {
        "title": "Survive 30 Days Chained To A Stranger, Win $250,000",
        "channel": "MrBeast",
        "url": "https://www.youtube.com/watch?v=iYlODtkyw_I",
        "published_at": "2026-06-27",
        "duration": "35:05",
        "niche": "Extreme Challenge (Forced Proximity With Stranger)",
        "views": "96,024,139 views in the last 90 days (517,000,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 96024139,
        "subscribers": 517000000,
        "score": "96,024,139 views",
        "pattern": "A high-production competitive challenge forcing two strangers into constant physical proximity for an extended period, with a large cash prize as the stated goal.",
        "trigger": "Curiosity about how two strangers' relationship evolves under forced, extreme proximity, plus anticipation of the large prize amount.",
        "thumbnail": "Two people literally chained together in a real setting, exaggerated expressions, bold dollar amount overlaid.",
        "formula": "\"Survive [Specific Duration] Chained To A Stranger, Win $[Amount]\"",
        "why": "A concrete constraint (literally chained) forces genuine interaction that can't be avoided, and pairing it with a large specific prize gives the premise a clear stake beyond just curiosity about the dynamic.",
        "translation": "Reframe \"forced to spend 30 days chained to a stranger for money\" as \"committing to a real extended conversation/date with a stranger and seeing where it goes\" -- same forced-proximity-reveals-real-dynamic device, minus the literal chain, applied to a genuine connection challenge.",
        "ca_title": "I Spent 24 Hours Straight With A Complete Stranger -- Here's What Happened",
        "ca_thumbnail": "Creator and a woman together in a real, extended setting, genuine candid expressions, bold \"24 HOURS\" text overlaid.",
        "notes": "The literal physical constraint is what makes MrBeast's version so shareable -- the cold-approach translation should keep some equivalent structural commitment (a stated time/duration) rather than a vague \"hung out.\"",
        "status": "Not Adapted",
    },
    {
        "title": "I Explored Abandoned Locations From My Childhood!",
        "channel": "Alexa Rivera",
        "url": "https://www.youtube.com/watch?v=vKPE1eDdIfk",
        "published_at": "2026-06-23",
        "duration": "18:33",
        "niche": "Forbidden Access/Urban Exploration (Personal Nostalgia)",
        "views": "2,110,445 views in the last 90 days (18,100,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 2110445,
        "subscribers": 18100000,
        "score": "2,110,445 views",
        "pattern": "Same abandoned-exploring device but anchored in the creator's own personal history rather than a celebrity or random location, adding genuine emotional stakes to the exploration.",
        "trigger": "Nostalgia and personal vulnerability from revisiting one's own past in decayed form, giving the forbidden-access thrill an emotional throughline beyond curiosity alone.",
        "thumbnail": "The creator in a real decayed childhood-relevant location, a visibly reflective/emotional expression, minimal text.",
        "formula": "\"I Explored Abandoned Locations From My Childhood!\"",
        "why": "Anchoring exploration in personal history adds real emotional stakes for the creator specifically, which reads as more vulnerable and authentic than pure curiosity-driven exploring.",
        "translation": "Reframe \"exploring my own decayed childhood places\" as \"returning to a real place from my own past during an approach story, and what that meant\" -- same personal-history-anchored-location device.",
        "ca_title": "I Took Her To The Place I Grew Up -- Here's What She Said",
        "ca_thumbnail": "The creator and a woman together in a real, personally meaningful location, genuine reflective expressions, minimal text.",
        "notes": "Personal stakes, not just curiosity, are the differentiator here -- worth using real, specific locations from your own life rather than generic public spots.",
        "status": "Not Adapted",
    },
    {
        "title": "Confronting Real Scammers, Thieves & Cheaters in Public!",
        "channel": "Airrack Uncut",
        "url": "https://www.youtube.com/watch?v=u0k54s9tfLA",
        "published_at": "2026-08-03",
        "duration": "2:45:44",
        "niche": "Confrontation/Justice (Real, In-Person)",
        "views": "1,059,218 views in the last 90 days (601,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1059218,
        "subscribers": 601000,
        "score": "1,059,218 views",
        "pattern": "A well-known creator personally confronts real real-world scammers/thieves in public, in-person rather than online, raising the stakes of the confrontation genre.",
        "trigger": "Satisfaction of watching wrongdoers confronted directly and in person, plus the credibility of a recognized creator putting themselves at real personal risk.",
        "thumbnail": "A real in-person confrontation moment, the creator's genuine intense expression, the wrongdoer visible.",
        "formula": "\"Confronting Real [Wrongdoer Type] in Public!\"",
        "why": "Taking a confrontation format offline and in-person raises real personal stakes and credibility, since the creator is physically present for whatever happens next.",
        "translation": "Reframe \"confronting real scammers in public\" as \"confronting a real, in-person awkward or dismissive moment directly rather than letting it go\" -- same raised-stakes, in-person-not-online confrontation device.",
        "ca_title": "Confronting The Guy Who Was Rude To Her In Public",
        "ca_thumbnail": "A real in-person street scene, the creator's genuine intense expression mid-confrontation, a woman visible nearby.",
        "notes": "Taking any online-native confrontation format into real, in-person footage instantly raises its perceived stakes and authenticity.",
        "status": "Not Adapted",
    },
    {
        "title": "3 Couples with 3 Breakup-Level Confessions | Truth or Drink | Cut",
        "channel": "Cut",
        "url": "https://www.youtube.com/watch?v=SapryT8caj8",
        "published_at": "2026-08-22",
        "duration": "19:09",
        "niche": "Real Couples/Confessions (Direct Dating Niche)",
        "views": "1,580,864 views in the last 90 days (12,400,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1580864,
        "subscribers": 12400000,
        "score": "1,580,864 views",
        "pattern": "Real couples answer increasingly vulnerable relationship questions on camera, with \"truth or drink\" as a game-show structure that gives permission for raw honesty.",
        "trigger": "Voyeuristic curiosity about real couples' private vulnerabilities, heightened by the drinking-game structure implying anything might get said.",
        "thumbnail": "A real couple's genuine tense/vulnerable expression mid-confession, minimal branded text.",
        "formula": "\"[Count] Couples with [Severity Level] Confessions | Truth or Drink\"",
        "why": "A game-show framing gives real couples social permission to say things they normally wouldn't on camera, and grading confessions by severity level sets clear stakes before it plays.",
        "translation": "Already squarely in-niche -- real couples' game-format vulnerable confessions is directly relevant dating content; the reusable device is the graded-severity game structure that licenses raw honesty.",
        "ca_title": "3 Couples Answer Breakup-Level Questions | Truth or Drink",
        "ca_thumbnail": "A real couple's genuine tense expression mid-confession, minimal branded text matching a recognizable game-show format.",
        "notes": "One of the most directly translatable entries in this batch -- this format already IS dating content, just needs your own branded execution.",
        "status": "Not Adapted",
    },
    {
        "title": "FINALLY OFFICIAL COUPLE NA YUNG ZAILAINE | FAMILYAY x MANNIX FAM",
        "channel": "Yukie and Kim",
        "url": "https://www.youtube.com/watch?v=x5iSpRet3lY",
        "published_at": "2026-06-27",
        "duration": "44:36",
        "niche": "Relationship Milestone Reveal (Direct Dating Niche)",
        "views": "1,909,420 views in the last 90 days (798,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1909420,
        "subscribers": 798000,
        "score": "1,909,420 views",
        "pattern": "A real couple's relationship-status milestone (going \"official\") documented as a payoff moment for viewers who've followed their story, tying into ongoing channel narrative.",
        "trigger": "Payoff satisfaction for an audience invested in a will-they-won't-they arc, resolved with a real, definitive status announcement.",
        "thumbnail": "The real couple together, visibly happy, minimal celebratory text.",
        "formula": "\"FINALLY OFFICIAL COUPLE NA YUNG [Names] | [Channel Crossover]\"",
        "why": "\"Finally\" signals this is the payoff to a story the audience has already been following, which works because it resolves anticipation rather than introducing something cold.",
        "translation": "Already squarely in-niche -- real relationship-milestone payoffs are direct dating content; the reusable device is building anticipation across multiple videos before the definitive payoff moment.",
        "ca_title": "We're FINALLY Official -- Here's How It Happened",
        "ca_thumbnail": "The real couple together, visibly happy, minimal celebratory text matching the original's tone.",
        "notes": "This only works if there's a real story the audience has been following -- the payoff needs actual built-up anticipation to land.",
        "status": "Not Adapted",
    },
    {
        "title": "Finally I Proposed Nega ❤️ With a Guinness Record  | Samsameer_insta",
        "channel": "Samsameer_insta",
        "url": "https://www.youtube.com/watch?v=X_83QO-8BX8",
        "published_at": "2026-08-23",
        "duration": "1:03:00",
        "niche": "Proposal Reaction (Extreme Scale)",
        "views": "2,307,155 views in the last 90 days (1,280,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 2307155,
        "subscribers": 1280000,
        "score": "2,307,155 views",
        "pattern": "A real proposal executed at a record-breaking extreme scale, the specific verifiable record claim raising the stakes of an otherwise-common proposal format.",
        "trigger": "Awe at an extreme, specific, verifiable scale claim applied to a universally understood romantic moment.",
        "thumbnail": "The real proposal moment at its extreme scale, her genuine reaction visible, record claim overlaid.",
        "formula": "\"Finally I Proposed [Name] With a Guinness Record\"",
        "why": "A verifiable, named record claim gives an otherwise-common proposal format a concrete, headline-worthy hook.",
        "translation": "Reframe \"proposing with a record-breaking gesture\" as \"a real approach or gesture taken to an extreme, verifiable scale\" -- same specific-verifiable-extreme-claim device applied to a bold romantic gesture.",
        "ca_title": "I Asked Her Out With The World's Largest Bouquet",
        "ca_thumbnail": "A real extreme-scale gesture moment, her genuine reaction visible, record claim overlaid matching the original's format.",
        "notes": "A specific, named, checkable record, not a vague superlative, is what makes an extreme claim feel real rather than exaggerated.",
        "status": "Not Adapted",
    },
    {
        "title": "She finally admitted she's a fraud",
        "channel": "Sydney Watson",
        "url": "https://www.youtube.com/watch?v=IGhFgAei-FI",
        "published_at": "2026-09-09",
        "duration": "25:49",
        "niche": "Confrontation/Reveal (Commentary)",
        "views": "1,929,254 views in the last 90 days (1,170,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1929254,
        "subscribers": 1170000,
        "score": "1,929,254 views",
        "pattern": "A real, named public figure's own admission used as the entire hook, the creator's commentary framing an opponent's words as a self-own.",
        "trigger": "Satisfaction from watching someone's own words become the evidence against them, framed as a long-awaited vindication.",
        "thumbnail": "A real split-screen or reaction shot showing the subject's own admission, minimal text.",
        "formula": "\"[Subject] Finally Admitted [Damaging Truth]\"",
        "why": "\"Finally admitted\" implies this was long-suspected and now proven in the subject's own words, which is more satisfying than an outside accusation because it's self-incriminating.",
        "translation": "Reframe \"she finally admitted she's a fraud\" as \"she finally admitted what she actually thought during the approach\" -- same self-admission-as-vindication device, applied to a genuine reveal moment.",
        "ca_title": "She Finally Admitted She Was Actually Interested The Whole Time",
        "ca_thumbnail": "A real candid reaction shot capturing the admission moment, minimal text matching the original's commentary style.",
        "notes": "Using someone's own words as the proof, not the creator's claim, is what makes this reveal format land as credible rather than one-sided.",
        "status": "Not Adapted",
    },
    {
        "title": "MERYLL SORIANO & DAD, WILLIE REVILLAME: The Journey To Forgiveness & Healing | Karen Davila",
        "channel": "Karen Davila",
        "url": "https://www.youtube.com/watch?v=md_tZjYfJxE",
        "published_at": "2026-08-27",
        "duration": "27:54",
        "niche": "Redemption/Forgiveness (Real Interview)",
        "views": "1,084,854 views in the last 90 days (2,740,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1084854,
        "subscribers": 2740000,
        "score": "1,084,854 views",
        "pattern": "A real, sit-down interview format documenting two real named people's actual journey toward reconciliation, credibility-driven by a recognized journalist host.",
        "trigger": "Emotional investment in a real, ongoing reconciliation between real people, grounded by the credibility of a known interview format/host.",
        "thumbnail": "The two real subjects together, a warm but visibly emotional real moment, minimal text naming the theme.",
        "formula": "\"[Named Subject] & [Named Subject]: The Journey To [Reconciliation Theme]\"",
        "why": "A real interview format lends journalistic credibility to an emotional story, and naming both real people plus the specific theme sets clear, grounded expectations.",
        "translation": "Reframe \"a real interview documenting two people's journey to forgiveness\" as \"a real, sit-down conversation revisiting an old rejection or falling-out and how it resolved\" -- same credible-interview-format-plus-named-real-people device.",
        "ca_title": "We Sat Down Years Later To Talk About Why She Rejected Me",
        "ca_thumbnail": "The creator and a woman together in a real sit-down setting, a warm but visibly reflective moment, minimal text naming the theme.",
        "notes": "The interview format itself, not just the story, lends credibility -- a calm, sit-down conversation reads as more serious/real than a street clip.",
        "status": "Not Adapted",
    },
    {
        "title": "The Strangest Abandoned Mansion...But is Has Something Disturbing Inside (NOT JOKING)",
        "channel": "RangerRickTV",
        "url": "https://www.youtube.com/watch?v=jx0t5jEKJ7M",
        "published_at": "2026-07-05",
        "duration": "36:02",
        "niche": "Forbidden Access/Urban Exploration (Mystery Twist)",
        "views": "1,093,683 views in the last 90 days (409,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1093683,
        "subscribers": 409000,
        "score": "1,093,683 views",
        "pattern": "Same abandoned-mansion device but the hook is an unspecified \"disturbing\" discovery inside, withholding what exactly was found to drive curiosity.",
        "trigger": "Curiosity about a vague but ominous promise that's deliberately left unspecified until the video plays.",
        "thumbnail": "A real decayed mansion interior with one specific unsettling detail partially visible, minimal text hinting at the mystery.",
        "formula": "\"The Strangest Abandoned [Property]...But it Has Something Disturbing Inside\"",
        "why": "Explicitly withholding what the \"disturbing\" thing is creates a stronger curiosity gap than describing it would, since the viewer's imagination fills in worse possibilities than most reveals could match.",
        "translation": "Reframe \"an abandoned mansion with something disturbing inside\" as \"an approach that took an unexpectedly strange turn\" -- same withheld-specific-twist device applied to a real interaction outcome.",
        "ca_title": "This Approach Started Normal...But Something Strange Happened Next",
        "ca_thumbnail": "A real street scene with a genuinely surprised/strange reaction partially visible, minimal text hinting at the twist without naming it.",
        "notes": "Deliberately withholding the specific twist, rather than naming it, is a stronger curiosity device than most explicit reveals -- the imagination gap does the work.",
        "status": "Not Adapted",
    },
    {
        "title": "Exploring the Haunted BACKROOMS of Hospitals...",
        "channel": "Khan Asadi",
        "url": "https://www.youtube.com/watch?v=UdohyMcSk6c",
        "published_at": "2026-08-30",
        "duration": "31:44",
        "niche": "Forbidden Access/Urban Exploration (Internet-Culture Reference)",
        "views": "1,002,666 views in the last 90 days (1,500,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1002666,
        "subscribers": 1500000,
        "score": "1,002,666 views",
        "pattern": "Combines real abandoned-location exploring with the \"backrooms\" internet horror-culture reference, borrowing an existing online mythology for instant recognition among a specific audience.",
        "trigger": "Recognition-based curiosity for viewers already familiar with \"backrooms\" internet culture, plus the specific unsettling context adding a real-world grounding to an internet meme.",
        "thumbnail": "A real decayed hospital corridor shot in the visual style associated with \"backrooms\" content, minimal ominous text.",
        "formula": "\"Exploring the Haunted BACKROOMS of [Specific Real Place Type]...\"",
        "why": "Borrowing an existing internet subculture reference instantly signals the video's tone and audience without needing to explain the aesthetic from scratch.",
        "translation": "Reframe \"exploring the internet-culture backrooms of hospitals\" as borrowing any existing recognizable internet aesthetic/reference and grounding it in a real cold-approach location or moment for built-in audience recognition.",
        "ca_title": "Approaching Women In The Most Liminal, Empty Mall In America",
        "ca_thumbnail": "A real, eerily empty public space shot in a recognizable internet-aesthetic style, creator in frame, minimal ominous text.",
        "notes": "Borrowing a pre-existing internet aesthetic/subculture reference is a shortcut to instant tonal recognition for viewers already inside that culture.",
        "status": "Not Adapted",
    },
    {
        "title": "I Reunited With My Ex Best Friend..",
        "channel": "FaZe Rug",
        "url": "https://www.youtube.com/watch?v=z7RYy-Ga_kk",
        "published_at": "2026-07-25",
        "duration": "38:03",
        "niche": "Reunion Surprise (Estranged Friendship)",
        "views": "4,217,377 views in the last 90 days (29,900,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 4217377,
        "subscribers": 29900000,
        "score": "4,217,377 views",
        "pattern": "A reunion specifically framed around a former close friendship that ended, rather than family or romance, adding tension from the implied falling-out.",
        "trigger": "Curiosity about why the friendship ended and whether reconciliation is genuine, since \"ex best friend\" implies real, unresolved history.",
        "thumbnail": "A real reunion moment between the two former friends, visibly emotional/tense-then-warm expressions.",
        "formula": "\"I Reunited With My Ex [Relationship Type]..\"",
        "why": "\"Ex\" applied to a friendship is an unusual, specific framing that implies real unresolved history, making the reunion feel higher-stakes than a casual catch-up.",
        "translation": "Reframe \"reunited with my ex best friend\" as \"reconnected with someone I had a falling-out with during an approach story, years later\" -- same unresolved-history reunion framing.",
        "ca_title": "I Reunited With The Girl Who Rejected Me 5 Years Ago",
        "ca_thumbnail": "A real reunion moment, visibly tense-then-warming expressions, natural setting matching the original's candid tone.",
        "notes": "Applying \"ex\" to a non-romantic relationship is a small but effective way to signal real unresolved history without overselling it.",
        "status": "Not Adapted",
    },
    {
        "title": "Outsmarted This Scammer…Watch His Reaction Live",
        "channel": "Scammer Payback",
        "url": "https://www.youtube.com/watch?v=ss-k44mStRA",
        "published_at": "2026-07-25",
        "duration": "16:32",
        "niche": "Scam-Baiting/Confrontation (Real-Time Reaction)",
        "views": "1,725,639 views in the last 90 days (9,460,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1725639,
        "subscribers": 9460000,
        "score": "1,725,639 views",
        "pattern": "A confrontation resolved by outsmarting the wrongdoer, with \"watch his reaction live\" promising an unedited, real-time emotional payoff.",
        "trigger": "Satisfaction of watching a wrongdoer out-maneuvered, with \"live\" signaling the reaction hasn't been cut or staged for effect.",
        "thumbnail": "A real live-reaction freeze-frame showing genuine shock/frustration, minimal text.",
        "formula": "\"Outsmarted This [Wrongdoer]...Watch His Reaction Live\"",
        "why": "\"Live\" as a qualifier promises an unedited, real-time reaction rather than a produced cutaway, which raises trust in a genre often assumed to be scripted.",
        "translation": "Reframe \"outsmarted a scammer, watch his live reaction\" as \"turned an awkward or dismissive moment around, watch her real, unedited reaction\" -- same real-time-authenticity-promise device.",
        "ca_title": "I Turned This Around On Her -- Watch Her Reaction Live",
        "ca_thumbnail": "A real live-reaction freeze-frame showing genuine surprise, minimal text matching the original's authenticity-forward style.",
        "notes": "The word \"live\" alone functions as a trust signal in genres prone to staging -- worth using deliberately when footage genuinely is unedited.",
        "status": "Not Adapted",
    },
    {
        "title": "Confronting Angry Paris Scammers!",
        "channel": "Zachcray",
        "url": "https://www.youtube.com/watch?v=6I76KruQXzE",
        "published_at": "2026-09-02",
        "duration": "14:55",
        "niche": "Confrontation (Named Real Location)",
        "views": "1,810,763 views in the last 90 days (673,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1810763,
        "subscribers": 673000,
        "score": "1,810,763 views",
        "pattern": "Real confrontation content grounded in a specific, named real city, adding travel-content appeal and local specificity to the confrontation genre.",
        "trigger": "Curiosity about a specific, real, named location's particular scam culture, plus travel-content appeal of seeing a real famous city.",
        "thumbnail": "A real in-person confrontation in a recognizable city setting, the creator's genuine intense expression.",
        "formula": "\"Confronting Angry [Wrongdoer Type] in [Named Real City]!\"",
        "why": "Naming a specific real city adds travel-content appeal and local specificity that makes the claim feel grounded and researched.",
        "translation": "Reframe \"confronting scammers in a named real city\" as \"approaching women in a specific, named real city while traveling\" -- same named-real-location specificity device.",
        "ca_title": "Approaching Women In Paris For The First Time",
        "ca_thumbnail": "A real recognizable city backdrop, creator mid-approach with a woman, natural daylight matching a travel-vlog feel.",
        "notes": "Naming a real, specific, recognizable location is a reusable device for adding grounded travel appeal to almost any format in this file.",
        "status": "Not Adapted",
    },
    {
        "title": "Scammer CRIES After I HACK Her Live Webcam!",
        "channel": "NanoBaiter",
        "url": "https://www.youtube.com/watch?v=KqkJF9oVmoA",
        "published_at": "2026-07-20",
        "duration": "17:25",
        "niche": "Scam-Baiting/Confrontation (Extreme Reveal)",
        "views": "8,444,928 views in the last 90 days (1,270,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 8444928,
        "subscribers": 1270000,
        "score": "8,444,928 views",
        "pattern": "A confrontation escalated to an extreme technical reveal, with the specific emotional reaction stated as the payoff.",
        "trigger": "Satisfaction of an extreme, technically impressive turnaround against a wrongdoer, with a specific, strong emotional reaction promised upfront.",
        "thumbnail": "A real webcam-captured reaction shot showing genuine distress, bold text naming the emotion.",
        "formula": "\"Scammer CRIES After I HACK Her Live Webcam!\"",
        "why": "Naming the specific emotional reaction rather than a vague \"reacts\" sets a concrete expectation, and the extreme technical method raises the stakes beyond a normal confrontation.",
        "translation": "Reframe \"hacked her webcam, she cried\" as \"did something unexpectedly bold during an approach that led to a genuinely strong, specific emotional reaction\" -- same extreme-method-plus-named-emotional-reaction device.",
        "ca_title": "She CRIED After I Said This During Our Conversation",
        "ca_thumbnail": "A real close-up capturing a genuine strong emotional reaction, bold text naming the specific emotion, natural lighting.",
        "notes": "Naming the exact emotional reaction in the title, not \"reacting,\" is a small but effective specificity upgrade over vaguer emotional promises.",
        "status": "Not Adapted",
    },
    {
        "title": "Telling My Twin I’m Pregnant FULL REACTION - Merrell Twins",
        "channel": "merrelltwins",
        "url": "https://www.youtube.com/watch?v=xJocP_9Q9RY",
        "published_at": "2026-09-08",
        "duration": "15:31",
        "niche": "Relationship Milestone Reveal (Family Reaction)",
        "views": "1,746,477 views in the last 90 days (6,530,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1746477,
        "subscribers": 6530000,
        "score": "1,746,477 views",
        "pattern": "A real, unedited full-length reaction to major personal news shared with someone very close, \"FULL REACTION\" signaling nothing was cut for effect.",
        "trigger": "Curiosity about a genuine, unfiltered reaction to major life news, with \"full reaction\" promising authenticity.",
        "thumbnail": "A real close-up capturing the exact moment of reaction, genuine shocked/emotional expression.",
        "formula": "\"Telling My [Close Relation] I'm [Major News] FULL REACTION\"",
        "why": "\"Full reaction\" signals the footage is complete and unedited, which builds trust that the reaction shown is genuinely spontaneous.",
        "translation": "Reframe \"telling my twin I'm pregnant, full reaction\" as \"telling someone close to me about a real approach/dating outcome, and their full, unfiltered reaction\" -- same complete-unedited-reaction-promise device.",
        "ca_title": "Telling My Best Friend I Got Her Number FULL REACTION",
        "ca_thumbnail": "A real close-up capturing a genuine surprised/excited reaction, natural lighting, minimal text.",
        "notes": "Explicitly labeling a reaction as \"full,\" not a highlight, is a cheap trust signal worth using whenever the footage genuinely is complete.",
        "status": "Not Adapted",
    },
    {
        "title": "We surprised Tom Holland and Zendaya with AMAZING Titanium Flashmob at Spider-Man fan event 😍",
        "channel": "Julien Cohen",
        "url": "https://www.youtube.com/watch?v=aMQOcbZ6Ls4",
        "published_at": "2026-07-29",
        "duration": "3:20",
        "niche": "Celebrity Surprise (Flashmob Gimmick)",
        "views": "5,731,961 views in the last 90 days (7,930,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 5731961,
        "subscribers": 7930000,
        "score": "5,731,961 views",
        "pattern": "A surprise flashmob performance for real, named A-list celebrities, borrowing maximum name recognition to elevate an otherwise-common street-performance format.",
        "trigger": "Curiosity about how two of the most recognizable celebrities in the world would react to an elaborate real surprise, plus the specific memorable song choice.",
        "thumbnail": "A real moment featuring the recognizable celebrities' genuine reaction, the performance visible around them.",
        "formula": "\"We surprised [Named A-List Celebrities] with AMAZING [Specific Performance] at [Real Setting]\"",
        "why": "Using maximum-recognition real names elevates an otherwise-common flashmob format into something with built-in mass appeal, since millions already care about how these specific people react.",
        "translation": "Reframe \"surprising A-list celebrities with a flashmob\" as \"surprising someone with an elaborate, memorable real gesture in a real public setting\" -- same elaborate-real-gesture-plus-genuine-reaction device, scaled to a realistic version.",
        "ca_title": "I Surprised Her With A Flash Mob In The Middle Of The Street",
        "ca_thumbnail": "A real public setting, a woman's genuine surprised reaction as the focal point, the gesture visible around her.",
        "notes": "The elaborate-real-gesture-plus-genuine-reaction structure works at any scale -- the celebrity names here are what make it shareable, but the mechanic works with ordinary real reactions too.",
        "status": "Not Adapted",
    },
    {
        "title": "Everyone Thought She’d Been Dead for 5 Years—Until She Returned With a Daughter",
        "channel": "Scene Zero",
        "url": "https://www.youtube.com/watch?v=6tFgdKrrZcM",
        "published_at": "2026-09-11",
        "duration": "50:15",
        "niche": "Dramatized Reveal (Extreme Time Gap)",
        "views": "630,110 views in the last 90 days (17,600 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 630110,
        "subscribers": 17600,
        "score": "630,110 views",
        "pattern": "A dramatized/staged story built around an extreme, specific false assumption resolved with an even bigger reveal, stacking two twists.",
        "trigger": "Maximum curiosity from an extreme false assumption stated directly in the title, compounded by a second, unstated detail teased as an additional twist.",
        "thumbnail": "A real/staged emotional reunion moment, the returning subject's expression ambiguous between joy and tension.",
        "formula": "\"Everyone Thought [Subject] Had Been Dead for [Specific Years]-Until [Subject] Returned With [Unstated Additional Detail]\"",
        "why": "Stacking two twists rather than just one gives the title two separate curiosity gaps instead of one, compounding the pull to click.",
        "translation": "Reframe \"presumed dead for years, returns with an unstated twist\" as \"assumed gone/uninterested for years, returns to an approach story with an unexpected additional detail\" -- same stacked-double-twist structure.",
        "ca_title": "Everyone Thought She'd Moved On For Good-Until She Showed Up With Something Nobody Expected",
        "ca_thumbnail": "A real/staged emotional reunion moment, an ambiguous expression between joy and tension, natural lighting.",
        "notes": "Stacking two separate twists in one title, not just one, is a reusable way to double the curiosity gap without needing two videos.",
        "status": "Not Adapted",
    },
    {
        "title": "🔥 Sabne Ugly Girl Ko Bully Kiya… Beauty Contest Mein Jo Hua, Sab Shock | Kdrama Explained Hindi|",
        "channel": "Alex Explainer Hindi",
        "url": "https://www.youtube.com/watch?v=RLIEj3aLXQc",
        "published_at": "2026-07-31",
        "duration": "49:45",
        "niche": "Revenge/Transformation (Bully Reversal)",
        "views": "1,108,800 views in the last 90 days (38,100 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1108800,
        "subscribers": 38100,
        "score": "1,108,800 views",
        "pattern": "A bullied-then-transformed narrative resolved at a specific, high-visibility public event, where the reversal happens in front of the original bullies.",
        "trigger": "Satisfaction of watching a specific bullying dynamic reversed at a maximally public, high-stakes moment, in front of the people who caused the original harm.",
        "thumbnail": "A real/staged transformation reveal moment at the specific event, the bullies' shocked reactions visible.",
        "formula": "\"[Bullies] Bullied [Subject]... [Specific Public Event] Mein Jo Hua, Sab Shock\"",
        "why": "Setting the reversal at a specific, real, high-visibility event gives the payoff a concrete stage where the original bullies are forced to witness it directly.",
        "translation": "Reframe \"bullied then transformed, reversal happens at a beauty contest in front of bullies\" as \"someone who felt overlooked shows up transformed to a real event in front of the people who doubted them\" -- same specific-public-stage-reversal device.",
        "ca_title": "They Said She'd Never Get Approached... Then This Happened At The Reunion",
        "ca_thumbnail": "A real event setting, a woman's confident transformed presence as the focal point, others' visible surprised reactions in the background.",
        "notes": "This appears to be animated/illustrated Hindi story content rather than real photography -- verify the actual thumbnail style before using it as a direct visual reference, though the title/reversal structure itself is a strong, reusable packaging lesson regardless.",
        "status": "Not Adapted",
    },
    {
        "title": "Surprising my FAMILY that I'm Pregnant!",
        "channel": "Alanna & Ivor",
        "url": "https://www.youtube.com/watch?v=6dyYJCWUoKg",
        "published_at": "2026-08-13",
        "duration": "12:10",
        "niche": "Family Reaction (Major News Reveal)",
        "views": "4,208,724 views in the last 90 days (1,990,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 4208724,
        "subscribers": 1990000,
        "score": "4,208,724 views",
        "pattern": "A real family's unfiltered reaction to major pregnancy news, capturing multiple genuine reactions from different family members in one scene.",
        "trigger": "Universal emotional resonance of major family news, amplified by capturing several real people's individual genuine reactions in one moment rather than just one.",
        "thumbnail": "A real family group moment, multiple genuine shocked/happy expressions visible at once.",
        "formula": "\"Surprising my FAMILY that I'm [Major News]!\"",
        "why": "Capturing multiple real people's reactions simultaneously gives the moment more visual richness and multiplies the genuine emotional payoff per view.",
        "translation": "Reframe \"surprising family with pregnancy news\" as \"surprising a group of friends/family with news about a real relationship milestone, capturing everyone's real reactions\" -- same multiple-simultaneous-genuine-reactions device.",
        "ca_title": "I Told My Whole Friend Group I Have A Girlfriend -- Their Reactions",
        "ca_thumbnail": "A real group moment, multiple genuine surprised/happy expressions visible at once, natural lighting.",
        "notes": "Capturing several people's reactions in one frame, not cutting between individuals, is what makes this feel like a richer, single big moment.",
        "status": "Not Adapted",
    },
    {
        "title": "Reunited With My Brother After 10 Years (FACE REVEAL)",
        "channel": "Regina & Daniela",
        "url": "https://www.youtube.com/watch?v=5_R6o3wH6_Q",
        "published_at": "2026-08-05",
        "duration": "14:57",
        "niche": "Reunion Surprise (Compounded With Format Gimmick)",
        "views": "1,216,010 views in the last 90 days (1,210,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1216010,
        "subscribers": 1210000,
        "score": "1,216,010 views",
        "pattern": "Compounds a long-gap sibling reunion with a \"face reveal,\" a separate, channel-specific content gimmick, doubling the reasons to watch.",
        "trigger": "Anticipation from two separate payoffs promised at once, the reunion itself AND the channel's own long-teased face reveal.",
        "thumbnail": "A real reunion embrace, faces visible for the first time on the channel, minimal text.",
        "formula": "\"Reunited With My [Family Member] After [Specific Years] (FACE REVEAL)\"",
        "why": "Stacking a personal-story payoff with a separate, pre-existing channel anticipation device pulls in two different audiences' reasons to click at once.",
        "translation": "Reframe \"reunion plus a teased face reveal\" as \"a real reunion moment that also resolves a separate piece of anticipation you've built with your own audience\" -- same double-payoff-stacking device, adaptable to whatever anticipation a channel has already built.",
        "ca_title": "I Ran Into My Ex After 10 Years (FIRST TIME SHOWING MY FACE)",
        "ca_thumbnail": "A real candid reunion moment, the creator's face shown clearly for the first time on camera, natural lighting, minimal text.",
        "notes": "This device only works if there's a genuine separate anticipation already built with your audience -- don't fabricate a \"reveal\" that isn't real.",
        "status": "Not Adapted",
    },
    {
        "title": "Marumagal Gave Us a HUGE Surprise! 😍🚗❤️ | New Car Reveal | @Mrrockyy",
        "channel": "Latto’s Kitchen",
        "url": "https://www.youtube.com/watch?v=u_Hvn_QidZc",
        "published_at": "2026-08-19",
        "duration": "8:08",
        "niche": "Family Surprise Reveal (Material Gift)",
        "views": "1,531,450 views in the last 90 days (804,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1531450,
        "subscribers": 804000,
        "score": "1,531,450 views",
        "pattern": "A real family surprise built around revealing a significant material gift, the emotional context elevating what could otherwise be a purely materialistic reveal.",
        "trigger": "Warmth from watching a loved one receive an unexpected, significant gift, grounded by the real family relationship giving it emotional weight beyond the object itself.",
        "thumbnail": "A real reaction moment at the reveal, the gift visible, genuine joyful expression.",
        "formula": "\"[Family Member] Gave Us a HUGE Surprise! | [Specific Gift] Reveal\"",
        "why": "Framing a significant material reveal through a real family relationship gives it emotional stakes that a pure purchase-flex video wouldn't have.",
        "translation": "Reframe \"family surprises us with a new car\" as \"someone surprises a person they're interested in with a thoughtful, significant real gesture, and the genuine reaction\" -- same relationship-grounded-significant-reveal device.",
        "ca_title": "I Surprised Her With Something She's Wanted For Years -- Her Reaction",
        "ca_thumbnail": "A real reaction moment at the reveal, the gift/gesture visible, genuine joyful expression, warm natural lighting.",
        "notes": "The relationship context, not the object's value alone, is what makes a material-gift reveal feel warm rather than showy -- keep that framing front and center.",
        "status": "Not Adapted",
    },
    {
        "title": "Twin Telepathy with REAL TWINS!",
        "channel": "Rebecca Zamolo",
        "url": "https://www.youtube.com/watch?v=jexniOCPo64",
        "published_at": "2026-08-02",
        "duration": "25:54",
        "niche": "Gimmick Challenge (Intuition/Connection Test)",
        "views": "1,618,242 views in the last 90 days (23,300,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1618242,
        "subscribers": 23300000,
        "score": "1,618,242 views",
        "pattern": "A recurring branded challenge format testing whether two people can read each other's minds/intuition, real reactions to correct and incorrect guesses driving the tension.",
        "trigger": "Curiosity about whether a claimed psychic-style connection is real, resolved live and verifiably in real time through a simple guessing game.",
        "thumbnail": "Two real people facing each other mid-guess, exaggerated surprised expressions, bold \"TELEPATHY\" text.",
        "formula": "\"[Connection Type] Telepathy with REAL [Relationship]!\"",
        "why": "Framing a simple guessing game as a test of a real claimed connection (twins, telepathy) gives an otherwise mundane game format genuine stakes and a verifiable pass/fail moment.",
        "translation": "Reframe \"twins testing telepathy\" as \"testing whether a stranger can guess something real about me within seconds of meeting\" -- same live, verifiable connection-test device applied to a cold approach.",
        "ca_title": "I Tested If She Could Guess Something True About Me In 10 Seconds",
        "ca_thumbnail": "The creator and a woman facing each other mid-guess, genuine surprised expression, bold text naming the test.",
        "notes": "A simple, verifiable pass/fail test (not a vague vibe check) is what gives this format real tension -- the guess is either right or it isn't, live on camera.",
        "status": "Not Adapted",
    },
    {
        "title": "Investigating a Haunted Mansion from 1931! *extreme*",
        "channel": "Zarckaroo Vlogs",
        "url": "https://www.youtube.com/watch?v=y0PUN6ZzpZg",
        "published_at": "2026-07-17",
        "duration": "16:22",
        "niche": "Forbidden Access/Urban Exploration (Named Era)",
        "views": "1,619,202 views in the last 90 days (2,000,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 1619202,
        "subscribers": 2000000,
        "score": "1,619,202 views",
        "pattern": "Same abandoned-mansion device anchored by a specific historical year rather than a celebrity name, grounding the mystery in a concrete era.",
        "trigger": "Curiosity about a place frozen in a specific, real, distant year, plus the \"*extreme*\" tag signaling unusually thorough or risky access.",
        "thumbnail": "A real decayed mansion interior, the specific year overlaid, dramatic flashlight lighting.",
        "formula": "\"Investigating a Haunted [Property] from [Specific Year]! *extreme*\"",
        "why": "A specific, real year (not \"old\") gives the location a concrete historical identity, and self-labeling the exploration \"*extreme*\" sets viewer expectations for unusually deep access.",
        "translation": "Reframe \"a mansion frozen since a specific year\" as \"approaching at a real venue with a specific, storied history\" -- same named-era-specificity device.",
        "ca_title": "Approaching Women At A Bar That's Been Open Since 1931",
        "ca_thumbnail": "A real historic venue exterior/interior, the specific year overlaid, creator in frame, warm period-appropriate lighting.",
        "notes": "A specific real year is a cheap, reusable way to add grounded history to any real-place packaging, the same device as naming a real person, just anchored in time instead.",
        "status": "Not Adapted",
    },
    {
        "title": "A New Level Of Entitlement | Reading Reddit Stories",
        "channel": "Smosh Pit",
        "url": "https://www.youtube.com/watch?v=cgD5eMHNYRI",
        "published_at": "2026-07-11",
        "duration": "1:10:04",
        "niche": "Reaction/Story-Reading (Real Cast)",
        "views": "3,078,549 views in the last 90 days (9,620,000 subscribers) -- a real, high-reach video used here as a proven thumbnail/title/retention example regardless of channel size.",
        "views_num": 3078549,
        "subscribers": 9620000,
        "score": "3,078,549 views",
        "pattern": "A recognizable real cast reacts live to real user-submitted stories, the specific labeled theme (entitlement) setting a clear emotional lens before any story is read.",
        "trigger": "Relatable frustration/schadenfreude toward a named universal social behavior (entitlement), amplified by watching real, known personalities react genuinely as they read.",
        "thumbnail": "The real cast's genuine exaggerated reaction mid-read, bold text naming the specific behavior theme.",
        "formula": "\"A New Level Of [Named Social Behavior] | Reading [Platform] Stories\"",
        "why": "Naming a specific, recognizable social behavior as the theme (rather than \"crazy stories\") gives viewers an instant emotional frame before a single story is read, and real hosts' live reactions carry the format rather than the stories alone.",
        "translation": "Reframe \"reacting to entitled-people stories\" as \"reacting live to real, submitted dating/approach horror stories with a named behavioral theme\" -- same labeled-theme-plus-live-real-reaction device.",
        "ca_title": "A New Level Of Rejection | Reading Your Worst Approach Stories",
        "ca_thumbnail": "The creator's genuine exaggerated reaction mid-read, bold text naming the specific theme, casual studio lighting.",
        "notes": "Naming the specific behavioral theme up front, not just \"stories,\" is what gives an otherwise-generic reaction format a clear emotional hook before it starts.",
        "status": "Not Adapted",
    },
]


def _score_num(score_str: str) -> float:
    """Pull the leading numeric multiplier out of a display string like '115.4x channel
    average views' or '114.8x subs' so the dashboard can sort by it."""
    match = re.match(r'[\d,.]+', score_str or "")
    if not match:
        return 0.0
    try:
        return float(match.group().replace(",", ""))
    except ValueError:
        return 0.0


def _video_id(url: str) -> str:
    """Extract the video ID from a youtube.com/watch?v=... URL, for building a static
    thumbnail CDN URL (i.ytimg.com/vi/<id>/...) without needing an API key."""
    match = re.search(r'[?&]v=([\w-]{6,})', url or "")
    return match.group(1) if match else ""


def to_dashboard_row(row: dict) -> dict:
    """Map a SWIPE_FILE entry's field names to the shape the dashboard's data.json
    expects for General Long/Short Form Outliers cards."""
    vid = _video_id(row["url"])
    return {
        "title": row["title"],
        "channel": row["channel"],
        "videoUrl": row["url"],
        "vid": vid,
        "thumbnailUrl": f"https://i.ytimg.com/vi/{vid}/mqdefault.jpg" if vid else "",
        "niche": row["niche"],
        "views": row.get("views_num", 0),
        "viewsRaw": row["views"],
        "scoreRaw": row["score"],
        "scoreNum": _score_num(row["score"]),
        "pattern": row["pattern"],
        "trigger": row["trigger"],
        "titleFormula": row["formula"],
        "translation": row["translation"],
        "coldTitle": row["ca_title"],
        "coldThumbnail": row["ca_thumbnail"],
        "notes": row["notes"],
        "status": row["status"],
        "duration": row.get("duration", ""),
        "publishedAt": row.get("published_at", ""),
    }


def main() -> None:
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data.json")
    write_rows_to_json(path, [to_dashboard_row(row) for row in SWIPE_FILE])
    print(f"Wrote {len(SWIPE_FILE)} swipe file entries to {path}")


if __name__ == "__main__":
    main()
